// Begrijpend lezen — thema "Fantastische families" (Blink, groep 7-8).
//
// Per les tien tekstfragmenten uit de lesbladen. Bij elk fragment staat een
// vraag voor groep 7 (g7) en een voor groep 8 (g8): dezelfde tekst, maar in
// groep 8 meer afleiden en beoordelen, met lastigere foute antwoorden.
//
// Vraagsoorten:
//   mark  — markeer in de tekst. `antwoord` is het letterlijke stuk tekst,
//           `kern` de woorden die er minstens in moeten zitten.
//   mc    — meerkeuze, `goed` is de index van het juiste antwoord.
//   order — zet op volgorde, `items` staan al in de goede volgorde.
//   drag  — sleep naar een groep: `items` is een lijst [tekst, groep].
// `soort` (alleen mc): 'afleiden' of 'beoordelen'.
//
// Bouwen: node scripts/begrijpend/maak-families.mjs

export const LESSEN = [
  {
    nr: 1, titel: 'Een koninklijke ruzie', emoji: '👑', cover: 'l1-paspoort2',
    intro: 'Je leest de dagboeken van koning Willem II en zijn zoon Willem III. Allebei schrijven ze over de nieuwe grondwet van 1848, maar ze denken er heel anders over.',
    klaar: 'Goed gedaan, geschiedenisspeurder!',
    vragen: [
      {
        img: 'l1-willem2', bijschrift: 'Koning Willem II',
        passage: '7 oktober 1840. Vandaag verandert mijn leven. Mijn vader doet afstand van de troon. Vanaf nu ben ík koning van Nederland. Dat klinkt feestelijk, maar het is ook spannend. Want nu moet ík de belangrijke beslissingen nemen. Pff, best lastig! Gelukkig heb ik wel veel macht om dingen te regelen. En ik ben niet de enige: ook in veel andere landen in Europa zijn de koningen machtig.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom Willem II het spannend vindt om koning te worden.',
          antwoord: 'Want nu moet ík de belangrijke beslissingen nemen.', kern: ['belangrijke', 'beslissingen', 'nemen'],
          feedback: 'Het staat in de zin: "Want nu moet ík de belangrijke beslissingen nemen." Het woord "want" geeft de reden.' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Welk gevoel past het best bij Willem II op 7 oktober 1840?',
          opties: ['Hij is alleen maar blij, want koning zijn is een feest', 'Hij is trots, maar ook een beetje zenuwachtig', 'Hij is boos dat zijn vader ermee stopt', 'Hij is bang dat het volk hem niet wil'], goed: 1,
          feedback: 'Hij schrijft dat het "feestelijk" klinkt, maar ook "spannend" is, en hij zucht "Pff, best lastig!". Twee gevoelens tegelijk dus.' },
      },
      {
        img: 'l1-willem2-paard', bijschrift: 'Koning Willem II te paard',
        passage: '12 januari 1848. Ik hoor allerlei verontrustende berichten uit Europa. Steeds meer mensen vinden het oneerlijk dat koningen zoveel macht hebben. Ze vragen zich af waarom één man zoveel mag bepalen over een heel land. Vandaag kwam er nieuws uit Sicilië. Daar komen mensen in opstand tegen hun leiders. Dit is geen klein protest. Het is veel groter dan dat: een revolutie! De mensen willen vrijheid, invloed en minder macht voor één leider. Ik hoop maar dat het niet overslaat naar mijn eigen volk …',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat de mensen in Sicilië willen.',
          antwoord: 'De mensen willen vrijheid, invloed en minder macht voor één leider.', kern: ['vrijheid', 'invloed', 'macht'],
          feedback: 'Het staat in de zin: "De mensen willen vrijheid, invloed en minder macht voor één leider."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat bedoelt Willem II met: "Ik hoop maar dat het niet overslaat naar mijn eigen volk"?',
          opties: ['Hij hoopt dat een ziekte uit Sicilië niet naar Nederland komt', 'Hij is bang dat de Nederlanders ook in opstand komen, tegen hém', 'Hij wil dat de Nederlanders de mensen in Sicilië gaan helpen', 'Hij hoopt dat zijn volk niet naar Sicilië verhuist'], goed: 1,
          feedback: '"Het" is de revolutie. Willem II is bang dat de onrust ook naar Nederland komt, en dan is hij zelf de koning tegen wie het volk in opstand komt.' },
      },
      {
        passage: '24 februari 1848. Oh nee, ook in Frankrijk is er een revolutie begonnen. In Parijs gaan mensen de straat op, er worden barricades gebouwd en er wordt gevochten. De Franse koning moet zelfs vluchten! Ik schrik hiervan. Frankrijk ligt niet ver van Nederland. Wat als de onrust overslaat? Wat als mensen hier ook in opstand komen tegen de koning? Tegen mij dus! Ik kan doen alsof er niets aan de hand is. Maar ik voel dat dat gevaarlijk is. Misschien moet ik iets veranderen voordat het te laat is.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom schrikt Willem II van het nieuws uit Frankrijk?',
          opties: ['Omdat hij de Franse koning goed kent', 'Omdat Frankrijk dichtbij ligt en de onrust kan overslaan naar Nederland', 'Omdat er in Parijs met zijn geld barricades worden gebouwd', 'Omdat hij zelf naar Frankrijk moet vluchten'], goed: 1,
          feedback: 'Hij schrijft: "Frankrijk ligt niet ver van Nederland. Wat als de onrust overslaat?"' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Willem II noemt twee dingen die hij kan doen. Voor welke keuze voelt hij het meest?',
          opties: ['Doen alsof er niets aan de hand is', 'Zelf naar Parijs gaan om de Franse koning te helpen', 'Iets veranderen voordat de onrust ook in Nederland begint', 'De barricades in Parijs laten afbreken'], goed: 2,
          feedback: 'Doen alsof er niets aan de hand is, voelt voor hem "gevaarlijk". Daarom schrijft hij: "Misschien moet ik iets veranderen voordat het te laat is."' },
      },
      {
        img: 'l1-grondwet', bijschrift: 'Een bladzijde uit de grondwet van 1814. Je ziet dat de koning (toen nog "de vorst") veel macht had.',
        passage: '17 maart 1848. Vandaag neem ik een belangrijk besluit. Ik wil dat de grondwet verandert. In de grondwet staan de belangrijkste regels van een land. Ik vraag Johan Rudolph Thorbecke en een groep andere mannen om nieuwe regels te maken. Die regels moeten ervoor zorgen dat de koning minder macht krijgt. 3 november 1848. Vandaag is het zover: Nederland krijgt een nieuwe grondwet. Vanaf nu is de koning niet meer in zijn eentje de baas. Ik geef dus een deel van mijn macht weg. Dat zou ik liever niet doen, maar ik ben ervan overtuigd dat het wel moet. Zo houd ik de rust in het land. Anders komen de mensen misschien in opstand, zoals in Frankrijk.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat er in een grondwet staat.',
          antwoord: 'In de grondwet staan de belangrijkste regels van een land.', kern: ['belangrijkste', 'regels', 'land'],
          feedback: 'Het staat in de zin: "In de grondwet staan de belangrijkste regels van een land."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Willem II geeft macht weg, terwijl hij dat "liever niet" doet. Waarom doet hij het toch?',
          opties: ['Thorbecke dwingt hem om macht weg te geven', 'Hij wil dat zijn zoon later minder macht heeft', 'Hij denkt dat hij zo een opstand zoals in Frankrijk kan voorkomen', 'Het volk heeft de macht al van hem afgepakt'], goed: 2,
          feedback: 'Hij schrijft: "Zo houd ik de rust in het land. Anders komen de mensen misschien in opstand, zoals in Frankrijk." Thorbecke maakte alleen de nieuwe regels, op zijn verzoek.' },
      },
      {
        img: 'l1-willem3', bijschrift: 'Koning Willem III',
        passage: '24 februari 1848. Er komen vreemde berichten uit Europa. In Frankrijk zijn mensen in opstand gekomen. De Franse koning moet zelfs vluchten! Mensen willen meer vrijheid en minder macht voor koningen. Ik snap daar weinig van. Waarom zou een koning minder macht moeten hebben? Een land heeft toch juist een sterke koning nodig? 19 oktober 1848. Ik ben woedend! Mijn vader wil de grondwet veranderen zodat de koning minder macht krijgt. Maar ik vind dat een grote fout. Een koning hoort het land te leiden. Daar heb ik me jaren op voorbereid. En nu laat mijn vader de regels veranderen!',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Hoe denkt Willem III over het plan van zijn vader?',
          opties: ['Hij vindt het een goed plan', 'Hij is het er helemaal niet mee eens en is woedend', 'Het kan hem niet zoveel schelen', 'Hij snapt het plan niet, maar vindt het wel spannend'], goed: 1,
          feedback: 'Hij schrijft: "Ik ben woedend!" en "Maar ik vind dat een grote fout."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Willem III schrijft: "Daar heb ik me jaren op voorbereid." Waarom zet hij dat erbij?',
          opties: ['Om te laten zien dat hij nog niet klaar is om koning te worden', 'Om uit te leggen waarom hij zo boos is: hij raakt iets kwijt waar hij lang voor heeft geoefend', 'Om zijn vader te bedanken voor de goede voorbereiding', 'Om te vertellen dat hij al jaren de grondwet wil veranderen'], goed: 1,
          feedback: 'Willem III heeft zich jarenlang voorbereid om een machtige koning te worden. Nu wordt de koning minder machtig. Daarom is hij zo woedend.' },
      },
      {
        img: 'l1-inhuldiging', bijschrift: 'Op 12 mei 1849 werd Willem III ingehuldigd in de Nieuwe Kerk in Amsterdam.',
        passage: '17 maart 1849. Vandaag is mijn vader gestorven. Dat maakt me verdrietig. Maar het betekent ook dat ik hem moet opvolgen. Vanaf nu ben ik de koning van Nederland. Eerder wilde ik nog afstand doen van mijn recht op de troon, maar dat kan niet zomaar. Daarom zal ik de kroon aanvaarden. Alleen, ik word niet de koning die ik vroeger dacht te worden. Ik krijg niet de macht die mijn vader eerst had. Ik moet regeren volgens de nieuwe grondwet waar ik zo tegen was. Ministers zijn belangrijker geworden en het parlement heeft meer te zeggen. De koning is niet meer alleen de baas. Daar baal ik flink van.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wie er meer te zeggen hebben gekregen door de nieuwe grondwet.',
          antwoord: 'Ministers zijn belangrijker geworden en het parlement heeft meer te zeggen.', kern: ['Ministers', 'parlement', 'meer'],
          feedback: 'Het staat in de zin: "Ministers zijn belangrijker geworden en het parlement heeft meer te zeggen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom is 17 maart 1849 voor Willem III een dag met dubbele gevoelens?',
          opties: ['Hij is blij dat hij eindelijk koning wordt met veel macht', 'Hij is verdrietig om zijn vader én hij baalt dat hij koning wordt met minder macht', 'Hij is boos op zijn vader omdat die is gestorven', 'Hij is opgelucht dat hij geen koning hoeft te worden'], goed: 1,
          feedback: 'Hij is verdrietig omdat zijn vader is gestorven. En hij wordt nu koning, maar met minder macht dan hij wilde: "Daar baal ik flink van."' },
      },
      {
        passage: 'Op 3 november 1848 kreeg Nederland een nieuwe grondwet. Dat plan begon al op 17 maart 1848, toen Willem II aan Thorbecke vroeg om nieuwe regels te maken. Willem II was toen al acht jaar koning: hij kwam in 1840 op de troon. Hij schrok van de revoluties in Europa: eerst in Sicilië, een maand later in Frankrijk. Zijn zoon Willem III was het niet met hem eens. Een paar weken voordat de nieuwe grondwet er kwam, schreef hij zijn vader een boze brief. In maart 1849 stierf Willem II en werd Willem III koning.',
        g7: { type: 'order', vraag: 'Zet deze gebeurtenissen op volgorde. Wat gebeurde het eerst?',
          items: ['Willem II wordt koning', 'Er is een revolutie in Frankrijk', 'Nederland krijgt een nieuwe grondwet', 'Willem III wordt koning'],
          feedback: '1840 Willem II koning → februari 1848 revolutie in Frankrijk → november 1848 nieuwe grondwet → maart 1849 Willem III koning.' },
        g8: { type: 'order', vraag: 'Zet deze gebeurtenissen op volgorde. Let goed op woorden als "eerder" en "later".',
          items: ['Er is een revolutie in Sicilië', 'Er is een revolutie in Frankrijk', 'Willem II vraagt Thorbecke om nieuwe regels', 'Willem III schrijft zijn vader een boze brief', 'Nederland krijgt een nieuwe grondwet', 'Willem III wordt koning'],
          feedback: 'Januari 1848 Sicilië → een maand later Frankrijk → 17 maart 1848 Thorbecke → oktober 1848 de boze brief (een paar weken vóór de grondwet) → 3 november 1848 nieuwe grondwet → maart 1849 Willem III koning.' },
      },
      {
        passage: 'In 1848 liet koning Willem II de grondwet veranderen. Daardoor werd Nederland een beetje democratischer: het volk kreeg meer te zeggen en de koning juist minder. Dit veranderde er: De koning kon niet meer in zijn eentje alles beslissen. Ministers moesten voortaan aan het parlement uitleggen waarom ze iets hadden besloten. Het parlement is een groep mensen die namens het volk meepraat en meebeslist over het land. Het parlement kreeg meer macht, vooral de Tweede Kamer. Mannen die genoeg belasting betaalden, mochten voortaan kiezen wie er in de Tweede Kamer kwamen. Alle mensen in Nederland kregen meer vrijheid. Je mocht nu bijvoorbeeld zeggen wat je dacht: dat heet vrijheid van meningsuiting. Toch mocht lang niet iedereen meebeslissen. Vrouwen en veel mannen mochten nog niet stemmen.',
        g7: { type: 'drag', vraag: 'Wie kreeg in 1848 meer te zeggen en wie minder? Sleep ze naar de goede kant.',
          cats: ['Meer te zeggen', 'Minder te zeggen'],
          items: [['De koning', 'Minder te zeggen'], ['Het parlement', 'Meer te zeggen'], ['De Tweede Kamer', 'Meer te zeggen'], ['Het volk', 'Meer te zeggen']],
          feedback: 'Het volk, het parlement en vooral de Tweede Kamer kregen meer te zeggen. De koning kon niet meer in zijn eentje alles beslissen.' },
        g8: { type: 'drag', vraag: 'Wat veranderde er al in 1848, en wat nog niet? Sleep ze naar de goede kant.',
          cats: ['Al in 1848', 'Nog niet in 1848'],
          items: [['Ministers leggen uit aan het parlement', 'Al in 1848'], ['Vrijheid van meningsuiting', 'Al in 1848'], ['Mannen die genoeg belasting betalen, mogen kiezen', 'Al in 1848'], ['Vrouwen mogen stemmen', 'Nog niet in 1848'], ['Alle mannen mogen stemmen', 'Nog niet in 1848']],
          feedback: 'Alleen mannen die genoeg belasting betaalden, mochten kiezen. Vrouwen en veel andere mannen mochten nog niet stemmen.' },
      },
      {
        passage: 'Koning Willem II stierf op 17 maart 1849. Zijn zoon Willem III volgde hem op. Willem III moest het doen met de regels die zijn vader had gemaakt. Maar daar was hij helemaal niet blij mee. Je zou denken: dan verandert hij die grondwet toch gewoon weer? Maar zo makkelijk ging dat niet. In de nieuwe grondwet stond namelijk dat de koning minder macht had. De koning kon dus niet meer zomaar in zijn eentje de belangrijkste regels veranderen. Balen voor Willem III, maar fijn voor het volk.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom Willem III de grondwet niet zomaar weer kon veranderen.',
          antwoord: 'In de nieuwe grondwet stond namelijk dat de koning minder macht had.', kern: ['koning', 'minder', 'macht'],
          feedback: 'Het staat in de zin: "In de nieuwe grondwet stond namelijk dat de koning minder macht had." Het woord "namelijk" geeft de reden.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'De schrijver eindigt met: "Balen voor Willem III, maar fijn voor het volk." Wat bedoelt de schrijver?',
          opties: ['Willem III was een slechte koning, en daar was het volk blij om', 'Dezelfde regel was slecht nieuws voor de koning, maar goed nieuws voor de mensen', 'Het volk vond het fijn dat Willem III verdrietig was', 'Willem III baalde, maar later veranderde hij de grondwet toch'], goed: 1,
          feedback: 'De regel dat de koning minder macht heeft, was vervelend voor Willem III, maar goed voor het volk: dat kreeg meer te zeggen.' },
      },
      {
        passage: 'Toch mocht lang niet iedereen meebeslissen. Vrouwen en veel mannen mochten nog niet stemmen. Nederland werd dus democratischer, maar was nog lang geen echte democratie zoals nu. Wist je dat onze grondwet al meer dan 200 jaar oud is? De eerste versie werd gemaakt in 1814.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom was Nederland in 1848 nog geen echte democratie?',
          opties: ['Omdat er nog een koning was', 'Omdat vrouwen en veel mannen nog niet mochten stemmen', 'Omdat er nog geen parlement was', 'Omdat niemand mocht zeggen wat hij dacht'], goed: 1,
          feedback: 'In een echte democratie mag iedereen meebeslissen. In 1848 mochten vrouwen en veel mannen nog niet stemmen.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Iemand zegt: "Na 1848 besliste het hele volk mee over het land." Wat is het beste antwoord?',
          opties: ['Klopt, want het parlement praat namens het volk', 'Klopt niet helemaal: het volk kreeg meer te zeggen, maar vrouwen en veel mannen mochten nog niet stemmen', 'Klopt niet: na 1848 had de koning juist meer macht', 'Klopt, want iedereen kreeg vrijheid van meningsuiting'], goed: 1,
          feedback: 'Nederland werd democratischer, maar "lang niet iedereen" mocht meebeslissen. Vrijheid van meningsuiting is iets anders dan mogen stemmen.' },
      },
    ],
  },
  {
    nr: 2, titel: 'Dappere Drucker', emoji: '✊', cover: 'l2-krant',
    intro: 'Je leest het maandblad Voorwaarts! uit 1930. Daarin staat hoe Wilhelmina Drucker en andere vrouwen streden voor gelijke rechten.',
    klaar: 'Goed gedaan, krantenlezer!',
    vragen: [
      {
        img: 'l2-was', bijschrift: 'Een vrouw doet de was. Het huishouden was vooral een taak van vrouwen.',
        passage: 'Rond 1850 vonden veel mensen dat een vrouw vooral thuis hoorde te zijn. Zij moest voor het huishouden, haar man en de kinderen zorgen. Meisjes hoefden niet veel te leren, omdat zij later toch zouden trouwen. Sommige mannen zeiden zelfs dat vrouwen minder slim waren dan mannen. Daarom zouden vrouwen ook minder rechten nodig hebben.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom meisjes niet veel hoefden te leren.',
          antwoord: 'omdat zij later toch zouden trouwen.', kern: ['later', 'trouwen'],
          feedback: 'Het staat in de zin: "Meisjes hoefden niet veel te leren, omdat zij later toch zouden trouwen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'In de laatste zin staat "zouden": "Daarom zouden vrouwen ook minder rechten nodig hebben." Waarom schrijft de schrijver dat zo?',
          opties: ['Om te laten zien dat dit de mening van die mannen was, en niet de waarheid', 'Omdat het in de toekomst gaat gebeuren', 'Omdat de schrijver het er helemaal mee eens is', 'Omdat vrouwen later minder rechten kregen'], goed: 0,
          feedback: 'Met "zouden" laat de schrijver zien dat dit is wat die mannen beweerden. De schrijver van een maandblad vóór vrouwenrechten is het daar zeker niet mee eens.' },
      },
      {
        img: 'l2-drucker', bijschrift: 'Wilhelmina Drucker (1847-1925) streed voor gelijkheid tussen mannen en vrouwen.',
        passage: 'Wilhelmina Drucker was het daar niet mee eens. Zij wist zelf hoe oneerlijk vrouwen vaak behandeld werden. Haar moeder was niet getrouwd toen Wilhelmina werd geboren. Daardoor had Wilhelmina volgens de wet minder rechten dan kinderen van getrouwde ouders. Toen haar vader stierf, had zij bijna geen recht op zijn erfenis. Dat zat zo: Wilhelmina’s vader kreeg na Wilhelmina nog meer kinderen, met een vrouw met wie hij wél trouwde. Die halfbroers en halfzussen van Wilhelmina erfden wél, omdat hun moeder getrouwd was.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waardoor Wilhelmina volgens de wet minder rechten had.',
          antwoord: 'Haar moeder was niet getrouwd toen Wilhelmina werd geboren.', kern: ['moeder', 'niet', 'getrouwd'],
          feedback: 'Het staat in de zin: "Haar moeder was niet getrouwd toen Wilhelmina werd geboren." De zin erna begint met "Daardoor".' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom kreeg Wilhelmina bijna niets van de erfenis, en haar halfbroers en halfzussen wel?',
          opties: ['Omdat zij de oudste was', 'Omdat haar moeder niet met haar vader getrouwd was, en hun moeder wel', 'Omdat haar vader boos op haar was', 'Omdat meisjes in die tijd nooit mochten erven'], goed: 1,
          feedback: 'Het ging niet om jongen of meisje, maar om getrouwd of niet: de halfbroers en halfzussen erfden wél, "omdat hun moeder getrouwd was".' },
      },
      {
        passage: 'Wilhelmina vond dat onrechtvaardig. Ze begon een rechtszaak en schreef samen met haar zus het boek George David. Daarin liet ze zien hoe oneerlijk vrouwen en hun kinderen soms werden behandeld. Met haar boek, rechtszaak en scherpe woorden liet Wilhelmina duidelijk van zich horen. Ook andere vrouwen gingen steeds vaker protesteren. Ze wilden niet langer dat mannen alles voor hen bepaalden. De boodschap werd steeds sterker: een vrouw was geen bezit van een man, maar een vrij mens.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat deed Wilhelmina om te laten zien dat ze het oneerlijk vond?',
          opties: ['Ze verhuisde naar het buitenland', 'Ze begon een rechtszaak en schreef een boek', 'Ze ging in de Tweede Kamer werken', 'Ze schreef een brief aan de koning'], goed: 1,
          feedback: 'Ze begon een rechtszaak en schreef met haar zus het boek George David.' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent "scherpe woorden" in deze tekst?',
          opties: ['Woorden die pijn doen aan je oren', 'Duidelijke, felle woorden die mensen niet kunnen negeren', 'Heel nette en beleefde woorden', 'Woorden die met een mes in papier zijn gekrast'], goed: 1,
          feedback: 'Met "scherpe woorden liet Wilhelmina duidelijk van zich horen": ze zei fel en duidelijk wat er mis was.' },
      },
      {
        passage: 'Halverwege de 19e eeuw hadden meisjes veel minder kansen dan jongens. Veel meisjes mochten niet lang naar school. Studeren was voor vrouwen bijna onmogelijk. Ook goede banen waren vooral voor mannen. Vrouwen die wel werkten, deden vaak zwaar of slecht betaald werk. Ook kregen ze minder loon. Wilhelmina Drucker vond dat vrouwen zelf hun geld moesten kunnen verdienen. Dan waren ze minder afhankelijk van een man.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom Wilhelmina vond dat vrouwen zelf geld moesten kunnen verdienen.',
          antwoord: 'Dan waren ze minder afhankelijk van een man.', kern: ['minder', 'afhankelijk', 'man'],
          feedback: 'Het staat in de zin: "Dan waren ze minder afhankelijk van een man."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Welke uitspraak past het best bij wat Wilhelmina vond?',
          opties: ['Wie zijn eigen geld verdient, kan meer zelf beslissen', 'Vrouwen moeten zwaar werk doen om sterk te worden', 'Mannen horen meer loon te krijgen dan vrouwen', 'Meisjes hoeven niet lang naar school als ze later gaan werken'], goed: 0,
          feedback: 'Met eigen geld ben je "minder afhankelijk van een man". Dan kun je dus meer zelf beslissen.' },
      },
      {
        passage: 'Ze schreef artikelen in kranten en tijdschriften over werk, onderwijs en gelijke rechten voor vrouwen. Zo konden veel mensen haar ideeën lezen. In 1893 begon ze samen met Dora Haver het weekblad Evolutie. Dat tijdschrift was speciaal bedoeld om ideeën over vrouwenrechten te verspreiden. Stap voor stap veranderde er iets. Meer meisjes kregen onderwijs. Sommige vrouwen werden arts, lerares, schrijfster of winkelbediende. Toch bleef er veel ongelijkheid. Vrouwen kregen vaak minder loon en minder kansen.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarvoor het weekblad Evolutie bedoeld was.',
          antwoord: 'om ideeën over vrouwenrechten te verspreiden.', kern: ['ideeën', 'vrouwenrechten', 'verspreiden'],
          feedback: 'Het staat in de zin: "Dat tijdschrift was speciaal bedoeld om ideeën over vrouwenrechten te verspreiden."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'In de krant staat bij elk stuk een meter: "Hoeveel is er veranderd? weinig – veel". Waar zet jij de meter na deze tekst?',
          opties: ['Helemaal bij "weinig": er veranderde niets', 'Ergens in het midden: er veranderde iets, maar er bleef ook veel ongelijk', 'Helemaal bij "veel": vrouwen en mannen waren gelijk', 'Dat kun je niet zeggen, want de tekst gaat alleen over tijdschriften'], goed: 1,
          feedback: '"Stap voor stap veranderde er iets": meer meisjes kregen onderwijs. "Toch bleef er veel ongelijkheid." Dus ergens in het midden.' },
      },
      {
        passage: 'Lange tijd mochten vrouwen niet stemmen. Mannen in de politiek beslisten over wetten, onderwijs, werk en gezin. Die beslissingen golden ook voor vrouwen, maar vrouwen mochten er niet over meepraten of meebeslissen. Veel politici vonden dat lange tijd normaal. Vaak luisterden zij niet naar vrouwen die meer rechten wilden.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom vonden vrouwen het oneerlijk dat ze niet mochten stemmen?',
          opties: ['Omdat stemmen leuk is', 'Omdat de wetten ook voor hen golden, maar ze er niet over mochten meebeslissen', 'Omdat mannen niet goed konden stemmen', 'Omdat vrouwen meer belasting betaalden dan mannen'], goed: 1,
          feedback: '"Die beslissingen golden ook voor vrouwen, maar vrouwen mochten er niet over meepraten of meebeslissen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Welk woord past het best bij hoe veel politici zich gedroegen?',
          opties: ['Behulpzaam', 'Onverschillig', 'Nieuwsgierig', 'Bang'], goed: 1,
          feedback: 'Ze vonden het "normaal" en "luisterden niet" naar vrouwen. Het kon hun niet zoveel schelen: onverschillig.' },
      },
      {
        img: 'l2-congres', bijschrift: 'Wilhelmina Drucker (links op de stoel) op een congres voor vrouwenkiesrecht in 1911. In het midden zit Aletta Jacobs.',
        passage: 'Wilhelmina Drucker vond dat onrechtvaardig. Zij hield toespraken voor grote groepen mensen en werkte samen met andere vrouwen. In 1889 hielp zij de Vrije Vrouwenvereeniging oprichten, die streed voor gelijke rechten voor vrouwen. In 1894 richtte zij samen met onder anderen Aletta Jacobs de Vereeniging voor Vrouwenkiesrecht op. Die vereniging streed voor één duidelijk doel: vrouwen moesten kiesrecht krijgen.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst het doel van de Vereeniging voor Vrouwenkiesrecht.',
          antwoord: 'vrouwen moesten kiesrecht krijgen.', kern: ['vrouwen', 'kiesrecht'],
          feedback: 'Het staat na de dubbele punt: "vrouwen moesten kiesrecht krijgen."' },
        g8: { type: 'drag', vraag: 'Bij welke vereniging hoort het? Sleep het naar de goede vereniging.',
          cats: ['Vrije Vrouwenvereeniging', 'Vereeniging voor Vrouwenkiesrecht'],
          items: [['Opgericht in 1889', 'Vrije Vrouwenvereeniging'], ['Opgericht in 1894', 'Vereeniging voor Vrouwenkiesrecht'], ['Streed voor gelijke rechten voor vrouwen', 'Vrije Vrouwenvereeniging'], ['Had één doel: kiesrecht voor vrouwen', 'Vereeniging voor Vrouwenkiesrecht'], ['Aletta Jacobs hielp oprichten', 'Vereeniging voor Vrouwenkiesrecht']],
          feedback: '1889: Vrije Vrouwenvereeniging, voor gelijke rechten. 1894: Vereeniging voor Vrouwenkiesrecht, met Aletta Jacobs, voor één doel: kiesrecht.' },
      },
      {
        img: 'l2-straat', bijschrift: 'Vrouwen gingen de straat op om te strijden voor het stemrecht.',
        passage: 'In 1894 werd de Vereeniging voor Vrouwenkiesrecht opgericht. De strijd duurde lang. In 1917 mochten vrouwen gekozen worden in de Tweede Kamer. Zelf stemmen mochten zij toen nog niet. Dat veranderde in 1919: vrouwen kregen stemrecht. In 1922 mochten vrouwen voor het eerst stemmen bij de Tweede Kamerverkiezingen. Daarmee was niet alle ongelijkheid verdwenen, maar vrouwen mochten eindelijk meebeslissen over hun land.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat mochten vrouwen in 1917 nog níet?',
          opties: ['Gekozen worden in de Tweede Kamer', 'Zelf stemmen', 'Een vereniging oprichten', 'Toespraken houden'], goed: 1,
          feedback: '"In 1917 mochten vrouwen gekozen worden in de Tweede Kamer. Zelf stemmen mochten zij toen nog niet."' },
        g8: { type: 'order', vraag: 'Zet de stappen in de strijd voor vrouwenkiesrecht op volgorde.',
          items: ['De Vereeniging voor Vrouwenkiesrecht wordt opgericht', 'Vrouwen mogen gekozen worden in de Tweede Kamer', 'Vrouwen krijgen stemrecht', 'Vrouwen stemmen voor het eerst bij de Tweede Kamerverkiezingen'],
          feedback: '1894 de vereniging → 1917 gekozen worden → 1919 stemrecht → 1922 voor het eerst stemmen.' },
      },
      {
        img: 'l2-symbool', bijschrift: 'Het symbool van de strijd voor vrouwenrechten.',
        passage: 'Dit is het symbool van de strijd voor vrouwenrechten. De cirkel met het kruisje betekent vrouw. De gebalde vuist staat voor strijd. Samen betekent het: vrouwen die strijden voor gelijke rechten. Het symbool staat in het maandblad Voorwaarts!, een blad voor en door vrouwen.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent het hele symbool samen?',
          opties: ['Vrouwen zijn sterker dan mannen', 'Vrouwen die strijden voor gelijke rechten', 'Vrouwen die graag sporten', 'Vrouwen die boos zijn op de koning'], goed: 1,
          feedback: 'De cirkel met het kruisje is "vrouw" en de vuist is "strijd". Samen: vrouwen die strijden voor gelijke rechten.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Waarom past dit symbool goed bij een maandblad met de naam Voorwaarts!?',
          opties: ['Omdat het blad over sport en vechten gaat', 'Omdat het blad, net als het symbool, oproept om door te gaan met de strijd voor vrouwenrechten', 'Omdat het blad door mannen werd gemaakt', 'Omdat het symbool het logo van de Tweede Kamer is'], goed: 1,
          feedback: '"Voorwaarts!" betekent: vooruit, ga door. Dat past bij een vuist die staat voor strijd.' },
      },
      {
        passage: 'VOORWAARTS! Maandblad voor en door vrouwen. Waar strijden wij voor? Juist, voor meer rechten voor de vrouw! Wat daarvan terecht is gekomen in de afgelopen jaren, leest u in dit maandblad. 1e jaargang, november 1930, nummer 11. In dit nummer: een groot stuk over Wilhelmina Drucker (1847-1925).',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarover lees je in dit maandblad?',
          opties: ['Over het nieuws van de koning', 'Over wat er de afgelopen jaren is bereikt in de strijd voor vrouwenrechten', 'Over de nieuwste mode uit Parijs', 'Over hoe je het huishouden goed doet'], goed: 1,
          feedback: '"Wat daarvan terecht is gekomen in de afgelopen jaren, leest u in dit maandblad." Met "daarvan" bedoelen ze de strijd voor meer rechten.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Het maandblad is van november 1930. Wat betekent dat voor het stuk over Wilhelmina Drucker?',
          opties: ['Zij heeft het stuk zelf geschreven', 'Het is een terugblik: er wordt verteld wat zij in haar leven heeft gedaan', 'Het is verzonnen, want zij leefde toen niet meer', 'Het gaat over haar plannen voor de toekomst'], goed: 1,
          feedback: 'Wilhelmina Drucker overleed in 1925, vijf jaar vóór dit nummer. Het blad kijkt dus terug op wat zij heeft gedaan.' },
      },
    ],
  },
  {
    nr: 3, titel: 'Ons verleden', emoji: '🧳', cover: 'l3-familie',
    intro: 'Maartje en Peggy hebben een koffer vol voorwerpen uit het verleden. Van wie is elk voorwerp? En welk verhaal vertelt het? Het gaat over de slavernij in Suriname.',
    klaar: 'Goed gedaan, verhalenspeurder!',
    vragen: [
      {
        passage: 'Maartje en Peggy maakten samen de podcast De plantage van onze voorouders. Ze hebben een koffer vol bijzondere voorwerpen uit het verleden verzameld. De bet-betovergrootmoeder van Maartje bezat een deel van plantage Tout Lui Faut in Suriname. De voorouders van Peggy waren tot slaaf gemaakt en moesten op die plantage werken.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat hebben de families van Maartje en Peggy met elkaar te maken?',
          opties: ['Ze waren vroeger buren in Nederland', 'Ze hadden te maken met dezelfde plantage: de een als eigenaar, de ander als tot slaaf gemaakten', 'Ze werkten allebei als eigenaar op de plantage', 'Ze maakten vroeger ook al samen een podcast'], goed: 1,
          feedback: 'De bet-betovergrootmoeder van Maartje bezat een deel van de plantage. De voorouders van Peggy moesten er werken.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Waarom is het bijzonder dat juist Maartje en Peggy samen een podcast maken?',
          opties: ['Omdat ze allebei uit Suriname komen', 'Omdat hun families vroeger op dezelfde plantage tegenover elkaar stonden, en zij nu samen het verhaal vertellen', 'Omdat ze allebei familie hebben die rijk was', 'Omdat podcasts in die tijd nog niet bestonden'], goed: 1,
          feedback: 'Hun voorouders stonden tegenover elkaar: eigenaar en tot slaaf gemaakten. Nu zoeken Maartje en Peggy samen uit wat er gebeurd is.' },
      },
      {
        img: 'l3-document', bijschrift: 'Document: vergoeding voor plantage-eigenaren',
        passage: 'In 1863 werd de slavernij in Suriname afgeschaft. Vanaf dat moment werden de mensen die tot slaaf waren gemaakt vrijgemaakten genoemd. Ze konden nog niet meteen hun eigen keuzes maken, maar moesten nog tien jaar verplicht blijven werken, de meesten op de plantages. De (plantage-)eigenaren kregen geld van de overheid. De vrijgemaakten kregen niets. In dit document staat hoeveel geld mijn bet-betovergrootmoeder kreeg toen de slavernij werd afgeschaft.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst hoe lang de vrijgemaakten nog verplicht moesten werken.',
          antwoord: 'nog tien jaar verplicht blijven werken,', kern: ['tien', 'jaar', 'verplicht'],
          feedback: 'Het staat in de zin: "... maar moesten nog tien jaar verplicht blijven werken, de meesten op de plantages."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Van wie uit de koffer is dit document, denk je?',
          opties: ['Van Peggy, want haar voorouders werden vrijgemaakt', 'Van Maartje, want haar bet-betovergrootmoeder was eigenaar en kreeg dit geld', 'Van allebei, want hun families kregen allebei geld', 'Van de overheid, want die betaalde het geld'], goed: 1,
          feedback: 'In het document staat hoeveel geld "mijn bet-betovergrootmoeder" kreeg. Alleen de eigenaren kregen geld, en dat was de familie van Maartje.' },
      },
      {
        img: 'l3-oma', bijschrift: 'Antonia Elisabeth van Lynden-van der Heim (1804-1884)',
        passage: 'Op deze foto zie je Antonia Elisabeth van Lynden-van der Heim (1804-1884), mijn bet-betovergrootmoeder. Zij was tot 1863 mede-eigenaar van de Surinaamse suikerplantage Tout Lui Faut.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst van welke plantage zij mede-eigenaar was.',
          antwoord: 'mede-eigenaar van de Surinaamse suikerplantage Tout Lui Faut.', kern: ['suikerplantage', 'Tout', 'Faut'],
          feedback: 'Het staat aan het eind: "mede-eigenaar van de Surinaamse suikerplantage Tout Lui Faut."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Hoe oud was Antonia Elisabeth toen de slavernij in Suriname werd afgeschaft?',
          opties: ['49 jaar', '59 jaar', '63 jaar', '80 jaar'], goed: 1,
          feedback: 'Ze werd geboren in 1804. De slavernij werd afgeschaft in 1863 (tot dan was ze mede-eigenaar). 1863 − 1804 = 59.' },
      },
      {
        img: 'l3-kaart', bijschrift: 'Kaart van plantage Tout Lui Faut',
        passage: 'Hier zie je een deel van de landkaart van de plantage Tout Lui Faut. De kaart is gemaakt door de Nederlandse beheerder van de plantage. Mijn bet-betovergrootmoeder bezat een deel van deze plantage. De voorouders van Peggy moesten hier werken.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wie vertelt over deze kaart: Maartje of Peggy?',
          opties: ['Peggy, want haar voorouders werkten er', 'Maartje, want ze schrijft "mijn bet-betovergrootmoeder bezat" en "de voorouders van Peggy"', 'Allebei tegelijk', 'De beheerder van de plantage'], goed: 1,
          feedback: 'De verteller schrijft over "de voorouders van Peggy". Dan is de verteller zelf dus niet Peggy, maar Maartje.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'De kaart is gemaakt door de Nederlandse beheerder. Wat kun je daarom níet van deze kaart te weten komen?',
          opties: ['Waar de akkers en gebouwen lagen', 'Hoe groot de plantage was', 'Hoe de tot slaaf gemaakten zelf het leven op de plantage beleefden', 'Waar de plantage aan de rivier lag'], goed: 2,
          feedback: 'Een kaart van de beheerder laat zien hoe de plantage eruitzag. Hoe de mensen die er moesten werken het beleefden, staat er niet op.' },
      },
      {
        img: 'l3-familie', bijschrift: 'Familiefoto',
        passage: 'Op deze foto zie je familie van mij. Tijdens het maken van de podcast De plantage van onze voorouders zocht ik uit wie mijn voorouders waren en hoe zij leefden. Ik ontdekte dat een deel van mijn familie op een andere plantage leefde: de koffieplantage Dordrecht, vlak bij Paramaribo in Suriname.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat de verteller ontdekte.',
          antwoord: 'Ik ontdekte dat een deel van mijn familie op een andere plantage leefde: de koffieplantage Dordrecht, vlak bij Paramaribo in Suriname.', kern: ['andere', 'plantage', 'Dordrecht'],
          feedback: 'Het staat in de laatste zin, die begint met "Ik ontdekte".' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Van wie is deze familiefoto, denk je? En waarom?',
          opties: ['Van Maartje, want haar familie had plantages', 'Van Peggy, want een deel van haar familie leefde en werkte op een plantage', 'Van Maartje, want de foto is oud', 'Dat kun je niet weten, want er staat geen naam bij'], goed: 1,
          feedback: 'De verteller zocht uit hoe haar voorouders "leefden" en ontdekte dat familie op een andere plantage leefde. Dat past bij Peggy, wier voorouders op plantages moesten werken.' },
      },
      {
        img: 'l3-verkooplijst', bijschrift: 'Verkooplijst van een scheepsverkoop uit 1768',
        passage: 'Dit is een lijst van een scheepsverkoop uit 1768. Hierop staan mensen, waarschijnlijk ook mijn voorouders, niet bij hun naam, maar met een kwetsend woord en een prijs erachter. Zo werden tot slaaf gemaakte mensen toen behandeld: niet als mens, maar als koopwaar. Ik vind het nog steeds moeilijk om dit te lezen.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Hoe staan de mensen op de verkooplijst?',
          opties: ['Met hun naam en hun leeftijd', 'Niet bij hun naam, maar met een kwetsend woord en een prijs', 'Met hun beroep en waar ze woonden', 'Met een foto en een nummer'], goed: 1,
          feedback: '"... niet bij hun naam, maar met een kwetsend woord en een prijs erachter."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'De verteller schrijft: "Ik vind het nog steeds moeilijk om dit te lezen." Waarom?',
          opties: ['Omdat het handschrift zo slecht te lezen is', 'Omdat waarschijnlijk haar eigen voorouders erop staan, behandeld als koopwaar', 'Omdat de lijst in een andere taal is geschreven', 'Omdat ze niet weet wat de prijzen betekenen'], goed: 1,
          feedback: 'Op de lijst staan "waarschijnlijk ook mijn voorouders", en zij werden behandeld "niet als mens, maar als koopwaar". Dat doet pijn om te lezen.' },
      },
      {
        img: 'l3-voetring', bijschrift: 'Een ijzeren voetring',
        passage: 'Dit is een ijzeren voetring. De ring werd om de voeten van tot slaaf gemaakten gedaan, zodat ze niet konden weglopen. Of ze kregen hem om als straf. Waarschijnlijk waren ook mijn voorouders die op de plantage werkten met zo’n ring vastgeketend.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarvoor de voetring werd gebruikt.',
          antwoord: 'zodat ze niet konden weglopen. Of ze kregen hem om als straf.', kern: ['weglopen', 'straf'],
          feedback: 'Er staan twee redenen: "zodat ze niet konden weglopen" en "Of ze kregen hem om als straf."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'De verteller schrijft "waarschijnlijk" waren ook haar voorouders vastgeketend. Waarom schrijft ze "waarschijnlijk"?',
          opties: ['Omdat ze het niet zeker weet: het is niet over haar eigen voorouders opgeschreven', 'Omdat ze denkt dat het niet waar is', 'Omdat ze de voetring zelf heeft gemaakt', 'Omdat alleen eigenaren een voetring droegen'], goed: 0,
          feedback: 'Ze weet dat zulke ringen werden gebruikt op plantages, maar niet zeker of háár voorouders er een droegen. Daarom: waarschijnlijk.' },
      },
      {
        img: 'l3-tekening', bijschrift: 'Tekening van Jan van Borssele van der Hooghe (1707-1764)',
        passage: 'En kijk, dit is een oude tekening van Jan van Borssele van der Hooghe (1707-1764). Het hangt normaal gesproken bij ons bovenaan de trap. Hij behoorde tot een adellijke familie in Zeeland, was directeur van de VOC en kende misschien mijn voorouders wel. Hij was kasteelheer van het landgoed Ter Hooge dat mijn familie honderd jaar later kocht.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat heeft Jan van Borssele van der Hooghe met de familie van de verteller te maken?',
          opties: ['Hij was de opa van de verteller', 'De familie van de verteller kocht later zijn landgoed Ter Hooge', 'Hij werkte op de plantage van de familie', 'Hij maakte de tekening van de verteller'], goed: 1,
          feedback: '"Hij was kasteelheer van het landgoed Ter Hooge dat mijn familie honderd jaar later kocht."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Van wie is deze tekening, Maartje of Peggy? Welk stukje tekst helpt je het meest?',
          opties: ['Van Peggy: "kende misschien mijn voorouders wel"', 'Van Maartje: haar familie kocht het landgoed van deze adellijke kasteelheer', 'Van Peggy: de tekening hangt bovenaan de trap', 'Van Maartje: Jan was directeur van de VOC'], goed: 1,
          feedback: 'Dat de familie later zijn kasteel kocht, past bij Maartje, uit een rijke familie van plantage-eigenaren. Dat Jan VOC-directeur was, zegt niets over van wie de tekening is.' },
      },
      {
        img: 'l3-plengoffer', bijschrift: 'Een plengoffer met een kalebas',
        passage: 'Dit is een kalebas, een schaal voor een plengoffer. Voor veel mensen in Suriname is het belangrijk om hun voorouders te eren. Je schenkt hiervoor wat water of een andere drank in de kalebas, giet dit op de grond en denkt aan je voorouders of spreekt een groet of dankwoord uit. Toen ik in Suriname was, bracht ik ook een plengoffer, aan mijn voorouders die op de plantage moesten werken. Dat was voor mij een emotioneel moment van stilstaan, herinneren en respect tonen.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst hoe je een plengoffer brengt.',
          antwoord: 'Je schenkt hiervoor wat water of een andere drank in de kalebas, giet dit op de grond en denkt aan je voorouders of spreekt een groet of dankwoord uit.', kern: ['schenkt', 'giet', 'grond'],
          feedback: 'Het staat in de zin die begint met "Je schenkt hiervoor ...".' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekende het plengoffer voor de verteller?',
          opties: ['Een feestje met familie en vrienden', 'Een emotioneel moment om haar voorouders te herinneren en respect te tonen', 'Een manier om de plantage-eigenaren te bedanken', 'Een gewoonte om de grond nat te houden'], goed: 1,
          feedback: '"Dat was voor mij een emotioneel moment van stilstaan, herinneren en respect tonen."' },
      },
      {
        passage: 'In de koffer zitten: een document over geld voor plantage-eigenaren, een kaart van plantage Tout Lui Faut, een foto van een bet-betovergrootmoeder die mede-eigenaar was, een verkooplijst van een scheepsverkoop uit 1768, een ijzeren voetring, een kalebas voor een plengoffer en een tekening van een kasteelheer uit Zeeland.',
        g7: { type: 'drag', vraag: 'Van wie is elk voorwerp uit de koffer? Sleep het naar Maartje of Peggy.',
          cats: ['Maartje', 'Peggy'],
          items: [['Document over geld voor eigenaren', 'Maartje'], ['Kaart van de plantage', 'Maartje'], ['Verkooplijst uit 1768', 'Peggy'], ['IJzeren voetring', 'Peggy'], ['Kalebas voor een plengoffer', 'Peggy']],
          feedback: 'Maartje: de spullen van de eigenaren (document, kaart). Peggy: de spullen over haar tot slaaf gemaakte voorouders (verkooplijst, voetring, plengoffer).' },
        g8: { type: 'drag', vraag: 'Van wie is elk voorwerp uit de koffer? Sleep het naar Maartje of Peggy.',
          cats: ['Maartje', 'Peggy'],
          items: [['Document over geld voor eigenaren', 'Maartje'], ['Kaart van de plantage', 'Maartje'], ['Foto van de bet-betovergrootmoeder', 'Maartje'], ['Tekening van de kasteelheer', 'Maartje'], ['Verkooplijst uit 1768', 'Peggy'], ['IJzeren voetring', 'Peggy'], ['Kalebas voor een plengoffer', 'Peggy']],
          feedback: 'Maartje: document, kaart, foto en tekening (haar familie was eigenaar en kocht later Ter Hooge). Peggy: verkooplijst, voetring en plengoffer.' },
      },
    ],
  },
  {
    nr: 4, titel: 'Kom in verzet', emoji: '✒️', cover: 'l4-judith',
    intro: 'Je leest een interview met Judith de Kom over haar vader Anton de Kom: schrijver, vrijheidsstrijder en verzetsheld.',
    klaar: 'Goed gedaan, interviewlezer!',
    vragen: [
      {
        img: 'l4-judith', bijschrift: 'Judith de Kom (1931-2024)',
        passage: 'Judith de Kom was dertien jaar oud toen haar vader Anton de Kom verdween. Pas veel later begreep ze hoe bijzonder hij was geweest. Hij kwam op voor mensen die slecht werden behandeld. Maar Judith kende hem niet als held uit een boek. Voor haar was hij vooral haar vader: lief, streng, slim en dapper.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst hoe Judith haar vader beschrijft.',
          antwoord: 'lief, streng, slim en dapper.', kern: ['lief', 'streng', 'slim', 'dapper'],
          feedback: 'Het staat na de dubbele punt: "lief, streng, slim en dapper."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat bedoelt de schrijver met: "Judith kende hem niet als held uit een boek"?',
          opties: ['Judith had nooit een boek over haar vader gelezen', 'Voor Judith was hij in de eerste plaats gewoon haar vader, niet een beroemd persoon', 'Anton de Kom was helemaal geen held', 'Judith vond boeken over helden saai'], goed: 1,
          feedback: 'Anderen kennen hem als held. Judith kende hem van thuis: "Voor haar was hij vooral haar vader."' },
      },
      {
        passage: 'Uw vader werd geboren in Suriname. Wat betekende dat land voor hem? In Suriname lagen mijn vaders wortels, daar kwam hij vandaan. Hij kende de verhalen, de taal en de mensen en hij hield van dat land. Maar hij zag ook dat veel Surinamers niet eerlijk werden behandeld. Suriname was toen een kolonie van Nederland. Nederlandse bestuurders hadden veel macht, terwijl gewone Surinamers weinig te zeggen hadden.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent "In Suriname lagen mijn vaders wortels"?',
          opties: ['Hij had in Suriname een moestuin', 'Hij kwam uit Suriname en voelde zich er thuis', 'Hij werkte in Suriname als boer', 'Hij wilde in Suriname bomen planten'], goed: 1,
          feedback: 'Judith legt het zelf uit: "daar kwam hij vandaan". Je wortels zijn de plek waar je vandaan komt.' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Wat voor tekst is dit, en hoe zie je dat?',
          opties: ['Een dagboek: er staan datums boven', 'Een interview: er wordt een vraag gesteld en Judith geeft antwoord', 'Een gedicht: de zinnen rijmen', 'Een reclame: er wordt iets verkocht'], goed: 1,
          feedback: 'De tekst begint met een vraag ("Wat betekende dat land voor hem?") en daarna antwoordt Judith ("mijn vaders wortels").' },
      },
      {
        passage: 'Hij verzamelde de verhalen van Surinamers over Suriname en schreef ze op. Hij vond dat zij hun eigen geschiedenis moesten kennen en doorvertellen, niet alleen de geschiedenis zoals Nederlanders die vertelden. Maar hij besloot in Nederland te gaan wonen … Klopt! In Suriname kreeg hij niet de kansen die hij verdiende. Mijn vader kon goed schrijven en rekenen, maar de betere banen waren vaak voor witte Nederlanders. In Nederland hoopte hij werk te vinden en een toekomst op te bouwen.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom Anton naar Nederland ging.',
          antwoord: 'In Nederland hoopte hij werk te vinden en een toekomst op te bouwen.', kern: ['werk', 'toekomst'],
          feedback: 'Het staat in de laatste zin: "In Nederland hoopte hij werk te vinden en een toekomst op te bouwen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom vond Anton het belangrijk dat Surinamers hun eigen verhalen opschreven?',
          opties: ['Omdat hij zelf graag verhalen las', 'Omdat mensen anders alleen de geschiedenis kenden zoals Nederlanders die vertelden', 'Omdat de Nederlanders daarom vroegen', 'Omdat hij er een boek mee wilde verkopen'], goed: 1,
          feedback: 'Ze moesten hun eigen geschiedenis kennen, "niet alleen de geschiedenis zoals Nederlanders die vertelden".' },
      },
      {
        img: 'l4-gezin', bijschrift: 'Nellie, Anton en hun vier kinderen. Judith wordt vastgehouden door haar moeder.',
        passage: 'En toen ontmoette hij daar mijn moeder Nellie. Dat ze een relatie kregen, was heel bijzonder, want zij was wit en hij was zwart. In die tijd vonden veel mensen dat een witte vrouw niet met een zwarte man mocht trouwen. Gelukkig was mijn oma, de moeder van mijn moeder, dol op mijn vader. Maar er waren ook veel mensen die racistische opmerkingen maakten.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom was de relatie van Anton en Nellie in die tijd bijzonder?',
          opties: ['Omdat ze elkaar in Suriname ontmoetten', 'Omdat zij wit was en hij zwart, en veel mensen vonden dat dat niet mocht', 'Omdat ze allebei schrijver waren', 'Omdat haar moeder het verbood'], goed: 1,
          feedback: '"... want zij was wit en hij was zwart. In die tijd vonden veel mensen dat een witte vrouw niet met een zwarte man mocht trouwen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Judith zegt: "Gelukkig was mijn oma dol op mijn vader." Waarom gebruikt ze het woord "gelukkig"?',
          opties: ['Omdat haar oma heel rijk was', 'Omdat veel andere mensen wél racistisch deden, en het fijn was dat haar oma hem steunde', 'Omdat haar oma ook uit Suriname kwam', 'Omdat haar oma de bruiloft betaalde'], goed: 1,
          feedback: 'Er waren "veel mensen die racistische opmerkingen maakten". Daarom was het een geluk dat de familie van Nellie wél achter Anton stond.' },
      },
      {
        passage: 'Wat voor vader was Anton de Kom? Hij was lief, maar hij kon ook streng zijn. Hij wilde dat we goed leerden, veel lazen en nieuwsgierig bleven naar de wereld om ons heen. Kennis vond hij heel belangrijk. ‘Als je veel weet, begrijp je beter wat er in de wereld gebeurt. Dan kun je ook beter voor jezelf en voor anderen opkomen’, zei hij. Ik zie hem nog zitten, in zijn leunstoel met een stapel woordenboeken naast zich. Hij schreef met een stompje potlood op alles wat hij maar aan papier kon vinden. Voor een notitieboekje had hij geen geld.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat je volgens Anton beter kunt als je veel weet.',
          antwoord: 'Dan kun je ook beter voor jezelf en voor anderen opkomen’,', kern: ['jezelf', 'anderen', 'opkomen'],
          feedback: 'Anton zei: "Als je veel weet, begrijp je beter wat er in de wereld gebeurt. Dan kun je ook beter voor jezelf en voor anderen opkomen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat laat het "stompje potlood" zien over Anton?',
          opties: ['Dat hij slordig was met zijn spullen', 'Dat hij weinig geld had, maar toch heel graag wilde schrijven', 'Dat hij liever tekende dan schreef', 'Dat hij geen woordenboeken had'], goed: 1,
          feedback: 'Hij schreef op "alles wat hij maar aan papier kon vinden", want "voor een notitieboekje had hij geen geld". Schrijven was hem heel veel waard.' },
      },
      {
        passage: 'Toen u één jaar oud was, verhuisde jullie gezin naar Suriname. Ja, mijn vader besloot om naar Suriname te gaan, omdat zijn moeder ernstig ziek was. In Suriname ontdekte hij hoe Surinaamse arbeiders werden uitgebuit: ze werkten hard, verdienden weinig en zaten vaak vast aan strenge contracten. Wie protesteerde, kon boetes of straf krijgen. Daarom begon mijn vader een adviesbureau. Arbeiders konden daar hun verhaal doen. Hij schreef hun klachten op en wees hen op hun rechten. Zo kregen mensen die nooit werden gehoord ineens wél een stem.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat Anton deed op zijn adviesbureau.',
          antwoord: 'Hij schreef hun klachten op en wees hen op hun rechten.', kern: ['klachten', 'rechten'],
          feedback: 'Het staat in de zin: "Hij schreef hun klachten op en wees hen op hun rechten."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent "uitgebuit" in deze tekst?',
          opties: ['Dat ze buiten moesten werken', 'Dat ze hard moesten werken voor weinig geld en zich niet konden verzetten', 'Dat ze een vrije dag kregen', 'Dat ze naar een ander land werden gestuurd'], goed: 1,
          feedback: 'Na de dubbele punt wordt het uitgelegd: hard werken, weinig verdienen, vastzitten aan strenge contracten, en straf als je protesteert.' },
      },
      {
        passage: 'Maar al snel moesten jullie terugkeren naar Nederland. Waarom? De Nederlandse bestuurders in Suriname werden bang voor zijn invloed. Steeds meer arbeiders, arme mensen en andere Surinamers met klachten kwamen naar hem toe. De bestuurders zagen hem als een oproerkraaier: iemand die voor onrust zorgde. Maar mijn vader wilde geen herrie maken om de herrie. Hij wilde eerlijkheid. Toch werd hij gevangengezet. Daarna werd hij naar Nederland teruggestuurd.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom werd Anton gevangengezet?',
          opties: ['Omdat hij iets had gestolen', 'Omdat de bestuurders bang waren voor zijn invloed, nu steeds meer mensen naar hem toe kwamen', 'Omdat hij geen werk had', 'Omdat hij terug wilde naar Nederland'], goed: 1,
          feedback: '"De Nederlandse bestuurders in Suriname werden bang voor zijn invloed. Steeds meer ... kwamen naar hem toe."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'De bestuurders noemden Anton een "oproerkraaier". Hoe ziet Judith dat?',
          opties: ['Ze is het met de bestuurders eens', 'Volgens haar wilde hij geen onrust, maar eerlijkheid', 'Ze vindt dat hij nog meer herrie had moeten maken', 'Ze weet niet wat hij wilde'], goed: 1,
          feedback: 'Judith zegt: "Maar mijn vader wilde geen herrie maken om de herrie. Hij wilde eerlijkheid." Het woord "maar" laat zien dat zij het anders ziet.' },
      },
      {
        img: 'l4-boek', bijschrift: 'In 1934 verscheen het boek Wij slaven van Suriname.',
        passage: 'Een jaar later verscheen zijn boek Wij slaven van Suriname. Waar ging dat boek over? Mijn vader schreef over slavernij, racisme en de manier waarop Surinamers door Nederlanders werden behandeld. Vaak werd die geschiedenis verteld door mensen met macht. Mijn vader draaide dat om: hij schreef vanuit de Surinamers zelf. Hij wilde dat lezers begrepen: dit is onrecht en daar mag je tegen opstaan.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarover Anton schreef in zijn boek.',
          antwoord: 'Mijn vader schreef over slavernij, racisme en de manier waarop Surinamers door Nederlanders werden behandeld.', kern: ['slavernij', 'racisme', 'behandeld'],
          feedback: 'Het staat in de zin: "Mijn vader schreef over slavernij, racisme en de manier waarop Surinamers door Nederlanders werden behandeld."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: '"Mijn vader draaide dat om." Wat draaide hij om?',
          opties: ['Hij schreef het boek van achteren naar voren', 'Hij vertelde de geschiedenis vanuit de Surinamers zelf, in plaats van vanuit de mensen met macht', 'Hij ging van Nederland terug naar Suriname', 'Hij maakte van slechte mensen goede mensen'], goed: 1,
          feedback: '"Dat" is: geschiedenis verteld door mensen met macht. Anton deed het andersom: "hij schreef vanuit de Surinamers zelf".' },
      },
      {
        passage: 'Judith de Kom werd in 1931 geboren. Toen de Tweede Wereldoorlog in 1940 uitbrak, sloot haar vader zich aan bij het verzet. Hij schreef teksten tegen de Duitse bezetters en werkte mee aan geheime kranten. Wij thuis wisten daar niets van. Dat was veiliger, voor hem én voor ons. Maar op 7 augustus 1944 werd hij opgepakt door de Duitse politie. Daarna hebben we nooit meer iets van hem gehoord. Pas jaren later hoorden we dat hij in verschillende Duitse concentratiekampen heeft gezeten. Toen ik 28 jaar was, ontdekte ik dat hij kort voor de bevrijding van Nederland was overleden aan tuberculose, een ernstige ziekte.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom wist het gezin niets van het verzetswerk van Anton?',
          opties: ['Omdat Anton het vergeten was te vertellen', 'Omdat het veiliger was, voor hem én voor het gezin', 'Omdat het gezin in Suriname woonde', 'Omdat Judith nog niet kon lezen'], goed: 1,
          feedback: '"Wij thuis wisten daar niets van. Dat was veiliger, voor hem én voor ons."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Judith was 28 toen ze ontdekte hoe haar vader was overleden. Hoeveel jaar na zijn arrestatie was dat ongeveer?',
          opties: ['1 jaar', '5 jaar', '15 jaar', '28 jaar'], goed: 2,
          feedback: 'Judith werd geboren in 1931, dus ze was 28 in 1959. Hij werd opgepakt in 1944. 1959 − 1944 = 15 jaar.' },
      },
      {
        img: 'l4-anton', bijschrift: 'Anton de Kom kwam op zijn 22e naar Nederland om te werken.',
        passage: 'In 1934 verscheen Wij slaven van Suriname, een jaar nadat Anton uit Suriname was teruggestuurd. Hij was daar maar kort geweest: in 1932 was hij met zijn gezin naar Suriname gegaan. Geboren was hij er in 1898. Toen hij 22 jaar was, kwam hij naar Nederland om te werken. Hij overleed in 1945, kort voor de bevrijding.',
        g7: { type: 'order', vraag: 'Zet deze gebeurtenissen uit het leven van Anton de Kom op volgorde.',
          items: ['Anton wordt geboren in Suriname', 'Anton komt naar Nederland om te werken', 'Anton wordt uit Suriname teruggestuurd', 'Anton overlijdt, kort voor de bevrijding'],
          feedback: '1898 geboren → 1920 naar Nederland → 1933 teruggestuurd → 1945 overleden.' },
        g8: { type: 'order', vraag: 'Zet deze gebeurtenissen op volgorde. Niet alle jaartallen staan erbij: reken ze uit!',
          items: ['Anton wordt geboren in Suriname', 'Anton komt naar Nederland om te werken', 'Anton gaat met zijn gezin naar Suriname', 'Anton wordt uit Suriname teruggestuurd', 'Het boek Wij slaven van Suriname verschijnt', 'Anton overlijdt, kort voor de bevrijding'],
          feedback: '1898 geboren → 1920 (22 jaar later) naar Nederland → 1932 naar Suriname → 1933 teruggestuurd (een jaar voor het boek) → 1934 het boek → 1945 overleden.' },
      },
    ],
  },
  {
    nr: 5, titel: 'Rebelse jongeren', emoji: '🎸', cover: 'l5-poster',
    intro: 'Je bekijkt een archief met bronnen uit de jaren 50: posters, krantenartikelen, reclames en brieven. Jongeren en hun ouders dachten in die tijd heel verschillend over muziek, kleding, school en geld.',
    klaar: 'Goed gedaan, bronnenspeurder!',
    vragen: [
      {
        img: 'l5-poster', bijschrift: 'Bron 1 – Reclameposter (1958)',
        passage: 'Bron 1 – Reclameposter (1958): aankondiging van The Tielman Brothers. Informatie over de bron: In de jaren 50 ontstaat een nieuwe jongerencultuur. Jongeren gaan naar dansavonden, ze dragen moderne kleding en ze luisteren naar nieuwe muziek uit Amerika, zoals rock-’n-roll. Voor jongeren hoort muziek bij vrijheid en het maken van eigen keuzes.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat muziek voor jongeren betekent.',
          antwoord: 'Voor jongeren hoort muziek bij vrijheid en het maken van eigen keuzes.', kern: ['vrijheid', 'eigen', 'keuzes'],
          feedback: 'Het staat in de laatste zin: "Voor jongeren hoort muziek bij vrijheid en het maken van eigen keuzes."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Op de poster staat: "De nieuwste muziek uit Amerika!" Waarom zet de maker dat erop?',
          opties: ['Om ouders gerust te stellen', 'Om jongeren te lokken: nieuw en Amerikaans klonk spannend en modern', 'Omdat de band uit Amerika kwam en geen Nederlands sprak', 'Om te waarschuwen voor wilde muziek'], goed: 1,
          feedback: 'Een reclameposter wil mensen laten komen. Jongeren vonden nieuwe muziek uit Amerika juist spannend.' },
      },
      {
        img: 'l5-krant', bijschrift: 'Bron 2 – Krantenartikel (1958)',
        passage: 'Bron 2 – Krantenartikel (1958): Ouders bezorgd over moderne dansavonden. Informatie over de bron: Veel ouders maken zich zorgen over jongeren. Zij vinden rock-’n-rollmuziek en moderne dansen te wild. Ouders zijn opgegroeid met rust, orde en gehoorzaamheid. Doe maar gewoon, denken zij. Zij vinden dat jongeren zich netjes moeten gedragen. De nieuwe jongerencultuur is voor hen een grote verandering. Sommige ouders zijn bang dat jongeren zich minder aan regels zullen houden.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom maken ouders zich zorgen over de dansavonden?',
          opties: ['Omdat de kaartjes te duur zijn', 'Omdat ze de muziek en de dansen te wild vinden en bang zijn dat jongeren zich minder aan regels houden', 'Omdat de dansavonden te laat beginnen', 'Omdat ze zelf ook willen dansen'], goed: 1,
          feedback: 'Ouders vinden de muziek en de dansen "te wild" en zijn bang "dat jongeren zich minder aan regels zullen houden".' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Bron 1 (de poster) en bron 2 (dit artikel) komen allebei uit 1958. Wat is het grootste verschil?',
          opties: ['Bron 1 is ouder dan bron 2', 'Bron 1 laat zien wat jongeren aantrekt, bron 2 laat zien waar ouders bang voor zijn', 'Bron 1 gaat over Amerika, bron 2 over Frankrijk', 'Er is geen verschil, ze zeggen hetzelfde'], goed: 1,
          feedback: 'Dezelfde muziek, twee kanten: voor jongeren betekent het vrijheid, ouders vinden het te wild.' },
      },
      {
        img: 'l5-brommer', bijschrift: 'Bron 3 – Tijdschriftadvertentie voor bromfietsen (ca. 1957)',
        passage: 'Bron 3 – Tijdschriftadvertentie (ca. 1957). Informatie over de bron: In de jaren 50 laten jongeren met hun uiterlijk zien wie ze zijn. Jongens dragen leren jacks en strakke broeken. Met Brylcreem, een haarcrème, wordt het haar strak in model gebracht, bijvoorbeeld in een vetkuif. Ook meisjes veranderen hun uiterlijk. Brommers geven jongeren meer vrijheid. Ze kunnen zo zelf op pad en vrienden opzoeken. Voor sommige jongens is een brommer ook stoer en belangrijk om indruk te maken. Volwassenen die zich eraan ergeren, noemen deze jongeren nozems.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom een brommer jongeren meer vrijheid geeft.',
          antwoord: 'Ze kunnen zo zelf op pad en vrienden opzoeken.', kern: ['zelf', 'pad', 'vrienden'],
          feedback: 'Het staat in de zin: "Ze kunnen zo zelf op pad en vrienden opzoeken."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent het woord "nozems" in deze tekst?',
          opties: ['Jongeren die een brommer verkopen', 'Een naam die volwassenen gaven aan jongeren met een eigen stijl die hen ergerden', 'Een merk haarcrème', 'Jongens die in een fabriek werken'], goed: 1,
          feedback: '"Volwassenen die zich eraan ergeren, noemen deze jongeren nozems." Het is dus geen vriendelijk woord.' },
      },
      {
        img: 'l5-brylcreem', bijschrift: 'Reclame voor Brylcreem, haarcrème voor een vetkuif',
        passage: 'Bron 4 – Krantenartikel (1959): overlast door nozems. Informatie over de bron: In de jaren 50 klagen veel volwassenen over nozems, jongeren uit die tijd die zich verzetten tegen hun ouders en een heel eigen kledingstijl hebben. Zij hangen rond op straat, maken herrie met hun brommers en gedragen zich brutaal. Vooral op pleinen, bij cafés en danszalen is er overlast. De politie grijpt regelmatig in. Volwassenen vinden het gedrag van nozems te vrij. Ze kennen geen grenzen, vinden zij.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waar er vooral overlast was.',
          antwoord: 'Vooral op pleinen, bij cafés en danszalen is er overlast.', kern: ['pleinen', 'cafés', 'danszalen'],
          feedback: 'Het staat in de zin: "Vooral op pleinen, bij cafés en danszalen is er overlast."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Welke zin is een mening en geen feit?',
          opties: ['De politie grijpt regelmatig in.', 'Ze kennen geen grenzen.', 'Vooral op pleinen, bij cafés en danszalen is er overlast.', 'Nozems hebben een heel eigen kledingstijl.'], goed: 1,
          feedback: '"Ze kennen geen grenzen" is wat volwassenen vínden. Daarom staat er in de tekst ook "vinden zij" achter.' },
      },
      {
        img: 'l5-doorleren', bijschrift: 'Bron 5 – Schoolfolder (ca. 1957)',
        passage: 'Bron 5 – Schoolfolder (ca. 1957): voorlichting over doorleren. Informatie over de bron: Vóór de jaren 50 gingen de meeste kinderen na de lagere school meteen aan het werk. Maar in de jaren 50 verandert dat. Er komen meer scholen bij, zoals de ambachtsschool (waar jongens een vak leren, bijvoorbeeld timmerman) en de huishoudschool (waar meisjes leren koken en naaien). Steeds meer jongeren willen doorleren, omdat ze hopen op een beter beroep dan hun ouders. Dat is nieuw: voor het eerst kiezen jongeren een andere weg dan hun ouders.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom steeds meer jongeren willen doorleren.',
          antwoord: 'omdat ze hopen op een beter beroep dan hun ouders.', kern: ['beter', 'beroep', 'ouders'],
          feedback: 'Het staat in de zin: "Steeds meer jongeren willen doorleren, omdat ze hopen op een beter beroep dan hun ouders."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat was er volgens de tekst echt nieuw in de jaren 50?',
          opties: ['Dat er scholen bestonden', 'Dat jongeren voor het eerst een andere weg kozen dan hun ouders', 'Dat meisjes leerden koken', 'Dat kinderen na de lagere school gingen werken'], goed: 1,
          feedback: '"Dat is nieuw: voor het eerst kiezen jongeren een andere weg dan hun ouders." Werken na de lagere school was juist het oude.' },
      },
      {
        img: 'l5-loonzakje', bijschrift: 'Bron 6 – Loonzakje (ca. 1955)',
        passage: 'Bron 6 – Loonzakje (ca. 1955). Informatie over de bron: Veel ouders van jongeren in de jaren 50 gingen zelf maar kort naar school. Doorleren was voor hen geen mogelijkheid. Na de lagere school gingen zij meteen aan het werk, bijvoorbeeld in een fabriek, winkel, kantoor of als hulp in de huishouding. Veel van dat werk was zwaar en het loon was laag. Sparen was daarom belangrijk. Ouders begrijpen niet waarom hun kinderen langer naar school willen. Een vak leer je toch op de werkvloer? En het gezin kan het geld goed gebruiken.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Waarom begrijpen ouders niet dat hun kinderen langer naar school willen?',
          opties: ['Omdat school toen heel duur was', 'Omdat zij vinden dat je een vak op de werkvloer leert, en het gezin het geld goed kan gebruiken', 'Omdat er geen scholen in de buurt waren', 'Omdat ze willen dat hun kinderen beroemd worden'], goed: 1,
          feedback: '"Een vak leer je toch op de werkvloer? En het gezin kan het geld goed gebruiken."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat vertelt dit loonzakje over het leven van de ouders toen zij jong waren?',
          opties: ['Dat ze al jong werkten, weinig verdienden en zuinig moesten zijn', 'Dat ze veel geld uitgaven aan kleding', 'Dat ze lang hebben doorgeleerd', 'Dat ze rijk werden in de fabriek'], goed: 0,
          feedback: 'Ze gingen meteen na de lagere school werken, het loon was laag en "sparen was daarom belangrijk".' },
      },
      {
        img: 'l5-bon', bijschrift: 'Bron 7 – Bonnetje van een kledingwinkel (1958)',
        passage: 'Bron 7 – Handgeschreven bon van een kledingwinkel (1958). Informatie over de bron: In de jaren 50 krijgen sommige jongeren meer geld te besteden. Ze kopen moderne kleding, grammofoonplaten (elpees) en kaartjes voor dansavonden. Nederland krijgt langzaam meer welvaart. Mensen kopen steeds meer spullen. Ook kopen zij vaker dingen voor plezier en vrije tijd. Dit heet een consumptiemaatschappij. Voor veel jongeren hoort geld uitgeven bij de nieuwe tijd.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat er gebeurt in een consumptiemaatschappij.',
          antwoord: 'Mensen kopen steeds meer spullen. Ook kopen zij vaker dingen voor plezier en vrije tijd.', kern: ['meer', 'spullen', 'plezier'],
          feedback: 'Vlak voor "Dit heet een consumptiemaatschappij" staat wat het is: "Mensen kopen steeds meer spullen. Ook kopen zij vaker dingen voor plezier en vrije tijd."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Wat kun je met deze bron, een bonnetje van een kledingwinkel, het best laten zien?',
          opties: ['Hoeveel loon een fabrieksarbeider kreeg', 'Dat jongeren in de jaren 50 geld uitgaven aan kleding', 'Dat ouders hun kinderen verboden om kleding te kopen', 'Hoe een dansavond verliep'], goed: 1,
          feedback: 'Een bon laat zien wat er gekocht is. Dat past bij jongeren die hun geld uitgaven aan moderne kleding.' },
      },
      {
        img: 'l5-brief', bijschrift: 'Bron 8 – Lezersbrief in een tijdschrift (1957)',
        passage: 'Bron 8 – Lezersbrief (1957). Geachte redactie, onze dochter is zeventien jaar en verdient sinds kort haar eigen loon. Tot onze zorg geeft zij bijna alles uit aan grammofoonplaten, lippenstift, nieuwe kousen en dansavonden. Mijn man en ik vinden dat een meisje moet leren zuinig te zijn. Een bezorgde moeder. Informatie over de bron: Ouders van jongeren in de jaren 50 zijn opgegroeid in een tijd van oorlog en schaarste. Zij weten hoe het is om weinig te hebben. Sparen en zuinig leven is voor hen vanzelfsprekend.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waaraan de dochter haar geld uitgeeft.',
          antwoord: 'grammofoonplaten, lippenstift, nieuwe kousen en dansavonden.', kern: ['grammofoonplaten', 'lippenstift', 'dansavonden'],
          feedback: 'Het staat in de zin: "... geeft zij bijna alles uit aan grammofoonplaten, lippenstift, nieuwe kousen en dansavonden."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom vindt deze moeder sparen zo belangrijk? Gebruik ook de informatie over de bron.',
          opties: ['Omdat haar dochter te weinig verdient', 'Omdat zij opgroeide in een tijd van oorlog en schaarste en weet hoe het is om weinig te hebben', 'Omdat lippenstift in die tijd verboden was', 'Omdat de redactie dat had gezegd'], goed: 1,
          feedback: 'De brief zelf zegt alleen dát ze sparen belangrijk vindt. De informatie over de bron legt uit waaróm: zij maakte oorlog en schaarste mee.' },
      },
      {
        passage: 'In het archief over de jaren 50 vind je stemmen van jongeren en van ouders. Jongeren willen dansen op rock-’n-roll, met hun brommer zelf op pad, doorleren voor een beter beroep en hun eigen loon uitgeven. Ouders zijn opgegroeid met rust, orde en zuinigheid. Zij vinden dat je een vak op de werkvloer leert, dat geld bedoeld is om te sparen en dat jongeren zich netjes moeten kleden.',
        g7: { type: 'drag', vraag: 'Wie denkt zo: jongeren of ouders in de jaren 50? Sleep het naar de goede kant.',
          cats: ['Jongeren', 'Ouders'],
          items: [['Dansen op rock-’n-roll', 'Jongeren'], ['Netjes gekleed gaan', 'Ouders'], ['Doorleren voor een beter beroep', 'Jongeren'], ['Sparen voor later', 'Ouders']],
          feedback: 'Jongeren: dansen en doorleren. Ouders: netjes gekleed gaan en sparen.' },
        g8: { type: 'drag', vraag: 'Wie denkt zo: jongeren of ouders in de jaren 50? Sleep het naar de goede kant.',
          cats: ['Jongeren', 'Ouders'],
          items: [['Dansen op rock-’n-roll', 'Jongeren'], ['Met de brommer zelf op pad', 'Jongeren'], ['Je eigen loon uitgeven', 'Jongeren'], ['Een vak leer je op de werkvloer', 'Ouders'], ['Geld is om te sparen', 'Ouders'], ['Rust, orde en gehoorzaamheid', 'Ouders']],
          feedback: 'Jongeren: dansen, brommer, eigen loon uitgeven. Ouders: vak op de werkvloer, sparen, rust en orde.' },
      },
      {
        passage: 'Onder elke bron in dit archief staat: "gereconstrueerde bron, gebaseerd op het tijdsbeeld". Dat betekent dat de bron opnieuw is gemaakt voor dit lesboek. Hij lijkt op echte bronnen uit de jaren 50, maar het is geen echt voorwerp uit die tijd.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat is een "gereconstrueerde bron"?',
          opties: ['Een bron die kapot is gegaan', 'Een bron die later opnieuw is gemaakt, zodat hij lijkt op echte bronnen uit die tijd', 'Een bron die in een museum ligt', 'Een bron die door een kind is gemaakt'], goed: 1,
          feedback: 'De bron is "opnieuw gemaakt voor dit lesboek" en "lijkt op echte bronnen uit de jaren 50".' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Wat kun je wél en níet met een gereconstrueerde bron?',
          opties: ['Je kunt er niets van leren, want hij is nep', 'Je leert hoe het er toen ongeveer uitzag, maar je kunt niet zeggen dat precies dit voorwerp echt bestaan heeft', 'Hij is net zo echt als een voorwerp uit een museum', 'Je kunt er precies uit halen wat één bepaald gezin dacht'], goed: 1,
          feedback: 'Hij is "gebaseerd op het tijdsbeeld": goed om de tijd te begrijpen, maar het is geen echt voorwerp van iemand uit de jaren 50.' },
      },
    ],
  },
  {
    nr: 6, titel: 'Nieuwe gezinnen', emoji: '🌈', cover: 'l6-regenboog',
    intro: 'Je leest een tijdlijn: "Van taboe naar trots". Hij laat zien hoe er in Nederland steeds meer ruimte kwam voor homo’s, lesbiennes en regenbooggezinnen.',
    klaar: 'Goed gedaan, tijdlijnlezer!',
    vragen: [
      {
        img: 'l6-taboe', bijschrift: 'Jaren 60',
        passage: 'Jaren 60 – Taboe. Over homoseksualiteit wordt bijna niet openlijk gepraat. Veel homo’s en lesbiennes durven niet te zeggen op wie ze verliefd zijn. In veel gezinnen is het een taboe. Ook op televisie komt het onderwerp bijna nooit voorbij.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent "taboe" in deze tekst?',
          opties: ['Iets wat verboden is in de wet', 'Iets waar mensen liever niet over praten', 'Een programma op televisie', 'Een ander woord voor verliefd'], goed: 1,
          feedback: 'In de tekst staat dat er "bijna niet openlijk" over gepraat wordt. Een taboe is een onderwerp waar je liever niet over praat.' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom durfden veel homo’s en lesbiennes in de jaren 60 niet te zeggen op wie ze verliefd waren?',
          opties: ['Omdat ze nog niet wisten wat verliefd was', 'Omdat er bijna niet over gepraat werd en het in veel gezinnen een taboe was', 'Omdat het op televisie werd afgeraden', 'Omdat ze het liever geheim hielden voor de lol'], goed: 1,
          feedback: 'Als niemand erover praat, ook thuis niet en op tv niet, is het moeilijk om eerlijk te zijn over wie je bent.' },
      },
      {
        img: 'l6-protest', bijschrift: '1969-1971: protest tegen artikel 248bis',
        passage: '1969-1971 – Protest artikel 248bis. Sinds 1911 staat er in de wet dat jongeren onder de 21 jaar geen verkering mogen hebben met iemand van hetzelfde geslacht. Voor jongeren die heteroseksueel zijn, geldt deze wet niet. Studenten vinden deze wet, die artikel 248bis wordt genoemd, oneerlijk. Ze protesteren. En met succes! De wet wordt in 1971 afgeschaft.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat er in artikel 248bis stond.',
          antwoord: 'jongeren onder de 21 jaar geen verkering mogen hebben met iemand van hetzelfde geslacht.', kern: ['21', 'verkering', 'geslacht'],
          feedback: 'Het staat in de eerste zin: "... dat jongeren onder de 21 jaar geen verkering mogen hebben met iemand van hetzelfde geslacht."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom vonden de studenten artikel 248bis oneerlijk?',
          opties: ['Omdat alle jongeren onder de 21 geen verkering mochten hebben', 'Omdat de wet alleen gold voor jongeren die verliefd werden op iemand van hetzelfde geslacht', 'Omdat studenten geen verkering mochten hebben', 'Omdat de wet pas in 1971 was gemaakt'], goed: 1,
          feedback: '"Voor jongeren die heteroseksueel zijn, geldt deze wet niet." De ene groep mocht iets wat de andere groep niet mocht.' },
      },
      {
        img: 'l6-premsela', bijschrift: '1964: Benno Premsela',
        passage: '1964 – Openlijk homoseksueel. Op televisie vertelt binnenhuisarchitect Benno Premsela openlijk dat hij homoseksueel is. Veel kijkers schrikken daarvan. Voor anderen voelt het juist als een belangrijke stap: eindelijk zegt iemand hardop wat veel mensen geheimhouden.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Hoe reageerden de kijkers op Benno Premsela?',
          opties: ['Iedereen vond het heel normaal', 'Veel kijkers schrokken, maar voor anderen was het juist een belangrijke stap', 'Niemand keek naar het programma', 'Alle kijkers werden boos'], goed: 1,
          feedback: '"Veel kijkers schrikken daarvan. Voor anderen voelt het juist als een belangrijke stap." Er waren dus twee soorten reacties.' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Waarom was het voor sommige mensen "een belangrijke stap"?',
          opties: ['Omdat Benno Premsela een beroemde architect was', 'Omdat eindelijk iemand hardop zei wat veel mensen geheim moesten houden', 'Omdat het de eerste keer was dat er televisie was', 'Omdat hij een prijs won'], goed: 1,
          feedback: '"Eindelijk zegt iemand hardop wat veel mensen geheimhouden." Voor wie zelf een geheim had, betekende dat veel.' },
      },
      {
        img: 'l6-tv', bijschrift: '1970: de eerste mannenzoen op tv',
        passage: '1970 – Eerste mannenzoen op tv. Op de Nederlandse televisie gebeurt iets wat kijkers nog nooit hebben gezien: twee mannen zoenen elkaar. Sommige mensen vinden dat vreemd of ongemakkelijk. Maar homoseksualiteit wordt daardoor wel zichtbaarder. Jaren 70-80 – De roze beweging groeit. Steeds meer homo’s en lesbiennes komen in actie. Ze protesteren, vragen om gelijke rechten en durven vaker openlijk zichzelf te zijn. Al die mensen en organisaties samen worden de roze beweging genoemd.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat de roze beweging is.',
          antwoord: 'Al die mensen en organisaties samen worden de roze beweging genoemd.', kern: ['mensen', 'organisaties', 'samen'],
          feedback: 'Het staat in de laatste zin: "Al die mensen en organisaties samen worden de roze beweging genoemd."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Sommige mensen vonden de mannenzoen ongemakkelijk. Waarom was hij volgens de tekst toch belangrijk?',
          opties: ['Omdat de kijkcijfers hoog waren', 'Omdat homoseksualiteit daardoor zichtbaarder werd', 'Omdat het een grap was', 'Omdat er daarna een nieuwe wet kwam'], goed: 1,
          feedback: '"Maar homoseksualiteit wordt daardoor wel zichtbaarder." Het woord "maar" laat zien dat dit het belangrijkste is.' },
      },
      {
        img: 'l6-wet', bijschrift: '1994: krantenkop over de nieuwe wet',
        passage: '1994 – Bescherming tegen discriminatie. Er komt een nieuwe wet die homo’s, lesbiennes en bi’s beter beschermt tegen discriminatie: de Algemene wet gelijke behandeling. Die wet zegt dat iemand niet oneerlijk behandeld mag worden omdat diegene homo, lesbisch of bi is.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst wat de Algemene wet gelijke behandeling zegt.',
          antwoord: 'iemand niet oneerlijk behandeld mag worden omdat diegene homo, lesbisch of bi is.', kern: ['niet', 'oneerlijk', 'behandeld'],
          feedback: 'Het staat in de laatste zin: "Die wet zegt dat iemand niet oneerlijk behandeld mag worden omdat diegene homo, lesbisch of bi is."' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'Iemand zegt: "Sinds deze wet wordt niemand meer gediscrimineerd." Klopt dat volgens de tekst?',
          opties: ['Ja, dat staat in de tekst', 'Nee, de tekst zegt alleen dat de wet mensen beter beschermt, niet dat discriminatie helemaal weg is', 'Ja, want een wet is altijd meteen klaar', 'Nee, want de wet geldt alleen voor bi’s'], goed: 1,
          feedback: 'De wet "beschermt beter" en zegt wat niet mag. Dat is iets anders dan dat het nooit meer gebeurt.' },
      },
      {
        img: 'l6-pride', bijschrift: '1996: de eerste Gay Pride in Amsterdam',
        passage: '1996 – Eerste Gay Pride. Amsterdam krijgt zijn eerste Gay Pride: een optocht van versierde boten door de grachten. Mensen zwaaien met regenboogvlaggen en vieren dat ze zichzelf mogen zijn. In andere landen bestaan al langer Pride-marsen als protest voor gelijke rechten. De Amsterdamse Gay Pride is vooral ook een feest: trots zijn op wie je bent.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat is het verschil tussen de Gay Pride in Amsterdam en de Pride-marsen in andere landen?',
          opties: ['In Amsterdam varen boten, in andere landen rijden auto’s', 'In andere landen waren het vooral protesten, in Amsterdam is het vooral ook een feest', 'In Amsterdam mag je geen vlag gebruiken', 'Er is geen verschil'], goed: 1,
          feedback: 'In andere landen zijn het marsen "als protest voor gelijke rechten". De Amsterdamse Gay Pride is "vooral ook een feest".' },
        g8: { type: 'mc', soort: 'beoordelen', vraag: 'De tijdlijn heet "Van taboe naar trots". Hoe past de Gay Pride bij die titel?',
          opties: ['Het is een voorbeeld van taboe: mensen verstoppen zich', 'Het is een voorbeeld van trots: mensen vieren openlijk wie ze zijn', 'Het past niet, want de Gay Pride gaat over boten', 'Het is het begin van de tijdlijn'], goed: 1,
          feedback: 'In de jaren 60 werd er niet over gepraat (taboe). Bij de Gay Pride vieren mensen in het openbaar dat ze zichzelf mogen zijn (trots).' },
      },
      {
        img: 'l6-huwelijk', bijschrift: '2001: het eerste homohuwelijk ter wereld',
        passage: '2001 – Eerste homohuwelijk ter wereld. In de nacht van 1 april 2001 trouwen in Amsterdam vier homoseksuele stellen. Burgemeester Job Cohen sluit de huwelijken in het stadhuis. Daarmee schrijft Nederland wereldgeschiedenis: het is het eerste land waar twee mannen of twee vrouwen officieel met elkaar mogen trouwen. (Artikel 248bis werd in 1971 afgeschaft.)',
        g7: { type: 'mark', vraag: 'Markeer in de tekst waarom Nederland in 2001 wereldgeschiedenis schreef.',
          antwoord: 'het is het eerste land waar twee mannen of twee vrouwen officieel met elkaar mogen trouwen.', kern: ['eerste', 'land', 'trouwen'],
          feedback: 'Het staat na de dubbele punt: "het is het eerste land waar twee mannen of twee vrouwen officieel met elkaar mogen trouwen."' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Hoeveel jaar zat er tussen het afschaffen van artikel 248bis en het eerste homohuwelijk?',
          opties: ['20 jaar', '30 jaar', '37 jaar', '90 jaar'], goed: 1,
          feedback: 'Artikel 248bis werd in 1971 afgeschaft, het eerste homohuwelijk was in 2001. 2001 − 1971 = 30 jaar.' },
      },
      {
        img: 'l6-samenouders', bijschrift: '2014: samen ouders',
        passage: '2014 – Samen ouders. Voor lesbische stellen wordt het makkelijker om samen officieel ouder te zijn. Tot 2014 werd alleen de moeder die het kind kreeg automatisch als ouder geregistreerd. Vanaf 2014 kan ook de andere moeder veel makkelijker officieel als ouder worden erkend.',
        g7: { type: 'mc', soort: 'afleiden', vraag: 'Wat veranderde er in 2014 voor lesbische stellen?',
          opties: ['Ze mochten voor het eerst trouwen', 'Ook de moeder die het kind niet zelf kreeg, kon makkelijker officieel ouder worden', 'Ze kregen meer kinderbijslag', 'Ze mochten voor het eerst samenwonen'], goed: 1,
          feedback: '"Vanaf 2014 kan ook de andere moeder veel makkelijker officieel als ouder worden erkend." Trouwen mocht al sinds 2001.' },
        g8: { type: 'mc', soort: 'afleiden', vraag: 'Wat betekent "automatisch als ouder geregistreerd"?',
          opties: ['Dat een computer bepaalt wie je ouders zijn', 'Dat je officieel als ouder bent ingeschreven, zonder dat je er iets extra voor hoeft te regelen', 'Dat je kind een automatische naam krijgt', 'Dat je elk jaar opnieuw moet laten weten dat je ouder bent'], goed: 1,
          feedback: 'Automatisch betekent: vanzelf. De moeder die het kind kreeg, stond meteen officieel als ouder ingeschreven. De andere moeder moest daar eerst veel voor regelen.' },
      },
      {
        img: 'l6-regenboog', bijschrift: 'Vanaf 2015: regenbooggezinnen',
        passage: 'Vanaf 2015 – Regenbooggezinnen. Steeds meer kinderen groeien op in een regenbooggezin. Dat is een gezin dat net even anders is dan een gezin met een vader en een moeder. Denk bijvoorbeeld aan twee moeders, twee vaders, één ouder. Maar het kan ook gaan om een samengesteld gezin of een gezin met ouders die samen op een andere manier een kind opvoeden. Op scholen, in kinderboeken en op televisie worden deze gezinnen steeds zichtbaarder.',
        g7: { type: 'mark', vraag: 'Markeer in de tekst welke voorbeelden van een regenbooggezin genoemd worden in de zin met "Denk bijvoorbeeld aan".',
          antwoord: 'twee moeders, twee vaders, één ouder.', kern: ['moeders', 'vaders', 'ouder'],
          feedback: 'Na "Denk bijvoorbeeld aan" staan de voorbeelden: "twee moeders, twee vaders, één ouder."' },
        g8: { type: 'drag', vraag: 'Kan dit volgens de tekst een regenbooggezin zijn? Sleep het naar de goede kant.',
          cats: ['Kan een regenbooggezin zijn', 'Noemt de tekst geen regenbooggezin'],
          items: [['Twee moeders', 'Kan een regenbooggezin zijn'], ['Eén ouder', 'Kan een regenbooggezin zijn'], ['Een samengesteld gezin', 'Kan een regenbooggezin zijn'], ['Twee vaders', 'Kan een regenbooggezin zijn'], ['Een vader en een moeder', 'Noemt de tekst geen regenbooggezin']],
          feedback: 'Een regenbooggezin is "net even anders dan een gezin met een vader en een moeder". De andere vier voorbeelden noemt de tekst wél.' },
      },
      {
        passage: 'In 2001 trouwden in Amsterdam de eerste homostellen ter wereld. Vijf jaar eerder was de eerste Gay Pride. In 1994 kwam de Algemene wet gelijke behandeling. Al in 1964 vertelde Benno Premsela op tv dat hij homo was. Zes jaar later was op tv de eerste mannenzoen te zien. Artikel 248bis werd in 1971 afgeschaft. In de jaren 60 werd er nog bijna niet over homoseksualiteit gepraat.',
        g7: { type: 'order', vraag: 'Zet deze gebeurtenissen van de tijdlijn op volgorde. Wat gebeurde het eerst?',
          items: ['Er wordt bijna niet over homoseksualiteit gepraat', 'Artikel 248bis wordt afgeschaft', 'De Algemene wet gelijke behandeling komt er', 'Het eerste homohuwelijk ter wereld'],
          feedback: 'Jaren 60 taboe → 1971 artikel 248bis afgeschaft → 1994 wet gelijke behandeling → 2001 eerste homohuwelijk.' },
        g8: { type: 'order', vraag: 'Zet deze gebeurtenissen op volgorde. Niet alle jaartallen staan erbij: reken ze uit!',
          items: ['Benno Premsela vertelt op tv dat hij homo is', 'De eerste mannenzoen op tv', 'Artikel 248bis wordt afgeschaft', 'De Algemene wet gelijke behandeling komt er', 'De eerste Gay Pride in Amsterdam', 'Het eerste homohuwelijk ter wereld'],
          feedback: '1964 Premsela → 1970 mannenzoen (zes jaar later) → 1971 artikel 248bis weg → 1994 wet → 1996 Gay Pride (vijf jaar vóór 2001) → 2001 homohuwelijk.' },
      },
    ],
  },
]
