export const WOORDSOORTEN = [
  { id: 'lw',  label: 'lidwoord' },
  { id: 'zn',  label: 'zelfstandig naamwoord' },
  { id: 'ww',  label: 'werkwoord' },
  { id: 'bnw', label: 'bijvoeglijk naamwoord' },
  { id: 'bw',  label: 'bijwoord' },
  { id: 'vnw', label: 'voornaamwoord' },
  { id: 'vz',  label: 'voorzetsel' },
  { id: 'tw',  label: 'telwoord' },
  { id: 'vgw', label: 'voegwoord' },
]

export const ZINSDELEN = [
  { id: 'ond', label: 'onderwerp' },
  { id: 'pv',  label: 'persoonsvorm' },
  { id: 'gez', label: 'gezegde' },
  { id: 'lv',  label: 'lijdend voorwerp' },
  { id: 'mv',  label: 'meewerkend voorwerp' },
  { id: 'bep', label: 'bepaling' },
]

// woordsoort: antwoord voor woordsoorten-modus (null = niet vragen)
// zinsdeel:   antwoord voor zinsdelen-modus   (null = niet vragen)
export const VRAGEN = [
  // ── Zin 1 ──────────────────────────────────────────────────────────────────
  { id: 1, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'hond',
    zinsdeelWoorden: 'De hond',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Hond" is een naam voor een dier — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',            uitleg_zd: 'Wie loopt? De hond! Dat is het onderwerp.' },
  { id: 2, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'loopt',
    woordsoort: 'werkwoord',            uitleg_ws: '"Loopt" zegt wat de hond doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',         uitleg_zd: 'Wat doet de hond? Hij loopt. "Loopt" is de persoonsvorm.' },
  { id: 3, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'snel',
    woordsoort: 'bijwoord',             uitleg_ws: '"Snel" zegt hoe de hond loopt — dat is een bijwoord.',
    zinsdeel:   'bepaling',             uitleg_zd: '"Snel" zegt hoe de hond loopt — dat is een bepaling.' },
  { id: 4, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'De',
    woordsoort: 'lidwoord',             uitleg_ws: '"De" is een bepaald lidwoord; het hoort bij "hond".',
    zinsdeel:   null },
  { id: 5, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'door',
    woordsoort: 'voorzetsel',           uitleg_ws: '"Door" geeft een richting aan — dat is een voorzetsel.',
    zinsdeel:   null },

  // ── Zin 2 ──────────────────────────────────────────────────────────────────
  { id: 6, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'Lisa',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Lisa" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie eet? Lisa! Dat is het onderwerp.' },
  { id: 7, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'eet',
    woordsoort: 'werkwoord',             uitleg_ws: '"Eet" zegt wat Lisa doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet Lisa? Ze eet. "Eet" is de persoonsvorm.' },
  { id: 8, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'appel',
    zinsdeelWoorden: 'een appel',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Appel" is een naam voor een vrucht — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat eet Lisa? Een appel! Dat is het lijdend voorwerp.' },
  { id: 9, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'voor',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Voor" geeft een verband aan — dat is een voorzetsel.',
    zinsdeel:   null },
  { id: 10, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'een',
    woordsoort: 'lidwoord',              uitleg_ws: '"Een" is een onbepaald lidwoord.',
    zinsdeel:   null },

  // ── Zin 3 ──────────────────────────────────────────────────────────────────
  { id: 11, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'Hij',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Hij" staat in de plaats van een naam — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie speelde? Hij! Dat is het onderwerp.' },
  { id: 12, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'speelde',
    woordsoort: 'werkwoord',             uitleg_ws: '"Speelde" is de verleden tijd van "spelen" — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat deed hij? Hij speelde. "Speelde" is de persoonsvorm.' },
  { id: 13, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'gisteren',
    woordsoort: 'bijwoord',              uitleg_ws: '"Gisteren" zegt wanneer hij speelde — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Gisteren" zegt wanneer hij speelde — dat is een bepaling.' },
  { id: 14, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'voetbal',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Voetbal" is een naam voor een sport — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat speelde hij? Voetbal! Dat is het lijdend voorwerp.' },
  { id: 15, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'zijn',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Zijn" (zijn vrienden) geeft aan van wie de vrienden zijn — dat is een bezittelijk voornaamwoord.',
    zinsdeel:   null },
  { id: 16, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'met',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Met" verbindt iets met de rest van de zin — dat is een voorzetsel.',
    zinsdeel:   null },

  // ── Zin 4 ──────────────────────────────────────────────────────────────────
  { id: 17, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'lerares',
    zinsdeelWoorden: 'De lerares',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Lerares" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie geeft? De lerares! Dat is het onderwerp.' },
  { id: 18, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'geeft',
    woordsoort: 'werkwoord',             uitleg_ws: '"Geeft" zegt wat de lerares doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de lerares? Ze geeft. "Geeft" is de persoonsvorm.' },
  { id: 19, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'drie',
    woordsoort: 'telwoord',              uitleg_ws: '"Drie" is een telwoord; het zegt hoeveel boeken er zijn.',
    zinsdeel:   null },
  { id: 20, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'boeken',
    zinsdeelWoorden: 'drie boeken',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Boeken" is een naam voor een ding — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat geeft de lerares? Boeken! Dat is het lijdend voorwerp.' },
  { id: 21, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'aan',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Aan" geeft een richting aan — dat is een voorzetsel.',
    zinsdeel:   null },
  { id: 100, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'kinderen',
    zinsdeelWoorden: 'aan de kinderen',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Kinderen" is een naam voor personen — dat is een zelfstandig naamwoord.',
    zinsdeel:   'meewerkend voorwerp',   uitleg_zd: 'Aan wie geeft de lerares de boeken? Aan de kinderen! Dat is het meewerkend voorwerp.' },

  // ── Zin 5 ──────────────────────────────────────────────────────────────────
  { id: 22, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'Wij',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Wij" staat in de plaats van namen — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie rijden? Wij! Dat is het onderwerp.' },
  { id: 23, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'rijden',
    woordsoort: 'werkwoord',             uitleg_ws: '"Rijden" zegt wat wij doen — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doen wij? Wij rijden. "Rijden" is de persoonsvorm.' },
  { id: 24, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'morgen',
    woordsoort: 'bijwoord',              uitleg_ws: '"Morgen" zegt wanneer we rijden — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Morgen" zegt wanneer we rijden — dat is een bepaling.' },
  { id: 25, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'naar',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Naar" geeft een richting aan — dat is een voorzetsel.',
    zinsdeel:   null },
  { id: 26, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'strand',
    zinsdeelWoorden: 'naar het strand',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Strand" is een naam voor een plek — dat is een zelfstandig naamwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Naar het strand" zegt waarheen we rijden — dat is een bepaling.' },

  // ── Zin 6 ──────────────────────────────────────────────────────────────────
  { id: 27, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'kleine',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Kleine" zegt hoe de kat eruit ziet — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 28, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'kat',
    zinsdeelWoorden: 'Een kleine kat',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Kat" is een naam voor een dier — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie slaapt? De kat! Dat is het onderwerp.' },
  { id: 29, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'slaapt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Slaapt" zegt wat de kat doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de kat? Ze slaapt. "Slaapt" is de persoonsvorm.' },
  { id: 30, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'altijd',
    woordsoort: 'bijwoord',              uitleg_ws: '"Altijd" zegt hoe vaak de kat slaapt — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Altijd" zegt hoe vaak de kat slaapt — dat is een bepaling.' },
  { id: 31, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'op',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Op" geeft een plek aan — dat is een voorzetsel.',
    zinsdeel:   null },
  { id: 32, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'Een',
    woordsoort: 'lidwoord',              uitleg_ws: '"Een" is een onbepaald lidwoord.',
    zinsdeel:   null },

  // ── Zin 7 ──────────────────────────────────────────────────────────────────
  { id: 33, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'Ze',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Ze" staat in de plaats van een naam — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie schrijft? Zij! Dat is het onderwerp.' },
  { id: 34, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'schrijft',
    woordsoort: 'werkwoord',             uitleg_ws: '"Schrijft" zegt wat ze doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet ze? Ze schrijft. "Schrijft" is de persoonsvorm.' },
  { id: 35, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'lang',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Lang" zegt hoe het verhaal is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 36, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'verhaal',
    zinsdeelWoorden: 'een lang verhaal',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Verhaal" is een naam voor een tekst — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat schrijft ze? Een verhaal! Dat is het lijdend voorwerp.' },
  { id: 37, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'haar',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Haar" (haar vakantie) geeft aan van wie de vakantie is — dat is een bezittelijk voornaamwoord.',
    zinsdeel:   null },
  { id: 38, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'over',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Over" verbindt twee woorden — dat is een voorzetsel.',
    zinsdeel:   null },

  // ── Zin 8 ──────────────────────────────────────────────────────────────────
  { id: 39, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'Papa',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Papa" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie koopt? Papa! Dat is het onderwerp.' },
  { id: 40, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'koopt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Koopt" zegt wat papa doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet papa? Hij koopt. "Koopt" is de persoonsvorm.' },
  { id: 41, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'twee',
    woordsoort: 'telwoord',              uitleg_ws: '"Twee" is een telwoord; het zegt hoeveel broden er zijn.',
    zinsdeel:   null },
  { id: 42, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'broden',
    zinsdeelWoorden: 'twee broden',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Broden" is een naam voor een ding — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat koopt papa? Broden! Dat is het lijdend voorwerp.' },
  { id: 43, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'bij',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Bij" geeft een plek aan — dat is een voorzetsel.',
    zinsdeel:   null },
  { id: 44, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'bakker',
    zinsdeelWoorden: 'bij de bakker',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Bakker" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Bij de bakker" zegt waar papa koopt — dat is een bepaling.' },

  // ── Zin 9 ──────────────────────────────────────────────────────────────────
  { id: 45, zin: 'Mijn zusje huilt nooit bij een film.',
    vraagWoord: 'Mijn',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Mijn" geeft aan van wie het zusje is — dat is een bezittelijk voornaamwoord.',
    zinsdeel:   null },
  { id: 46, zin: 'Mijn zusje huilt nooit bij een film.',
    vraagWoord: 'zusje',
    zinsdeelWoorden: 'Mijn zusje',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Zusje" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie huilt? Het zusje! Dat is het onderwerp.' },
  { id: 47, zin: 'Mijn zusje huilt nooit bij een film.',
    vraagWoord: 'huilt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Huilt" zegt wat het zusje doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet het zusje? Ze huilt. "Huilt" is de persoonsvorm.' },
  { id: 48, zin: 'Mijn zusje huilt nooit bij een film.',
    vraagWoord: 'nooit',
    woordsoort: 'bijwoord',              uitleg_ws: '"Nooit" zegt hoe vaak ze huilt — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Nooit" zegt hoe vaak ze huilt — dat is een bepaling.' },

  // ── Zin 10 ─────────────────────────────────────────────────────────────────
  { id: 49, zin: 'De blauwe auto rijdt snel door de stad.',
    vraagWoord: 'blauwe',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Blauwe" zegt welke kleur de auto heeft — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 50, zin: 'De blauwe auto rijdt snel door de stad.',
    vraagWoord: 'auto',
    zinsdeelWoorden: 'De blauwe auto',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Auto" is een naam voor een voertuig — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wat rijdt? De auto! Dat is het onderwerp.' },
  { id: 51, zin: 'De blauwe auto rijdt snel door de stad.',
    vraagWoord: 'rijdt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Rijdt" zegt wat de auto doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de auto? Hij rijdt. "Rijdt" is de persoonsvorm.' },
  { id: 52, zin: 'De blauwe auto rijdt snel door de stad.',
    vraagWoord: 'snel',
    woordsoort: 'bijwoord',              uitleg_ws: '"Snel" zegt hoe de auto rijdt — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Snel" zegt hoe de auto rijdt — dat is een bepaling.' },

  // ── Zin 11 ─────────────────────────────────────────────────────────────────
  { id: 53, zin: 'Onze juf vertelt een spannend verhaal.',
    vraagWoord: 'Onze',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Onze" geeft aan van wie de juf is — dat is een bezittelijk voornaamwoord.',
    zinsdeel:   null },
  { id: 54, zin: 'Onze juf vertelt een spannend verhaal.',
    vraagWoord: 'juf',
    zinsdeelWoorden: 'Onze juf',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Juf" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie vertelt? De juf! Dat is het onderwerp.' },
  { id: 55, zin: 'Onze juf vertelt een spannend verhaal.',
    vraagWoord: 'vertelt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Vertelt" zegt wat de juf doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de juf? Ze vertelt. "Vertelt" is de persoonsvorm.' },
  { id: 56, zin: 'Onze juf vertelt een spannend verhaal.',
    vraagWoord: 'spannend',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Spannend" zegt hoe het verhaal is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 57, zin: 'Onze juf vertelt een spannend verhaal.',
    vraagWoord: 'verhaal',
    zinsdeelWoorden: 'een spannend verhaal',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Verhaal" is een naam voor een tekst — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat vertelt de juf? Een verhaal! Dat is het lijdend voorwerp.' },

  // ── Zin 12 ─────────────────────────────────────────────────────────────────
  { id: 58, zin: 'De vogels zingen vroeg in de ochtend.',
    vraagWoord: 'vogels',
    zinsdeelWoorden: 'De vogels',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Vogels" is een naam voor dieren — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie zingen? De vogels! Dat is het onderwerp.' },
  { id: 59, zin: 'De vogels zingen vroeg in de ochtend.',
    vraagWoord: 'zingen',
    woordsoort: 'werkwoord',             uitleg_ws: '"Zingen" zegt wat de vogels doen — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doen de vogels? Ze zingen. "Zingen" is de persoonsvorm.' },
  { id: 60, zin: 'De vogels zingen vroeg in de ochtend.',
    vraagWoord: 'vroeg',
    woordsoort: 'bijwoord',              uitleg_ws: '"Vroeg" zegt wanneer ze zingen — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Vroeg" zegt wanneer ze zingen — dat is een bepaling.' },
  { id: 61, zin: 'De vogels zingen vroeg in de ochtend.',
    vraagWoord: 'in',
    woordsoort: 'voorzetsel',            uitleg_ws: '"In" geeft een tijdstip aan — dat is een voorzetsel.',
    zinsdeel:   null },

  // ── Zin 13 ─────────────────────────────────────────────────────────────────
  { id: 62, zin: 'Tom en Emma spelen samen in de tuin.',
    vraagWoord: 'en',
    woordsoort: 'voegwoord',             uitleg_ws: '"En" verbindt twee namen — dat is een voegwoord.',
    zinsdeel:   null },
  { id: 63, zin: 'Tom en Emma spelen samen in de tuin.',
    vraagWoord: 'spelen',
    woordsoort: 'werkwoord',             uitleg_ws: '"Spelen" zegt wat Tom en Emma doen — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doen Tom en Emma? Ze spelen. "Spelen" is de persoonsvorm.' },
  { id: 64, zin: 'Tom en Emma spelen samen in de tuin.',
    vraagWoord: 'samen',
    woordsoort: 'bijwoord',              uitleg_ws: '"Samen" zegt hoe ze spelen — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Samen" zegt hoe ze spelen — dat is een bepaling.' },
  { id: 65, zin: 'Tom en Emma spelen samen in de tuin.',
    vraagWoord: 'tuin',
    zinsdeelWoorden: 'in de tuin',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Tuin" is een naam voor een plek — dat is een zelfstandig naamwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"In de tuin" zegt waar ze spelen — dat is een bepaling.' },

  // ── Zin 14 ─────────────────────────────────────────────────────────────────
  { id: 66, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'Ik',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Ik" is een persoonlijk voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie loopt? Ik! Dat is het onderwerp.' },
  { id: 67, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'loop',
    woordsoort: 'werkwoord',             uitleg_ws: '"Loop" zegt wat ik doe — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doe ik? Ik loop. "Loop" is de persoonsvorm.' },
  { id: 68, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'tien',
    woordsoort: 'telwoord',              uitleg_ws: '"Tien" is een telwoord; het zegt hoeveel minuten.',
    zinsdeel:   null },
  { id: 69, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'naar',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Naar" geeft een richting aan — dat is een voorzetsel.',
    zinsdeel:   null },
  { id: 70, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'school',
    zinsdeelWoorden: 'naar school',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"School" is een naam voor een gebouw — dat is een zelfstandig naamwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Naar school" zegt waarheen ik loop — dat is een bepaling.' },

  // ── Zin 15 ─────────────────────────────────────────────────────────────────
  { id: 71, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'lacht',
    woordsoort: 'werkwoord',             uitleg_ws: '"Lacht" zegt wat ze doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet ze? Ze lacht. "Lacht" is de persoonsvorm.' },
  { id: 72, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'omdat',
    woordsoort: 'voegwoord',             uitleg_ws: '"Omdat" verbindt twee zinsdelen — dat is een voegwoord.',
    zinsdeel:   null },
  { id: 73, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'leuk',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Leuk" zegt hoe het cadeau is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 74, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'cadeau',
    zinsdeelWoorden: 'een leuk cadeau',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Cadeau" is een naam voor een ding — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat heeft ze gekregen? Een cadeau! Dat is het lijdend voorwerp.' },

  // ── Zin 16 ─────────────────────────────────────────────────────────────────
  { id: 75, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'Vijf',
    woordsoort: 'telwoord',              uitleg_ws: '"Vijf" is een telwoord; het zegt hoeveel kinderen er zijn.',
    zinsdeel:   null },
  { id: 76, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'kinderen',
    zinsdeelWoorden: 'Vijf kinderen',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Kinderen" is een naam voor personen — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie lopen? De kinderen! Dat is het onderwerp.' },
  { id: 77, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'lopen',
    woordsoort: 'werkwoord',             uitleg_ws: '"Lopen" zegt wat de kinderen doen — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doen de kinderen? Ze lopen. "Lopen" is de persoonsvorm.' },
  { id: 78, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'hard',
    woordsoort: 'bijwoord',              uitleg_ws: '"Hard" zegt hoe ze lopen — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Hard" zegt hoe ze lopen — dat is een bepaling.' },
  { id: 79, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'over',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Over" geeft een richting aan — dat is een voorzetsel.',
    zinsdeel:   null },

  // ── Zin 17 ─────────────────────────────────────────────────────────────────
  { id: 80, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'grote',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Grote" zegt hoe de beer eruit ziet — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 81, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'beer',
    zinsdeelWoorden: 'De grote beer',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Beer" is een naam voor een dier — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie slaapt? De beer! Dat is het onderwerp.' },
  { id: 82, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'slaapt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Slaapt" zegt wat de beer doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de beer? Hij slaapt. "Slaapt" is de persoonsvorm.' },
  { id: 83, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'rustig',
    woordsoort: 'bijwoord',              uitleg_ws: '"Rustig" zegt hoe de beer slaapt — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Rustig" zegt hoe de beer slaapt — dat is een bepaling.' },
  { id: 84, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'hol',
    zinsdeelWoorden: 'in zijn hol',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Hol" is een naam voor een plek — dat is een zelfstandig naamwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"In zijn hol" zegt waar de beer slaapt — dat is een bepaling.' },

  // ── Zin 18 ─────────────────────────────────────────────────────────────────
  { id: 85, zin: 'Zij tekent elke avond mooie plaatjes.',
    vraagWoord: 'Zij',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Zij" staat in de plaats van een naam — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie tekent? Zij! Dat is het onderwerp.' },
  { id: 86, zin: 'Zij tekent elke avond mooie plaatjes.',
    vraagWoord: 'tekent',
    woordsoort: 'werkwoord',             uitleg_ws: '"Tekent" zegt wat zij doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet zij? Ze tekent. "Tekent" is de persoonsvorm.' },
  { id: 87, zin: 'Zij tekent elke avond mooie plaatjes.',
    vraagWoord: 'mooie',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Mooie" zegt hoe de plaatjes zijn — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 88, zin: 'Zij tekent elke avond mooie plaatjes.',
    vraagWoord: 'plaatjes',
    zinsdeelWoorden: 'mooie plaatjes',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Plaatjes" is een naam voor dingen — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat tekent zij? Plaatjes! Dat is het lijdend voorwerp.' },

  // ── Zin 19 ─────────────────────────────────────────────────────────────────
  { id: 89, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'kok',
    zinsdeelWoorden: 'De kok',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Kok" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie bakt? De kok! Dat is het onderwerp.' },
  { id: 90, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'bakt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Bakt" zegt wat de kok doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de kok? Hij bakt. "Bakt" is de persoonsvorm.' },
  { id: 91, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'tien',
    woordsoort: 'telwoord',              uitleg_ws: '"Tien" is een telwoord; het zegt hoeveel pannenkoeken.',
    zinsdeel:   null },
  { id: 92, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'pannenkoeken',
    zinsdeelWoorden: 'tien pannenkoeken',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Pannenkoeken" is een naam voor eten — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat bakt de kok? Pannenkoeken! Dat is het lijdend voorwerp.' },
  { id: 93, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'voor',
    woordsoort: 'voorzetsel',            uitleg_ws: '"Voor" geeft een doel aan — dat is een voorzetsel.',
    zinsdeel:   null },

  // ── Zin 20 ─────────────────────────────────────────────────────────────────
  { id: 94, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'maar',
    woordsoort: 'voegwoord',             uitleg_ws: '"Maar" verbindt twee tegengestelde zinnen — dat is een voegwoord.',
    zinsdeel:   null },
  { id: 95, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'hoog',
    woordsoort: 'bijwoord',              uitleg_ws: '"Hoog" zegt hoe we springen — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Hoog" zegt hoe we springen — dat is een bepaling.' },
  { id: 96, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'springen',
    woordsoort: 'werkwoord',             uitleg_ws: '"Springen" zegt wat wij doen — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doen wij? Wij springen. "Springen" is de persoonsvorm.' },
  { id: 97, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'diep',
    woordsoort: 'bijwoord',              uitleg_ws: '"Diep" zegt hoe hij duikt — dat is een bijwoord.',
    zinsdeel:   'bepaling',              uitleg_zd: '"Diep" zegt hoe hij duikt — dat is een bepaling.' },

  // ── Zin 21 (meewerkend voorwerp) ─────────────────────────────────────────────
  { id: 101, zin: 'Tom geeft zijn oma een grote knuffel.',
    vraagWoord: 'Tom',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Tom" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie geeft? Tom! Dat is het onderwerp.' },
  { id: 102, zin: 'Tom geeft zijn oma een grote knuffel.',
    vraagWoord: 'geeft',
    woordsoort: 'werkwoord',             uitleg_ws: '"Geeft" zegt wat Tom doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet Tom? Hij geeft. "Geeft" is de persoonsvorm.' },
  { id: 103, zin: 'Tom geeft zijn oma een grote knuffel.',
    vraagWoord: 'oma',
    zinsdeelWoorden: 'zijn oma',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Oma" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'meewerkend voorwerp',   uitleg_zd: 'Aan wie geeft Tom de knuffel? Aan zijn oma! Dat is het meewerkend voorwerp.' },
  { id: 104, zin: 'Tom geeft zijn oma een grote knuffel.',
    vraagWoord: 'grote',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Grote" zegt hoe de knuffel is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 105, zin: 'Tom geeft zijn oma een grote knuffel.',
    vraagWoord: 'knuffel',
    zinsdeelWoorden: 'een grote knuffel',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Knuffel" is een naam voor een ding — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat geeft Tom? Een knuffel! Dat is het lijdend voorwerp.' },

  // ── Zin 22 (meewerkend voorwerp) ─────────────────────────────────────────────
  { id: 106, zin: 'De juf leest de kinderen een spannend verhaal voor.',
    vraagWoord: 'juf',
    zinsdeelWoorden: 'De juf',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Juf" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie leest voor? De juf! Dat is het onderwerp.' },
  { id: 107, zin: 'De juf leest de kinderen een spannend verhaal voor.',
    vraagWoord: 'leest',
    woordsoort: 'werkwoord',             uitleg_ws: '"Leest" zegt wat de juf doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de juf? Ze leest. "Leest" is de persoonsvorm.' },
  { id: 108, zin: 'De juf leest de kinderen een spannend verhaal voor.',
    vraagWoord: 'kinderen',
    zinsdeelWoorden: 'de kinderen',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Kinderen" is een naam voor personen — dat is een zelfstandig naamwoord.',
    zinsdeel:   'meewerkend voorwerp',   uitleg_zd: 'Aan wie leest de juf voor? Aan de kinderen! Dat is het meewerkend voorwerp.' },
  { id: 109, zin: 'De juf leest de kinderen een spannend verhaal voor.',
    vraagWoord: 'spannend',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Spannend" zegt hoe het verhaal is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 110, zin: 'De juf leest de kinderen een spannend verhaal voor.',
    vraagWoord: 'verhaal',
    zinsdeelWoorden: 'een spannend verhaal',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Verhaal" is een naam voor een tekst — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat leest de juf? Een verhaal! Dat is het lijdend voorwerp.' },

  // ── Zin 23 (meewerkend voorwerp) ─────────────────────────────────────────────
  { id: 111, zin: 'Ik stuur mijn beste vriend een brief.',
    vraagWoord: 'Ik',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Ik" is een persoonlijk voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie stuurt? Ik! Dat is het onderwerp.' },
  { id: 112, zin: 'Ik stuur mijn beste vriend een brief.',
    vraagWoord: 'stuur',
    woordsoort: 'werkwoord',             uitleg_ws: '"Stuur" zegt wat ik doe — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doe ik? Ik stuur. "Stuur" is de persoonsvorm.' },
  { id: 113, zin: 'Ik stuur mijn beste vriend een brief.',
    vraagWoord: 'vriend',
    zinsdeelWoorden: 'mijn beste vriend',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Vriend" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'meewerkend voorwerp',   uitleg_zd: 'Aan wie stuur ik een brief? Aan mijn vriend! Dat is het meewerkend voorwerp.' },
  { id: 114, zin: 'Ik stuur mijn beste vriend een brief.',
    vraagWoord: 'brief',
    zinsdeelWoorden: 'een brief',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Brief" is een naam voor een ding — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat stuur ik? Een brief! Dat is het lijdend voorwerp.' },

  // ── Zin 24 (meewerkend voorwerp) ─────────────────────────────────────────────
  { id: 115, zin: 'Opa vertelt ons een grappige mop.',
    vraagWoord: 'Opa',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Opa" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie vertelt? Opa! Dat is het onderwerp.' },
  { id: 116, zin: 'Opa vertelt ons een grappige mop.',
    vraagWoord: 'vertelt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Vertelt" zegt wat opa doet — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet opa? Hij vertelt. "Vertelt" is de persoonsvorm.' },
  { id: 117, zin: 'Opa vertelt ons een grappige mop.',
    vraagWoord: 'ons',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Ons" staat in de plaats van namen — dat is een voornaamwoord.',
    zinsdeel:   'meewerkend voorwerp',   uitleg_zd: 'Aan wie vertelt opa de mop? Aan ons! Dat is het meewerkend voorwerp.' },
  { id: 118, zin: 'Opa vertelt ons een grappige mop.',
    vraagWoord: 'grappige',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Grappige" zegt hoe de mop is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 119, zin: 'Opa vertelt ons een grappige mop.',
    vraagWoord: 'mop',
    zinsdeelWoorden: 'een grappige mop',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Mop" is een naam voor een grapje — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat vertelt opa? Een mop! Dat is het lijdend voorwerp.' },

  // ── Zin 25 — gezegde (één werkwoord = persoonsvorm én gezegde) ──────────────
  { id: 120, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'loopt',
    woordsoort: null,
    zinsdeel:   'gezegde', uitleg_zd: 'Er is maar één werkwoord in de zin: "loopt". Dan zijn persoonsvorm én gezegde hetzelfde woord.' },

  // ── Zin 26 — werkwoordelijk gezegde (twee werkwoorden samen) ────────────────
  { id: 121, zin: 'Hij heeft een nieuwe fiets gekocht.',
    vraagWoord: 'Hij',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Hij" staat in de plaats van een naam — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie heeft gekocht? Hij! Dat is het onderwerp.' },
  { id: 122, zin: 'Hij heeft een nieuwe fiets gekocht.',
    vraagWoord: 'heeft',
    woordsoort: 'werkwoord',             uitleg_ws: '"Heeft" is het hulpwerkwoord bij "gekocht" — samen zijn het werkwoorden.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'De persoonsvorm is het werkwoord dat verandert met het onderwerp: "heeft".' },
  { id: 123, zin: 'Hij heeft een nieuwe fiets gekocht.',
    vraagWoord: 'heeft gekocht',
    woordsoort: null,
    zinsdeel:   'gezegde', uitleg_zd: 'Het werkwoordelijk gezegde bestaat hier uit twéé woorden: de persoonsvorm "heeft" + het voltooid deelwoord "gekocht".' },
  { id: 124, zin: 'Hij heeft een nieuwe fiets gekocht.',
    vraagWoord: 'nieuwe',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Nieuwe" zegt hoe de fiets is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },
  { id: 125, zin: 'Hij heeft een nieuwe fiets gekocht.',
    vraagWoord: 'fiets',
    zinsdeelWoorden: 'een nieuwe fiets',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Fiets" is een naam voor een ding — dat is een zelfstandig naamwoord.',
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat heeft hij gekocht? Een fiets! Dat is het lijdend voorwerp.' },

  // ── Zin 27 — werkwoordelijk gezegde met "zijn" ───────────────────────────────
  { id: 126, zin: 'Zij is naar het feest gegaan.',
    vraagWoord: 'Zij',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Zij" staat in de plaats van een naam — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie is gegaan? Zij! Dat is het onderwerp.' },
  { id: 127, zin: 'Zij is naar het feest gegaan.',
    vraagWoord: 'is',
    woordsoort: 'werkwoord',             uitleg_ws: '"Is" is hier het hulpwerkwoord bij "gegaan" — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'De persoonsvorm is "is" — het verandert mee met het onderwerp.' },
  { id: 128, zin: 'Zij is naar het feest gegaan.',
    vraagWoord: 'is gegaan',
    woordsoort: null,
    zinsdeel:   'gezegde', uitleg_zd: 'Werkwoordelijk gezegde van twee woorden: "is" (persoonsvorm) + "gegaan" (voltooid deelwoord).' },

  // ── Zin 28 — naamwoordelijk gezegde (koppelwerkwoord + bijvoeglijk naamwoord) ─
  { id: 129, zin: 'De soep is heerlijk.',
    vraagWoord: 'soep',
    zinsdeelWoorden: 'De soep',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Soep" is een naam voor eten — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Waar gaat de zin over? De soep! Dat is het onderwerp.' },
  { id: 130, zin: 'De soep is heerlijk.',
    vraagWoord: 'is',
    woordsoort: 'werkwoord',             uitleg_ws: '"Is" is hier een koppelwerkwoord — dat is ook een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'De persoonsvorm is "is".' },
  { id: 131, zin: 'De soep is heerlijk.',
    vraagWoord: 'is heerlijk',
    woordsoort: null,
    zinsdeel:   'gezegde', uitleg_zd: 'Naamwoordelijk gezegde: koppelwerkwoord "is" + "heerlijk", dat iets zegt over het onderwerp.' },
  { id: 132, zin: 'De soep is heerlijk.',
    vraagWoord: 'heerlijk',
    woordsoort: 'bijvoeglijk naamwoord', uitleg_ws: '"Heerlijk" zegt hoe de soep is — dat is een bijvoeglijk naamwoord.',
    zinsdeel:   null },

  // ── Zin 29 — naamwoordelijk gezegde met "worden" ────────────────────────────
  { id: 133, zin: 'Mijn broer wordt boos.',
    vraagWoord: 'broer',
    zinsdeelWoorden: 'Mijn broer',
    woordsoort: 'zelfstandig naamwoord', uitleg_ws: '"Broer" is een naam voor een persoon — dat is een zelfstandig naamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie wordt boos? Mijn broer! Dat is het onderwerp.' },
  { id: 134, zin: 'Mijn broer wordt boos.',
    vraagWoord: 'wordt',
    woordsoort: 'werkwoord',             uitleg_ws: '"Wordt" is hier een koppelwerkwoord — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'De persoonsvorm is "wordt".' },
  { id: 135, zin: 'Mijn broer wordt boos.',
    vraagWoord: 'wordt boos',
    woordsoort: null,
    zinsdeel:   'gezegde', uitleg_zd: 'Naamwoordelijk gezegde: koppelwerkwoord "wordt" + "boos", dat zegt hoe het onderwerp wordt.' },

  // ── Zin 30 — werkwoordelijk gezegde met hulpwerkwoord "mogen" ───────────────
  { id: 136, zin: 'Wij mogen buiten spelen.',
    vraagWoord: 'Wij',
    woordsoort: 'voornaamwoord',         uitleg_ws: '"Wij" staat in de plaats van namen — dat is een voornaamwoord.',
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie mogen spelen? Wij! Dat is het onderwerp.' },
  { id: 137, zin: 'Wij mogen buiten spelen.',
    vraagWoord: 'mogen',
    woordsoort: 'werkwoord',             uitleg_ws: '"Mogen" is het hulpwerkwoord bij "spelen" — dat is een werkwoord.',
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'De persoonsvorm is "mogen".' },
  { id: 138, zin: 'Wij mogen buiten spelen.',
    vraagWoord: 'mogen spelen',
    woordsoort: null,
    zinsdeel:   'gezegde', uitleg_zd: 'Werkwoordelijk gezegde van twee woorden: hulpwerkwoord "mogen" + infinitief "spelen".' },
  // ── Ontbrekend onderwerp bij "Tom en Emma" (samengesteld onderwerp) ─────────
  { id: 139, zin: 'Tom en Emma spelen samen in de tuin.',
    vraagWoord: 'Tom en Emma',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie spelen er? Tom en Emma! Samen zijn zij het onderwerp.' },

  // ── Samengestelde zinnen ───────────────────────────────────────────────────
  // Twee deelzinnen, elk met een eigen onderwerp en persoonsvorm. Ze staan in
  // SAMENGESTELDE_ZINNEN hieronder en komen alleen langs als de leerling "ook
  // samengestelde zinnen" aanzet. woordsoort blijft null: deze zinnen zijn er
  // voor het ontleden, niet voor de woordsoorten-oefening.
  { id: 140, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'Wij',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie springen er hoog? Wij! Onderwerp van het eerste stukje.' },
  { id: 141, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'hij',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie duikt diep? Hij! Onderwerp van het tweede stukje.' },
  { id: 142, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'duikt',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet hij? Hij duikt. "Duikt" is de persoonsvorm van het tweede stukje.' },

  { id: 143, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'Ze',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie lacht? Ze! Onderwerp van de hoofdzin.' },
  { id: 144, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'ze',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie heeft dat cadeau gekregen? Ze! Onderwerp van de bijzin.' },
  { id: 145, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'heeft',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Verander de zin naar gisteren: "had". "Heeft" is de persoonsvorm van de bijzin.' },

  { id: 146, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'zon', zinsdeelWoorden: 'De zon',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wat schijnt er? De zon! Onderwerp van het eerste stukje.' },
  { id: 147, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'schijnt',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de zon? Hij schijnt. "Schijnt" is de persoonsvorm.' },
  { id: 148, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'vogels', zinsdeelWoorden: 'de vogels',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie zingen er? De vogels! Onderwerp van het tweede stukje.' },
  { id: 149, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'zingen',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doen de vogels? Ze zingen. "Zingen" is de persoonsvorm.' },
  { id: 150, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'vrolijk',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Vrolijk" zegt hoe de vogels zingen — dat is een bepaling.' },

  { id: 151, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'Ik',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie pakt er een jas? Ik! Onderwerp van het eerste stukje.' },
  { id: 152, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'pak',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doe ik? Ik pak. "Pak" is de persoonsvorm.' },
  { id: 153, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'jas', zinsdeelWoorden: 'mijn jas',
    woordsoort: null,
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat pak ik? Mijn jas! Dat is het lijdend voorwerp.' },
  { id: 154, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'het',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wat regent er? Het! Onderwerp van het tweede stukje.' },
  { id: 155, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'regent',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Verander naar gisteren: "regende". "Regent" is de persoonsvorm.' },
  { id: 156, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'buiten',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Buiten" zegt waar het regent — dat is een bepaling.' },

  { id: 157, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'Wij',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie blijven er binnen? Wij! Onderwerp van de hoofdzin.' },
  { id: 158, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'blijven',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Verander naar gisteren: "bleven". "Blijven" is de persoonsvorm.' },
  { id: 159, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'binnen',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Binnen" zegt waar wij blijven — dat is een bepaling.' },
  { id: 160, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'het',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wat onweert er? Het! Onderwerp van de bijzin.' },
  { id: 161, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'hard',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Hard" zegt hoe het onweert — dat is een bepaling.' },
  { id: 162, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'onweert',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Verander naar gisteren: "onweerde". "Onweert" is de persoonsvorm van de bijzin.' },

  { id: 163, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'Papa',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie kookt er? Papa! Onderwerp van de hoofdzin.' },
  { id: 164, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'kookt',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet papa? Hij kookt. "Kookt" is de persoonsvorm.' },
  { id: 165, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'eten', zinsdeelWoorden: 'het eten',
    woordsoort: null,
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat kookt papa? Het eten! Dat is het lijdend voorwerp.' },
  { id: 166, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'mama',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie dekt de tafel? Mama! Onderwerp van de bijzin.' },
  { id: 167, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'tafel', zinsdeelWoorden: 'de tafel',
    woordsoort: null,
    zinsdeel:   'lijdend voorwerp',      uitleg_zd: 'Wat dekt mama? De tafel! Dat is het lijdend voorwerp van de bijzin.' },
  { id: 168, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'dekt',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet mama? Ze dekt. "Dekt" is de persoonsvorm van de bijzin.' },

  { id: 169, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'hond', zinsdeelWoorden: 'De hond',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie blaft er? De hond! Onderwerp van het eerste stukje.' },
  { id: 170, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'blaft',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de hond? Hij blaft. "Blaft" is de persoonsvorm.' },
  { id: 171, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'hard',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Hard" zegt hoe de hond blaft — dat is een bepaling.' },
  { id: 172, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'kat', zinsdeelWoorden: 'de kat',
    woordsoort: null,
    zinsdeel:   'onderwerp',             uitleg_zd: 'Wie slaapt er? De kat! Onderwerp van het tweede stukje.' },
  { id: 173, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'slaapt',
    woordsoort: null,
    zinsdeel:   'persoonsvorm',          uitleg_zd: 'Wat doet de kat? Ze slaapt. "Slaapt" is de persoonsvorm.' },
  { id: 174, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'rustig',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Rustig" zegt hoe de kat slaapt — dat is een bepaling.' },
  // ── Bepalingen die nog ontbraken (nodig om de zin in groepen te knippen) ───
  { id: 175, zin: 'De hond loopt snel door het park.',
    vraagWoord: 'park', zinsdeelWoorden: 'door het park',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Door het park" zegt waar de hond loopt — dat is ook een bepaling.' },
  { id: 176, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'dag', zinsdeelWoorden: 'elke dag',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Elke dag" zegt wanneer Lisa een appel eet — dat is een bepaling.' },
  { id: 177, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'school', zinsdeelWoorden: 'voor school',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Voor school" zegt wanneer ze eet — dat is ook een bepaling.' },
  { id: 178, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'vrienden', zinsdeelWoorden: 'met zijn vrienden',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Met zijn vrienden" zegt met wie hij speelde — dat is een bepaling.' },
  { id: 179, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'fiets', zinsdeelWoorden: 'met de fiets',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Met de fiets" zegt waarmee we rijden — dat is een bepaling.' },
  { id: 180, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'strand', zinsdeelWoorden: 'naar het strand',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Naar het strand" zegt waarheen we rijden — dat is een bepaling.' },
  { id: 181, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'bank', zinsdeelWoorden: 'op de bank',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Op de bank" zegt waar de kat slaapt — dat is een bepaling.' },
  { id: 182, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'vakantie', zinsdeelWoorden: 'over haar vakantie',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Over haar vakantie" zegt waarover ze schrijft — dat is een bepaling.' },
  { id: 183, zin: 'Mijn zusje huilt nooit bij een film.',
    vraagWoord: 'film', zinsdeelWoorden: 'bij een film',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Bij een film" zegt wanneer ze niet huilt — dat is een bepaling.' },
  { id: 184, zin: 'De blauwe auto rijdt snel door de stad.',
    vraagWoord: 'stad', zinsdeelWoorden: 'door de stad',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Door de stad" zegt waar de auto rijdt — dat is een bepaling.' },
  { id: 185, zin: 'De vogels zingen vroeg in de ochtend.',
    vraagWoord: 'ochtend', zinsdeelWoorden: 'in de ochtend',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"In de ochtend" zegt wanneer de vogels zingen — dat is een bepaling.' },
  { id: 186, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'ochtend', zinsdeelWoorden: 'elke ochtend',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Elke ochtend" zegt wanneer ik loop — dat is een bepaling.' },
  { id: 187, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'minuten', zinsdeelWoorden: 'tien minuten',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Tien minuten" zegt hoe lang ik loop — dat is een bepaling.' },
  { id: 188, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'schoolplein', zinsdeelWoorden: 'over het schoolplein',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Over het schoolplein" zegt waar ze lopen — dat is een bepaling.' },
  { id: 189, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'hol', zinsdeelWoorden: 'in zijn hol',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"In zijn hol" zegt waar de beer slaapt — dat is een bepaling.' },
  { id: 190, zin: 'Zij tekent elke avond mooie plaatjes.',
    vraagWoord: 'avond', zinsdeelWoorden: 'elke avond',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Elke avond" zegt wanneer zij tekent — dat is een bepaling.' },
  { id: 191, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'feest', zinsdeelWoorden: 'voor het feest',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Voor het feest" zegt waarvoor de kok bakt — dat is een bepaling.' },
  { id: 192, zin: 'Zij is naar het feest gegaan.',
    vraagWoord: 'feest', zinsdeelWoorden: 'naar het feest',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Naar het feest" zegt waarheen zij is gegaan — dat is een bepaling.' },
  { id: 193, zin: 'Wij mogen buiten spelen.',
    vraagWoord: 'buiten',
    woordsoort: null,
    zinsdeel:   'bepaling',              uitleg_zd: '"Buiten" zegt waar we mogen spelen — dat is een bepaling.' },
  // ── Gezegde bij elke zin ──────────────────────────────────────────────────
  // Vink je "gezegde" aan, dan is er in iedere zin ook een gezegde te leggen.
  // Bij één werkwoord is dat hetzelfde woord als de persoonsvorm.
  { id: 194, zin: 'Lisa eet elke dag een appel voor school.',
    vraagWoord: 'eet',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "eet". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 195, zin: 'Hij speelde gisteren voetbal met zijn vrienden.',
    vraagWoord: 'speelde',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "speelde". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 196, zin: 'De lerares geeft drie boeken aan de kinderen.',
    vraagWoord: 'geeft',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "geeft". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 197, zin: 'Wij rijden morgen met de fiets naar het strand.',
    vraagWoord: 'rijden',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "rijden". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 198, zin: 'Een kleine kat slaapt altijd op de bank.',
    vraagWoord: 'slaapt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "slaapt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 199, zin: 'Ze schrijft een lang verhaal over haar vakantie.',
    vraagWoord: 'schrijft',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "schrijft". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 200, zin: 'Papa koopt twee broden bij de bakker.',
    vraagWoord: 'koopt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "koopt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 201, zin: 'Mijn zusje huilt nooit bij een film.',
    vraagWoord: 'huilt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "huilt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 202, zin: 'De blauwe auto rijdt snel door de stad.',
    vraagWoord: 'rijdt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "rijdt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 203, zin: 'Onze juf vertelt een spannend verhaal.',
    vraagWoord: 'vertelt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "vertelt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 204, zin: 'De vogels zingen vroeg in de ochtend.',
    vraagWoord: 'zingen',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "zingen". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 205, zin: 'Tom en Emma spelen samen in de tuin.',
    vraagWoord: 'spelen',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "spelen". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 206, zin: 'Ik loop elke ochtend tien minuten naar school.',
    vraagWoord: 'loop',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "loop". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 207, zin: 'Vijf kinderen lopen hard over het schoolplein.',
    vraagWoord: 'lopen',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "lopen". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 208, zin: 'De grote beer slaapt rustig in zijn hol.',
    vraagWoord: 'slaapt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "slaapt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 209, zin: 'Zij tekent elke avond mooie plaatjes.',
    vraagWoord: 'tekent',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "tekent". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 210, zin: 'De kok bakt tien pannenkoeken voor het feest.',
    vraagWoord: 'bakt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "bakt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 211, zin: 'Tom geeft zijn oma een grote knuffel.',
    vraagWoord: 'geeft',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "geeft". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 212, zin: 'Ik stuur mijn beste vriend een brief.',
    vraagWoord: 'stuur',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "stuur". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 213, zin: 'Opa vertelt ons een grappige mop.',
    vraagWoord: 'vertelt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Er is maar één werkwoord in de zin: "vertelt". Dan zijn de persoonsvorm en het gezegde hetzelfde woord.' },
  { id: 214, zin: 'De juf leest de kinderen een spannend verhaal voor.',
    vraagWoord: 'leest voor',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'Het werkwoord is "voorlezen": "leest" en "voor" horen bij elkaar en vormen samen het gezegde.' },
  { id: 215, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'lacht',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In de hoofdzin is "lacht" het enige werkwoord — dat is daar het gezegde.' },
  { id: 216, zin: 'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
    vraagWoord: 'heeft gekregen',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In de bijzin staan twee werkwoorden: "heeft gekregen" is samen het gezegde.' },
  { id: 217, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'springen',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het eerste stukje is "springen" het enige werkwoord — dat is daar het gezegde.' },
  { id: 218, zin: 'Wij springen hoog maar hij duikt diep.',
    vraagWoord: 'duikt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het tweede stukje is "duikt" het enige werkwoord — dat is daar het gezegde.' },
  { id: 219, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'schijnt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het eerste stukje is "schijnt" het enige werkwoord — dat is daar het gezegde.' },
  { id: 220, zin: 'De zon schijnt en de vogels zingen vrolijk.',
    vraagWoord: 'zingen',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het tweede stukje is "zingen" het enige werkwoord — dat is daar het gezegde.' },
  { id: 221, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'pak',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het eerste stukje is "pak" het enige werkwoord — dat is daar het gezegde.' },
  { id: 222, zin: 'Ik pak mijn jas want het regent buiten.',
    vraagWoord: 'regent',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het tweede stukje is "regent" het enige werkwoord — dat is daar het gezegde.' },
  { id: 223, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'blijven',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In de hoofdzin is "blijven" het enige werkwoord — dat is daar het gezegde.' },
  { id: 224, zin: 'Wij blijven binnen omdat het hard onweert.',
    vraagWoord: 'onweert',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In de bijzin is "onweert" het enige werkwoord — dat is daar het gezegde.' },
  { id: 225, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'kookt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In de hoofdzin is "kookt" het enige werkwoord — dat is daar het gezegde.' },
  { id: 226, zin: 'Papa kookt het eten terwijl mama de tafel dekt.',
    vraagWoord: 'dekt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In de bijzin is "dekt" het enige werkwoord — dat is daar het gezegde.' },
  { id: 227, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'blaft',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het eerste stukje is "blaft" het enige werkwoord — dat is daar het gezegde.' },
  { id: 228, zin: 'De hond blaft hard maar de kat slaapt rustig.',
    vraagWoord: 'slaapt',
    woordsoort: null,
    zinsdeel:   'gezegde',               uitleg_zd: 'In het tweede stukje is "slaapt" het enige werkwoord — dat is daar het gezegde.' },
]

// Zinnen met twee deelzinnen. De zinsdelen-oefening laat ze alleen zien als
// "ook samengestelde zinnen" aanstaat; elke deelzin heeft dan een eigen
// onderwerp en persoonsvorm om neer te leggen.
export const SAMENGESTELDE_ZINNEN = new Set([
  'Wij springen hoog maar hij duikt diep.',
  'Ze lacht omdat ze een leuk cadeau heeft gekregen.',
  'De zon schijnt en de vogels zingen vrolijk.',
  'Ik pak mijn jas want het regent buiten.',
  'Wij blijven binnen omdat het hard onweert.',
  'Papa kookt het eten terwijl mama de tafel dekt.',
  'De hond blaft hard maar de kat slaapt rustig.',
])

// ── Hulpjes om een zin op woorden te ontleden ──
// Gedeeld door TaalOefenen (woordsoorten) en Zinsdelen (slepen), zodat beide
// exact hetzelfde bepalen welke woorden bij een zinsdeel horen.

export const splitZin = (zin) => zin.split(' ')
export const cleanWoord = (w) => w.replace(/[.,!?;:]$/, '')

// De frase mag een los woord zijn, een aaneengesloten stuk (bijv. "een appel"),
// of een uit elkaar getrokken werkwoordelijk gezegde (bijv. "mogen ... spelen"
// in "Wij mogen buiten spelen") — de woorden worden in volgorde gezocht, niet
// per se naast elkaar. Hoofdletters tellen mee, zodat "de kinderen" niet aan
// het "De" aan het zinsbegin blijft plakken.
export function woordIndexen(zin, frase) {
  const words = splitZin(zin)
  const doel = frase.split(' ')
  const matched = new Set()
  let ti = 0
  for (let i = 0; i < words.length && ti < doel.length; i++) {
    if (cleanWoord(words[i]) === doel[ti] || words[i] === doel[ti]) {
      matched.add(i)
      ti++
    }
  }
  return matched
}

// Welke woorden hóren bij het zinsdeel: het volledige zinsdeel ("De hond"),
// niet alleen het kernwoord ("hond") dat de woordsoorten-modus gebruikt.
export const zinsdeelFrase = (q) => q.zinsdeelWoorden || q.vraagWoord

// ── Hulpteksten ──
// Wat de leerling achter de hulpknop krijgt: geen antwoord, maar de truc om
// het zelf te vinden.

export const TIP_ZINSDEEL = {
  'onderwerp':           'Zoek eerst de persoonsvorm. Vraag dan: wie of wat + persoonsvorm? Bij "De hond blaft hard": wie blaft? De hond — dat is het onderwerp.',
  'persoonsvorm':        'Maak er een vraagzin van: het werkwoord dat dan vooraan springt is de persoonsvorm. Werkt dat niet? Zet de zin in een andere tijd (doe alsof het gisteren gebeurde) — het werkwoord dat meeverandert is de persoonsvorm.',
  'gezegde':             'Zoek alle werkwoorden bij elkaar. De persoonsvorm plus de andere werkwoorden vormen samen het werkwoordelijk gezegde, ook als ze uit elkaar staan: "Wij mogen buiten spelen".',
  'lijdend voorwerp':    'Vraag: wie of wat + persoonsvorm + onderwerp? Bij "Papa koopt twee broden": wat koopt papa? Twee broden — dat is het lijdend voorwerp.',
  'meewerkend voorwerp': 'Vraag: aan wie of voor wie gebeurt het? Je kunt er meestal "aan" voor zetten: (aan) de kinderen.',
  'bepaling':            'Een bepaling vertelt waar, wanneer, hoe, hoe lang of waarmee iets gebeurt. Wat overblijft naast het onderwerp, de persoonsvorm en de voorwerpen is meestal een bepaling.',
}

export const TIP_WOORDSOORT = {
  'lidwoord':              'Er zijn er maar drie: de, het en een.',
  'zelfstandig naamwoord': 'Je kunt er de, het of een voor zetten: (de) hond, (het) park.',
  'werkwoord':             'Iets dat je kunt doen. Zet "ik" ervoor: ik loop, ik koop, ik slaap.',
  'bijvoeglijk naamwoord': 'Het zegt hoe iets is. Pas het in: de ___ auto → de blauwe auto.',
  'bijwoord':              'Het zegt iets over het werkwoord: hoe, wanneer of waar iets gebeurt — snel, gisteren, hard.',
  'voornaamwoord':         'Een woordje in plaats van een naam: ik, jij, hij, zij, wij, mijn, zijn.',
  'voorzetsel':            'De kast-truc: je kunt het voor "de kast" zetten — in, op, onder, naast, door, bij.',
  'telwoord':              'Het zegt hoeveel of de hoeveelste: twee, tien, vijf, eerste.',
  'voegwoord':             'Het verbindt twee stukken zin: en, maar, want, omdat, terwijl.',
}
