// Woordenschat blok 1 — Staal thema 1 "Ik ontmoet", les 2, 7 en 12 (45 begrippen).
//
// `woord`   zoals het in de methode staat (met lidwoord bij zelfstandige naamwoorden)
// `kern`    de vorm die in een zin met een gat past ('interview', niet 'het interview');
//           alleen gezet als die afwijkt van `woord`
// `zin`     voorbeeldzin met ___ op de plek van het woord
// `tegen`   het woord uit deze lijst dat er de tegenstelling van is
// `uitdrukking` true bij uitdrukkingen, zodat afleiders ook uitdrukkingen zijn
//           (anders is "welke past er in de zin" te makkelijk te raden)

export const WOORDEN = [
  // ── Les 2 — Van vlogger tot schipper ──
  { les: 2, woord: 'het interview', kern: 'interview',
    uitleg: 'een gesprek waarbij de één vragen stelt en de ander antwoordt',
    zin: 'De verslaggever hield een ___ met de doelman na de wedstrijd.' },
  { les: 2, woord: 'de geïnterviewde', kern: 'geïnterviewde',
    uitleg: 'degene die antwoord geeft op vragen in een gesprek',
    zin: 'De vragen waren lastig, maar de ___ gaf overal antwoord op.' },
  { les: 2, woord: 'formuleren',
    uitleg: 'iets in woorden zeggen of opschrijven',
    zin: 'Denk eerst even na, dan kun je je vraag beter ___.' },
  { les: 2, woord: 'vastleggen',
    uitleg: 'iets bewaren door het op te schrijven of er een foto of filmpje van te maken',
    zin: 'Met haar camera wilde ze het hele feest ___.' },
  { les: 2, woord: 'onbevangen', tegen: 'bevooroordeeld',
    uitleg: 'als je van tevoren geen mening hebt over iets of iemand',
    zin: 'Hij ging ___ naar zijn nieuwe school: hij wist nog niets van de leraren.' },
  { les: 2, woord: 'bevooroordeeld', tegen: 'onbevangen',
    uitleg: 'als je van tevoren al een mening hebt over iets of iemand',
    zin: 'Ze was ___ over de film, want het boek vond ze al saai.' },
  { les: 2, woord: 'vermoedelijk',
    uitleg: 'waarschijnlijk, als je denkt dat iets zo is',
    zin: 'De trein heeft ___ vertraging door het slechte weer.' },
  { les: 2, woord: 'de waardering', kern: 'waardering',
    uitleg: 'als je iets goed of belangrijk vindt',
    zin: 'Na het optreden kreeg de band veel ___ van het publiek.' },
  { les: 2, woord: 'fascineren',
    uitleg: 'heel erg boeien',
    zin: 'Sterren en planeten kunnen mij enorm ___.' },
  { les: 2, woord: 'veeleisend',
    uitleg: 'als iets veel moeite kost of heel zwaar is',
    zin: 'Turnen is een ___ sport: je traint bijna elke dag.' },
  { les: 2, woord: 'de discipline', kern: 'discipline',
    uitleg: 'als je steeds doet wat moet, ook als je er geen zin in hebt',
    zin: 'Voor topsport heb je veel ___ nodig.' },
  { les: 2, woord: 'resoluut',
    uitleg: 'vastberaden, heel zeker van je zaak',
    zin: 'Hij zei ___ nee en twijfelde geen seconde.' },
  { les: 2, woord: 'achter de schermen', uitdrukking: true,
    uitleg: 'dat wat je normaal niet te zien krijgt',
    zin: 'Op het podium stonden vijf acteurs, maar ___ werkten er wel twintig mensen.' },
  { les: 2, woord: 'op eigen houtje', uitdrukking: true,
    uitleg: 'zonder hulp of toestemming van anderen, zonder anderen te vragen',
    zin: 'Ze ging ___ op onderzoek uit, zonder het aan iemand te vragen.' },
  { les: 2, woord: 'opborrelen',
    uitleg: 'uit het niets naar boven komen',
    zin: 'Bij die oude foto’s voelde ze allerlei herinneringen ___.' },

  // ── Les 7 — Een doosje voor je nachtmerries ──
  { les: 7, woord: 'respecteren', tegen: 'minachten',
    uitleg: 'veel waardering hebben voor iets of iemand',
    zin: 'Je hoeft het niet eens te zijn, maar je moet elkaars mening wel ___.' },
  { les: 7, woord: 'minachten', tegen: 'respecteren',
    uitleg: 'geen enkele waardering hebben voor iets of iemand',
    zin: 'Je mag iemand best anders vinden, maar je moet hem niet ___.' },
  { les: 7, woord: 'weerloos', tegen: 'weerbaar',
    uitleg: 'als je niet tegen iets of iemand op kunt',
    zin: 'Zonder helm en bescherming stond hij ___ tegenover de aanvallers.' },
  { les: 7, woord: 'weerbaar', tegen: 'weerloos',
    uitleg: 'als je je kunt verdedigen tegen iets of iemand',
    zin: 'Op de judoles leer je ___ te worden.' },
  { les: 7, woord: 'afkomstig zijn', kern: 'afkomstig',
    uitleg: 'ergens vandaan komen',
    zin: 'Deze appels zijn ___ uit Zuid-Afrika.' },
  { les: 7, woord: 'de gave', kern: 'gave',
    uitleg: 'het talent',
    zin: 'Zingen gaat haar heel makkelijk af; ze heeft een bijzondere ___.' },
  { les: 7, woord: 'ontroeren',
    uitleg: 'iemands gevoel raken met iets moois of verdrietigs',
    zin: 'Het einde van die film kan je echt ___.' },
  { les: 7, woord: 'beamen',
    uitleg: 'zeggen dat iets klopt of dat je het met iets eens bent',
    zin: 'Iedereen kon ___ dat het een geslaagde dag was.' },
  { les: 7, woord: 'het interieur', kern: 'interieur',
    uitleg: 'de binnenkant van een ruimte',
    zin: 'Het ___ van de nieuwe bibliotheek is licht en modern.' },
  { les: 7, woord: 'eigenaardig',
    uitleg: 'vreemd',
    zin: 'Hij deed ___: hij groette niemand en liep meteen door.' },
  { les: 7, woord: 'uiteraard',
    uitleg: 'natuurlijk',
    zin: 'Je mag ___ meedoen, iedereen is welkom.' },
  { les: 7, woord: 'de invloed', kern: 'invloed',
    uitleg: 'het kunnen veranderen van iets of iemand',
    zin: 'Vrienden hebben veel ___ op wat je leuk vindt.' },
  { les: 7, woord: 'de historie', kern: 'historie',
    uitleg: 'de geschiedenis',
    zin: 'In het museum leer je alles over de ___ van de stad.' },
  { les: 7, woord: 'het hemd van het lijf vragen', kern: 'het hemd van het lijf', uitdrukking: true,
    uitleg: 'heel veel vragen stellen',
    zin: 'Mijn oma vroeg me ___ over mijn nieuwe klas.' },
  { les: 7, woord: 'leven van de wind', kern: 'van de wind leven', uitdrukking: true,
    uitleg: 'je leven leiden zonder geld te verdienen',
    zin: 'Hij werkt niet en verdient niets; hij lijkt wel te ___.' },

  // ── Les 12 — De sport van meneer Stroef ──
  { les: 12, woord: 'de verrijking', kern: 'verrijking', tegen: 'de verarming',
    uitleg: 'dat waar iets of iemand beter van wordt',
    zin: 'De nieuwe speeltuin is een echte ___ voor de wijk.' },
  { les: 12, woord: 'de verarming', kern: 'verarming', tegen: 'de verrijking',
    uitleg: 'dat waar iets of iemand slechter van wordt',
    zin: 'Het kappen van het bos is een ___ van de natuur.' },
  { les: 12, woord: 'openhartig', tegen: 'gesloten',
    uitleg: 'als je makkelijk over jezelf vertelt',
    zin: 'Ze vertelde ___ over haar angst om te verliezen.' },
  { les: 12, woord: 'gesloten', tegen: 'openhartig',
    uitleg: 'als je niet of bijna niet laat merken wat je voelt of vindt',
    zin: 'Hij is nogal ___; je merkt bijna nooit wat hij voelt.' },
  { les: 12, woord: 'indrukwekkend',
    uitleg: 'groot en bijzonder',
    zin: 'De waterval was ___: wel dertig meter hoog.' },
  { les: 12, woord: 'allesbehalve',
    uitleg: 'helemaal niet',
    zin: 'De toets was ___ makkelijk; ik zweette peentjes.' },
  { les: 12, woord: 'hinderen',
    uitleg: 'storen, tot last zijn',
    zin: 'Het lawaai van de bouw kan je flink ___ bij het leren.' },
  { les: 12, woord: 'atletisch',
    uitleg: 'gespierd zoals een atleet',
    zin: 'Met zijn ___ lichaam sprong hij zo over de sloot.' },
  { les: 12, woord: 'het niveau', kern: 'niveau',
    uitleg: 'de kwaliteit van wat je weet of kunt',
    zin: 'Ze speelt tennis op een hoog ___.' },
  { les: 12, woord: 'de beperking', kern: 'beperking',
    uitleg: 'iets wat niet of minder makkelijk kan',
    zin: 'Door zijn ___ kan hij geen trap lopen, maar sporten doet hij wel.' },
  { les: 12, woord: 'de tactiek', kern: 'tactiek',
    uitleg: 'een plan dat je hebt bedacht om een doel te bereiken',
    zin: 'De trainer legde de ___ voor de wedstrijd nog een keer uit.' },
  { les: 12, woord: 'de voldoening', kern: 'voldoening',
    uitleg: 'de tevredenheid',
    zin: 'Het gaf hem veel ___ dat de klus eindelijk gelukt was.' },
  { les: 12, woord: 'bijwonen',
    uitleg: 'erbij zijn',
    zin: 'Mijn ouders komen de voorstelling ___.' },
  { les: 12, woord: 'de spijker op de kop slaan', kern: 'de spijker op de kop', uitdrukking: true,
    uitleg: 'precies zeggen waar het om gaat',
    zin: 'Met die ene opmerking sloeg hij ___.' },
  { les: 12, woord: 'je ogen de kost geven', kern: 'je ogen de kost', uitdrukking: true,
    uitleg: 'alles goed bekijken',
    zin: 'Loop rustig door het museum en geef ___.' },
]

export const kernVan = (w) => w.kern || w.woord
