// Woordenschat blok 2 t/m 8 — Taal actief groep 7, thema 2 t/m 8, week 1-3
// (45 woordkaartjes per blok). Zelfde velden als blok 1 (woordenschatData.js);
// `week` vervangt daar `les`. De betekenis komt van het kaartje, de zinnen
// zijn eigen voorbeeldzinnen.
//
// w(week, woord, uitleg, zin, extra) — bij een zelfstandig naamwoord zonder
// `kern` valt het lidwoord vanzelf weg ('de sfeer' → 'sfeer').

const w = (week, woord, uitleg, zin, extra = {}) => {
  const kern = extra.kern ?? (/^(de|het) /.test(woord) ? woord.replace(/^(de|het) /, '') : undefined)
  return { week, woord, uitleg, zin, ...extra, ...(kern && kern !== woord ? { kern } : {}) }
}
const U = { uitdrukking: true }

const BLOK2 = [
  w(1, 'de sfeer', 'de stemming van een groep mensen of in een ruimte', 'Met lampjes en muziek was de ___ in de klas meteen gezellig.'),
  w(1, 'relaxed', 'fijn, ontspannen', 'Na de laatste toets voelde iedereen zich lekker ___.'),
  w(1, 'knus', 'gezellig', 'Met de kaarsjes aan was het in de kleine hut heel ___.'),
  w(1, 'het succes', 'iets wat gelukt is, iets wat goed is gegaan', 'De schoolmusical was een groot ___: iedereen bleef klappen.', { tegen: 'de mislukking' }),
  w(1, 'de mislukking', 'iets wat niet gelukt is, iets wat fout is gegaan', 'De taart zakte in en werd één grote ___.', { tegen: 'het succes' }),
  w(1, 'centraal', 'in het midden', 'De tafel met eten stond ___ in de zaal, zodat iedereen erbij kon.'),
  w(1, 'zich terugtrekken', 'naar een plek gaan waar geen andere mensen zijn', 'Na het drukke feest wilde Noor zich even ___ in een stil hoekje.', { kern: 'terugtrekken' }),
  w(1, 'weergeven', 'laten zien', 'Deze grafiek moet ___ hoeveel regen er elke maand viel.'),
  w(1, 'desnoods', 'als het echt nodig is', 'We gaan morgen naar het strand, ___ met een regenjas aan.'),
  w(1, 'trachten', 'proberen, ergens je best voor doen', 'De keeper zal ___ de bal tegen te houden.'),
  w(1, 'het ontzag', 'de bewondering', 'Met veel ___ keken de kinderen naar de enorme walvis.'),
  w(1, 'omvatten', 'als inhoud hebben', 'De zwemcursus zal tien lessen ___.'),
  w(1, 'ergens behoefte aan hebben', 'iets nodig hebben of graag willen', 'Na de lange wandeling had iedereen ___ een glas water.', { ...U, kern: 'behoefte aan' }),
  w(1, 'te binnen schieten', 'je plotseling iets herinneren, ineens iets bedenken', 'Ineens schoot het antwoord me ___.', { ...U, kern: 'te binnen' }),
  w(1, 'in harmonie leven', 'goed samenleven', 'De kat en de hond leven thuis ___ met elkaar.', { ...U, kern: 'in harmonie' }),

  w(2, 'likkebaarden', 'je verheugen op iets lekkers', 'Toen oma pannenkoeken bakte, zaten we al te ___.'),
  w(2, 'kokhalzen', 'bijna overgeven', 'Van de vieze geur uit de vuilnisbak moest Sem bijna ___.'),
  w(2, 'uitbundig', 'vrolijk, uitgelaten', 'Na het doelpunt juichten de fans heel ___.', { tegen: 'ingetogen' }),
  w(2, 'ingetogen', 'rustig, bescheiden', 'Tijdens de herdenking was iedereen stil en ___.', { tegen: 'uitbundig' }),
  w(2, 'ondervinden', 'meemaken, merken', 'Op kamp zul je zelf ___ hoe koud een tent ’s nachts is.'),
  w(2, 'dubieus', 'twijfelachtig, vermoedelijk niet goed', 'Die supergoedkope telefoon op internet vond papa erg ___.'),
  w(2, 'charmant', 'aardig en aantrekkelijk', 'De nieuwe buurman is vriendelijk en heel ___.'),
  w(2, 'hooguit', 'niet meer dan', 'De wandeling duurt ___ een halfuur, dus je hoeft geen eten mee.'),
  w(2, 'het effect', 'het gevolg, het resultaat', 'De nieuwe trainer had meteen ___: we wonnen alles.'),
  w(2, 'zwijmelen', 'dromerig denken aan iets fijns', 'Bij dat romantische liedje zat Fleur te ___.'),
  w(2, 'de oase', 'een plek in de woestijn met water, waardoor er planten kunnen groeien', 'Na dagen door het zand zagen de reizigers eindelijk een ___ met palmbomen.'),
  w(2, 'aanhankelijk', 'als je steeds bij iemand wilt zijn', 'Ons nieuwe katje is heel ___: het loopt me overal achterna.'),
  w(2, 'de consequentie', 'het logische gevolg', 'Als je je huiswerk vergeet, is de ___ dat je het na school moet maken.'),
  w(2, 'je neus ergens in steken', 'je ergens mee bemoeien', 'Steek ___ niet overal in, het gaat jou niet aan!', { ...U, kern: 'je neus' }),
  w(2, 'een oogje op iemand hebben', 'verliefd zijn op iemand', 'Iedereen weet dat Daan ___ heeft op Lotte.', { ...U, kern: 'een oogje' }),

  w(3, 'het concert', 'een muziekuitvoering voor publiek', 'De band gaf een ___ in het park voor duizend mensen.'),
  w(3, 'het orkest', 'een groep mensen die muziek maakt op verschillende instrumenten', 'Het ___ speelde met violen, trompetten en een grote trom.'),
  w(3, 'de dirigent', 'de leider van een orkest', 'De ___ zwaaide met het stokje en de muziek begon.'),
  w(3, 'flexibel', 'als je je makkelijk aanpast', 'Onze juf is heel ___: als het regent, verzint ze meteen iets anders.', { tegen: 'star' }),
  w(3, 'star', 'als je je moeilijk aanpast', 'Opa is nogal ___: alles moet precies gaan zoals hij gewend is.', { tegen: 'flexibel' }),
  w(3, 'sidderen', 'heel erg beven van spanning of angst', 'Bij het harde onweer zat de hond te ___ onder de tafel.'),
  w(3, 'de beeldspraak', 'het gebruik van woorden met een figuurlijke betekenis', '“Het regent pijpenstelen” is ___: er vallen geen echte pijpen.'),
  w(3, 'het aspect', 'een onderdeel van iets', 'Geld is maar één ___ van een fijne baan.'),
  w(3, 'de mimiek', 'de bewegingen van je gezicht waarmee je gevoelens uitdrukt', 'Aan de ___ van de clown zag je meteen dat hij verdrietig was.'),
  w(3, 'de pre', 'het voordeel', 'Dat je kunt zwemmen is een ___ als je op een boot wilt werken.'),
  w(3, 'inspelen op', 'reageren op iets', 'Een goede winkel probeert te ___ wat klanten willen.'),
  w(3, 'de kick', 'een prettig gevoel omdat je iets erg leuk vindt', 'Van de hoge achtbaan krijg ik echt een ___.'),
  w(3, 'uit je dak gaan', 'helemaal wild worden van plezier of enthousiasme', 'Bij dit liedje mag je helemaal ___ gaan!', { ...U, kern: 'uit je dak' }),
  w(3, 'de show stelen', 'de meeste aandacht krijgen, het meeste succes hebben', 'Het kleine hondje op het podium stal ___.', { ...U, kern: 'de show' }),
  w(3, 'zich laten meeslepen', 'je gevoelens helemaal laten gaan, heel erg door iets geboeid zijn', 'Bij een spannend boek kun je je helemaal laten ___.', { kern: 'meeslepen' }),
]

const BLOK3 = [
  w(1, 'de recensie', 'een bespreking met informatie en een mening, bijvoorbeeld over een boek, film of restaurant', 'In de krant stond een ___ over de nieuwe film: vier sterren!'),
  w(1, 'analyseren', 'onderzoeken hoe iets precies in elkaar zit', 'De trainer ging de wedstrijd ___ om te zien wat er misging.'),
  w(1, 'interpreteren', 'bedenken hoe iets bedoeld is', 'Je kunt dat berichtje op twee manieren ___.'),
  w(1, 'evalueren', 'iets achteraf bespreken, vaak om ervan te leren', 'Na het schoolreisje gaan we met de klas ___ wat goed ging.'),
  w(1, 'verguizen', 'heel slecht over iemand denken en praten', 'Fans kunnen een speler eerst bewonderen en na één fout ___.', { tegen: 'adoreren' }),
  w(1, 'adoreren', 'heel erg bewonderen', 'Veel kinderen ___ die zanger en hebben posters van hem.', { tegen: 'verguizen' }),
  w(1, 'aansporen', 'proberen iemand iets te laten doen', 'De coach bleef de lopers ___ om nog harder te gaan.'),
  w(1, 'beduusd', 'erg verbaasd, je weet even niet wat je moet zeggen', 'Na de verrassing stond Mila even ___ te kijken.'),
  w(1, 'onderbouwen', 'argumenten geven voor je mening', 'Bij een betoog moet je je mening ___ met goede argumenten.'),
  w(1, 'in het bijzonder', 'vooral', 'Ik hou van dieren, ___ van paarden.', U),
  w(1, 'de stijl', 'de manier waarop iemand iets doet, bijvoorbeeld schrijven of schilderen', 'Aan de ___ zie je meteen dat dit schilderij van Van Gogh is.'),
  w(1, 'volstrekt', 'helemaal, absoluut', 'Dat verhaal over een vliegende koe is ___ onmogelijk.'),
  w(1, 'gebruikelijk', 'gewoonlijk, zoals het meestal gebeurt', 'Op een verjaardag is het ___ dat je de jarige feliciteert.'),
  w(1, 'oog hebben voor iets', 'aandacht hebben voor iets', 'Een goede fotograaf heeft ___ kleine details.', { ...U, kern: 'oog voor' }),
  w(1, 'zo zout heb ik het nog nooit gegeten', 'zoiets raars heb ik nog nooit meegemaakt', 'Een pinguïn in de supermarkt? ___ heb ik het nog nooit gegeten!', { ...U, kern: 'Zo zout' }),

  w(2, 'samenstellen', 'van verschillende dingen één geheel maken', 'Voor het feest mag jij een playlist ___ met je favoriete liedjes.'),
  w(2, 'opdelen', 'iets helemaal in stukken verdelen', 'We gaan de pizza ___ in acht gelijke stukken.'),
  w(2, 'indelen', 'dingen een eigen plek geven', 'De juf gaat de klas ___ in groepjes van vier.'),
  w(2, 'exact', 'precies', 'De trein vertrekt ___ om 8.14 uur, geen minuut later.', { tegen: 'ruwweg' }),
  w(2, 'ruwweg', 'ongeveer', 'Er stonden ___ duizend mensen op het plein, misschien iets meer.', { tegen: 'exact' }),
  w(2, 'zowaar', 'onverwacht, terwijl je het niet had verwacht', 'Na drie dagen regen scheen ___ de zon!'),
  w(2, 'puntsgewijs', 'punt voor punt', 'Zet de regels ___ onder elkaar, dan is het overzichtelijk.'),
  w(2, 'evenmin', 'ook niet', 'Lars houdt niet van spinazie en zijn zus ___.'),
  w(2, 'beschouwen als', 'op een bepaalde manier zien of voelen', 'Wij ___ onze hond als een echt lid van de familie.', { kern: 'beschouwen' }),
  w(2, 'de graffiti', 'tekeningen of korte teksten die met verf op bijvoorbeeld een muur zijn gespoten', 'Op de muur van het station stond kleurrijke ___.'),
  w(2, 'ongunstig', 'in je nadeel', 'Met harde tegenwind is het weer ___ voor een fietstocht.'),
  w(2, 'de talkshow', 'een tv-programma waarin mensen over een onderwerp praten, een praatprogramma', 'Gisteravond zat de schrijver aan tafel bij een ___ op tv.'),
  w(2, 'keuren', 'iets of iemand zorgvuldig onderzoeken en beoordelen', 'De dierenarts gaat de paarden ___ voor de wedstrijd.'),
  w(2, 'in één oogopslag', 'vrijwel meteen', 'Met deze kaart zie je ___ waar de uitgang is.', U),
  w(2, 'binnen de kortste keren', 'al heel gauw', 'De ijsjes waren ___ uitverkocht.', U),

  w(3, 'inventief', 'als je goed bent in het bedenken van oplossingen', 'Van een doos en een touw maakte Ravi een lift voor zijn knuffels, zo ___ is hij.'),
  w(3, 'innovatief', 'als je goed bent in het bedenken van nieuwe ideeën', 'Dat bedrijf is heel ___: het bouwde de eerste fiets die zelf remt.'),
  w(3, 'functioneel', 'geschikt voor het doel', 'Deze jas is niet mooi, maar wel ___: hij houdt je droog.'),
  w(3, 'statisch', 'niet in beweging', 'Een foto is ___, een filmpje beweegt.', { tegen: 'dynamisch' }),
  w(3, 'dynamisch', 'steeds in beweging', 'Een voetbalwedstrijd is heel ___: alles is steeds in beweging.', { tegen: 'statisch' }),
  w(3, 'grondig', 'heel erg goed, zonder iets over te slaan', 'Voordat de logés kwamen, maakten we het huis ___ schoon.'),
  w(3, 'behoedzaam', 'voorzichtig', 'De kat sloop ___ over het smalle muurtje.'),
  w(3, 'observeren', 'iets lang en met veel aandacht bekijken', 'Met een verrekijker kun je vogels ___ zonder ze te storen.'),
  w(3, 'de afwerking', 'de manier waarop iets afgemaakt is', 'De kast is mooi, maar de ___ van de randen is slordig.'),
  w(3, 'daarentegen', 'maar, integendeel', 'Mijn broer houdt van voetbal, ik ___ van tekenen.'),
  w(3, 'de bravoure', 'de durf, het lef', 'Met veel ___ sprong ze van de hoogste duikplank.'),
  w(3, 'monteren', 'iets in elkaar zetten, bijvoorbeeld met schroeven of lijm', 'Papa ging de nieuwe kast ___ met een schroevendraaier.'),
  w(3, 'de constructie', 'de manier waarop iets in elkaar gezet is', 'De ___ van deze brug is zo sterk dat er vrachtwagens over kunnen.'),
  w(3, 'van heinde en verre', 'overal vandaan', 'Voor het festival kwamen mensen ___.', U),
  w(3, 'op je dooie gemak', 'rustig aan, zonder haast', 'Je hoeft niet te rennen, loop maar ___.', U),
]

const BLOK4 = [
  w(1, 'bewijzen', 'duidelijk maken dat iets waar is', 'Met dit filmpje kan ik ___ dat ik de bal echt raakte.', { tegen: 'weerleggen' }),
  w(1, 'weerleggen', 'duidelijk maken dat iets niet waar is', 'Met een foto van de klok kon Jesse het verhaal ___: hij was wél op tijd.', { tegen: 'bewijzen' }),
  w(1, 'ten koste van', 'ergens nadeel van hebben', 'De wedstrijd werd gewonnen, maar ___ een gebroken arm.', { ...U, tegen: 'ten bate van' }),
  w(1, 'ten bate van', 'ergens voordeel van hebben', 'De sponsorloop is ___ het dierenasiel.', { ...U, tegen: 'ten koste van' }),
  w(1, 'de smaakpapil', 'een klein bobbeltje op je tong waarmee je kunt proeven', 'Met elke ___ op je tong proef je iets.'),
  w(1, 'de creativiteit', 'het talent om mooie of nieuwe dingen te bedenken of te maken', 'Bij de knutselwedstrijd kon je je ___ helemaal kwijt.'),
  w(1, 'de asperge', 'de (witte) stengel van een plant die je kunt eten', 'Papa schilde de dikke witte ___ voor het avondeten.'),
  w(1, 'serveren', 'eten of drinken op een gedekte tafel zetten', 'De ober kwam de soep ___.'),
  w(1, 'zich tegoed doen aan', 'ergens heel erg van genieten', 'Op het feest deden de kinderen zich ___ aan de taart.', { kern: 'tegoed' }),
  w(1, 'voedzaam', 'met veel voedingsstoffen erin, goed voedend', 'Havermout is heel ___: je zit er lang vol van.'),
  w(1, 'aanprijzen', 'zeggen dat iets of iemand goed is', 'Op de markt hoorde je de verkopers hun groente ___.'),
  w(1, 'met name', 'vooral', 'Ik hou van fruit, ___ van aardbeien.', U),
  w(1, 'royaal', 'ruim, groot', 'De hotelkamer was ___: er pasten wel vier bedden in.'),
  w(1, 'voor geen goud', 'absoluut niet', 'In die enge achtbaan ga ik ___!', U),
  w(1, 'voor elk wat wils', 'als er voor iedereen iets bijzit, als iedereen er iets van wil', 'Op de markt is er ___: kleding, eten en speelgoed.', U),

  w(2, 'het aanbod', 'iets wat je van iets of iemand kunt krijgen', 'Het ___ van deze winkel is groot: je vindt er alles.'),
  w(2, 'accepteren', 'je zegt ja tegen iets, je vindt het goed', 'Ik wil je uitnodiging graag ___.', { tegen: 'verwerpen' }),
  w(2, 'verwerpen', 'je zegt nee tegen iets, je vindt het niet goed', 'De klas besloot het plan te ___: niemand wilde het.', { tegen: 'accepteren' }),
  w(2, 'het voornemen', 'iets wat je wilt gaan doen', 'Mijn ___ voor dit jaar is elke dag te lezen.'),
  w(2, 'realiseren', 'uitvoeren', 'Met genoeg geld kan de school het nieuwe speelplein ___.'),
  w(2, 'dikwijls', 'vaak', 'In de winter is het ___ glad op de weg.'),
  w(2, 'het risico', 'de kans dat er iets vervelends met iets of iemand gebeurt', 'Als je zonder helm skatet, loop je het ___ dat je je hoofd stoot.'),
  w(2, 'de variant', 'iets wat lijkt op iets anders, maar net niet helemaal hetzelfde is', 'Deze pizza is een ___ op de margherita, met extra kaas.'),
  w(2, 'ruig', 'wild', 'De zee was ___ met hoge golven.'),
  w(2, 'duizelingwekkend', 'zo groot of veel dat je er duizelig van wordt', 'De wolkenkrabber was ___ hoog.'),
  w(2, 'zich bewust zijn van', 'weten dat iets zo is', 'Ben je je ___ van het gevaar?', { kern: 'bewust' }),
  w(2, 'zinvol', 'nuttig, als iets zin heeft', 'Het is ___ om voor een toets te oefenen.'),
  w(2, 'krampachtig', 'veel steviger dan nodig is', 'Ze hield het stuur ___ vast, bang om te vallen.'),
  w(2, 'iets onder de knie hebben', 'weten hoe iets moet en het kunnen', 'Na veel oefenen heb ik de handstand eindelijk ___.', { ...U, kern: 'onder de knie' }),
  w(2, 'door het oog van de naald kruipen', 'nog maar net aan een gevaar ontsnappen', 'De fietser kon nog net remmen: hij kroop ___.', { ...U, kern: 'door het oog van de naald' }),

  w(3, 'de opbrengst', 'het geldbedrag dat de verkoop van iets oplevert', 'De ___ van de rommelmarkt was tweehonderd euro.'),
  w(3, 'de donatie', 'geld of voorwerpen die je geeft, bijvoorbeeld voor een goed doel', 'Met jouw ___ kan het asiel nieuw voer kopen.'),
  w(3, 'importeren', 'iets in je eigen land brengen vanuit een ander land', 'Nederland moet bananen ___, want die groeien hier niet.', { tegen: 'exporteren' }),
  w(3, 'exporteren', 'iets naar een ander land brengen vanuit je eigen land', 'Nederlandse kwekers ___ veel tulpen naar andere landen.', { tegen: 'importeren' }),
  w(3, 'aangezien', 'omdat', 'We blijven binnen, ___ het hard regent.'),
  w(3, 'de expositie', 'een uitstalling van kunstwerken of bijzondere voorwerpen', 'In het museum is een ___ met oude robots.'),
  w(3, 'de criticus', 'iemand die in de krant of op internet zijn mening geeft over nieuwe films, boeken of tentoonstellingen', 'De ___ schreef in de krant dat de film saai was.'),
  w(3, 'het object', 'het voorwerp, het ding', 'Op tafel lag een vreemd ___ dat niemand herkende.'),
  w(3, 'anoniem', 'zonder naam', 'De brief was ___: er stond geen naam onder.'),
  w(3, 'hedendaags', 'van nu, van deze tijd', 'Deze muziek is niet oud, maar ___.'),
  w(3, 'beletten', 'iemand tegenhouden om iets te doen', 'Een beetje regen zal ons niet ___ om te gaan wandelen.'),
  w(3, 'bespotten', 'iets of iemand belachelijk maken', 'Het is gemeen om iemand te ___ omdat die anders praat.'),
  w(3, 'de rage', 'iets dat op een bepaald moment heel erg in de mode is', 'Vorig jaar was het een ___ op school: iedereen had een fidget spinner.'),
  w(3, 'het gezicht staat op onweer', 'heel boos kijken', 'Na het verlies stond het gezicht van de trainer ___.', { ...U, kern: 'op onweer' }),
  w(3, 'tot in lengte van dagen', 'nog heel lang', 'En ze leefden nog gelukkig ___.', U),
]

const BLOK5 = [
  w(1, 'stemmen', 'laten weten of je voor of tegen iets bent', 'Morgen gaan we in de klas ___ over het uitje.'),
  w(1, 'de meerderheid', 'de grootste groep van het geheel', 'De ___ van de klas wilde naar de dierentuin.', { tegen: 'de minderheid' }),
  w(1, 'de minderheid', 'de kleinste groep van het geheel', 'Maar een kleine ___ wilde liever naar het zwembad.', { tegen: 'de meerderheid' }),
  w(1, 'doeltreffend', 'als iets het doel heeft bereikt', 'Het nieuwe slot is ___: er is nooit meer een fiets gestolen.', { tegen: 'ineffectief' }),
  w(1, 'ineffectief', 'als iets het doel niet heeft bereikt', 'De muggenspray bleek ___: ik zat toch vol bulten.', { tegen: 'doeltreffend' }),
  w(1, 'soortgelijk', 'van dezelfde soort, ongeveer hetzelfde', 'Mijn fiets lijkt op die van jou, het is een ___ model.'),
  w(1, 'et cetera', 'enzovoort', 'In de tas zitten boeken, pennen, schriften, ___.'),
  w(1, 'ergens op teren', 'het ergens mee doen, van iets leven', 'Het team kan nog lang ___ op die ene grote overwinning.', { kern: 'teren' }),
  w(1, 'verzadigd', 'als je genoeg hebt gehad', 'Na drie borden pasta was ik helemaal ___.'),
  w(1, 'het nageslacht', 'kinderen, kleinkinderen, kinderen van kleinkinderen, enzovoort', 'De oude eik moet blijven staan voor het ___.'),
  w(1, 'de suggestie', 'een voorstel', 'Heeft iemand een goede ___ voor de naam van de klassenhamster?'),
  w(1, 'bevorderen', 'vooruithelpen, zorgen dat iets beter gaat', 'Samen spelen kan de vriendschap ___.'),
  w(1, 'voorleggen', 'iemand om zijn mening vragen over iets', 'Ik ga het plan eerst aan de juf ___.'),
  w(1, 'je borst natmaken', 'je voorbereiden op iets wat moeilijk of niet zo prettig zal zijn', 'Morgen is de grote toets, dus maak ___!', { ...U, kern: 'je borst maar nat' }),
  w(1, 'iets voor de boeg hebben', 'nog werk te doen hebben, nog iets mee moeten maken', 'We hebben nog een lange reis ___.', { ...U, kern: 'voor de boeg' }),

  w(2, 'de voorzitter', 'het hoofd van het bestuur, degene die de vergaderingen leidt', 'De ___ opende de vergadering met een klap van de hamer.'),
  w(2, 'de secretaris', 'iemand die alle communicatie verzorgt voor het bestuur', 'De ___ stuurde alle leden een mail over de vergadering.'),
  w(2, 'de penningmeester', 'degene in het bestuur die alles regelt wat met geld te maken heeft', 'De ___ telde hoeveel geld er in de clubkas zat.'),
  w(2, 'abrupt', 'heel plotseling', 'De muziek stopte ___ toen de stroom uitviel.'),
  w(2, 'gaandeweg', 'na enige tijd, geleidelijk', 'Eerst vond ik de film saai, maar ___ werd hij spannender.'),
  w(2, 'veelzeggend', 'met een duidelijke bedoeling of betekenis', 'Mama keek ___ naar de rommel in mijn kamer.'),
  w(2, 'de getuige', 'iemand die aanwezig is of was bij een gebeurtenis', 'De ___ vertelde de politie wat ze had gezien.'),
  w(2, 'de wethouder', 'iemand die samen met de burgemeester een gemeente bestuurt', 'De ___ opende samen met de burgemeester het nieuwe zwembad.'),
  w(2, 'de gemeenteraad', 'de mensen die namens de inwoners beslissen wat er gebeurt in een gemeente', 'De ___ besliste dat er een nieuw park komt.'),
  w(2, 'de aanstelling', 'een bepaalde baan of functie', 'Na het gesprek kreeg de nieuwe juf haar ___ op onze school.'),
  w(2, 'de notulen', 'een geschreven verslag van wat er is gezegd in een vergadering', 'In de ___ kun je teruglezen wat er op de vergadering is gezegd.'),
  w(2, 'ontruimen', 'leegmaken', 'Bij brandalarm moeten we het gebouw snel ___.'),
  w(2, 'de sensatie', 'grote opwinding of opschudding', 'De ontsnapte giraffe zorgde voor veel ___ in de stad.'),
  w(2, 'van de baan zijn', 'niet doorgaan', 'Door de storm is het schoolreisje ___.', { ...U, kern: 'van de baan' }),
  w(2, 'met je neus in de boter vallen', 'precies op het goede moment komen, onverwachts veel geluk hebben', 'Je komt net binnen als de taart wordt aangesneden: je valt ___!', { ...U, kern: 'met je neus in de boter' }),

  w(3, 'democratisch', 'als iedereen mag meebeslissen', 'In onze klas gaat het ___: iedereen mag meebeslissen.'),
  w(3, 'de verkiezing', 'het kiezen van iets of iemand door te stemmen', 'Bij de ___ voor de leerlingenraad kreeg Yara de meeste stemmen.'),
  w(3, 'het stemrecht', 'het recht om te mogen stemmen', 'Vanaf achttien jaar heb je in Nederland ___.'),
  w(3, 'de inspraak', 'de mogelijkheid om je mening te geven', 'De kinderen kregen ___ over het nieuwe schoolplein.'),
  w(3, 'een verzoek afwijzen', 'bij een vraag (of iemand iets mag doen) zeggen dat het niet mag', 'De juf zei nee: ze moest ons verzoek om vrij te krijgen ___.', { kern: 'afwijzen', tegen: 'toestemming verlenen' }),
  w(3, 'toestemming verlenen', 'zeggen dat het mag', 'De ouders moeten toestemming ___ voor het kamp.', { kern: 'verlenen', tegen: 'een verzoek afwijzen' }),
  w(3, 'het alternatief', 'een andere goede mogelijkheid', 'Als het regent, is de bioscoop een goed ___.'),
  w(3, 'inschakelen', 'erbij halen, te hulp roepen', 'Bij een lekkage moet je een loodgieter ___.'),
  w(3, 'massaal', 'heel groot of met heel veel', 'De kinderen kwamen ___ naar de opening van het speelplein.'),
  w(3, 'huidig', 'van nu', 'Wie is de ___ wereldkampioen schaken?', { kern: 'huidige' }),
  w(3, 'afzonderlijk', 'los van elkaar, apart', 'De juf sprak de kinderen ___: één voor één.'),
  w(3, 'gelet op', 'rekening houdend met', 'We gaan niet zwemmen, ___ de koude regen.', U),
  w(3, 'de discussie', 'een gesprek waarbij mensen verschillende meningen hebben', 'Er ontstond een ___ over welke film we gingen kijken.'),
  w(3, 'geen overbodige luxe', 'hard nodig', 'Met dit weer is een regenjas ___.', U),
  w(3, 'ergens je tanden in zetten', 'met volle inzet aan een groot karwei beginnen', 'Dit is een flinke klus, daar kun je ___ zetten.', { ...U, kern: 'je tanden in' }),
]

const BLOK6 = [
  w(1, 'raadplegen', 'iets opzoeken, bijvoorbeeld in een boek of op internet', 'Als je een woord niet kent, kun je een woordenboek ___.'),
  w(1, 'selecteren', 'kiezen, uitzoeken', 'De trainer gaat elf spelers ___ voor de finale.'),
  w(1, 'vergaren', 'verzamelen', 'Voor je werkstuk moet je eerst informatie ___.'),
  w(1, 'de identiteit', 'alles wat jou maakt tot wie je bent: je karakter, maar bijvoorbeeld ook je geboortedatum en woonplaats', 'Met je paspoort kun je je ___ laten zien.'),
  w(1, 'de persoonlijkheid', 'het karakter, de opvallende eigenschappen van iemand', 'Ze heeft een vrolijke ___: ze lacht altijd.'),
  w(1, 'de burgerlijke staat', 'of je getrouwd, ongetrouwd of gescheiden bent', 'Op het formulier moest oma haar ___ invullen: weduwe.'),
  w(1, 'de nationaliteit', 'het behoren tot een bepaald land volgens je paspoort', 'Lucas is in Spanje geboren, maar heeft de Nederlandse ___.'),
  w(1, 'het archief', 'een plek waar belangrijke papieren worden bewaard', 'In het ___ van de gemeente liggen papieren van honderd jaar oud.'),
  w(1, 'de bloedverwant', 'iemand die familie van je is', 'Mijn neef is een ___ van me, mijn buurman niet.'),
  w(1, 'regeren', 'een land besturen', 'Vroeger mocht de koning het hele land ___.'),
  w(1, 'de adel', 'groep mensen uit rijke en belangrijke families die vroeger meer rechten hadden dan anderen', 'Graven en baronnen hoorden vroeger bij de ___.'),
  w(1, 'de carrière', 'de reeks banen die iemand achter elkaar heeft gehad', 'Na een lange ___ als keeper stopte hij met voetballen.'),
  w(1, 'afhankelijk van', 'bepaald door', 'Of we buiten gymmen, is ___ het weer.', U),
  w(1, 'de tijd zal het leren', 'als je rustig afwacht, zul je wel zien hoe het loopt', 'Of het plan werkt, weet ik nog niet: ___.', { ...U, kern: 'de tijd zal het leren' }),
  w(1, 'met de gebakken peren zitten', 'te maken hebben met de vervelende gevolgen van iets', 'Jij maakte de rommel en nu zit ik ___!', { ...U, kern: 'met de gebakken peren' }),

  w(2, 'de vedette', 'iemand die erg populair is vanwege prestaties in sport, zang of film', 'De ___ van het team scoorde drie keer.'),
  w(2, 'de aanhang', 'fans, volgers', 'De zanger heeft een grote ___ die bij elk concert staat.'),
  w(2, 'vermaard', 'beroemd', 'Deze bakker is ___ om zijn appeltaart.'),
  w(2, 'furore maken', 'heel bekend en populair worden', 'Dat nieuwe dansje maakte ___ op internet.', { kern: 'furore' }),
  w(2, 'ergens lyrisch over zijn', 'iets fantastisch vinden', 'Na de film was iedereen ___ over de effecten.', { kern: 'lyrisch', tegen: 'ergens van walgen' }),
  w(2, 'ergens van walgen', 'iets afschuwelijk vinden', 'Veel mensen ___ van slijmerige slakken.', { kern: 'walgen', tegen: 'ergens lyrisch over zijn' }),
  w(2, 'gedurende', 'tijdens, zo lang als iets duurt', 'Je telefoon blijft in je tas ___ de hele les.'),
  w(2, 'komisch', 'grappig, om te lachen', 'De clown was zo ___ dat iedereen lag te lachen.'),
  w(2, 'het meesterwerk', 'een heel mooi kunstwerk, bijvoorbeeld een schilderij, boek of film', 'De Nachtwacht van Rembrandt is een echt ___.'),
  w(2, 'de regisseur', 'iemand die de leiding heeft bij het maken van een film, toneelstuk of tv-programma', 'De ___ riep “Actie!” en de acteurs begonnen.'),
  w(2, 'de concurrentie', 'anderen die hetzelfde doen als jij en proberen beter te zijn', 'De nieuwe bakker heeft veel ___ van de supermarkt.'),
  w(2, 'in het openbaar', 'op plekken waar iedereen mag komen', 'De burgemeester sprak ___ op het marktplein.', U),
  w(2, 'assisteren', 'iemand helpen bij zijn of haar werk', 'De verpleger gaat de dokter ___ bij de operatie.'),
  w(2, 'het gaat van kwaad tot erger', 'het wordt steeds slechter', 'Eerst lekte het dak, toen viel de stroom uit: het ging ___.', { ...U, kern: 'van kwaad tot erger' }),
  w(2, 'leven in de brouwerij brengen', 'zorgen voor drukte en vrolijkheid', 'De nieuwe puppy bracht meteen ___.', { ...U, kern: 'leven in de brouwerij' }),

  w(3, 'citeren', 'een uitspraak van een ander in precies dezelfde woorden herhalen', 'In je werkstuk mag je een zin uit het boek ___ tussen aanhalingstekens.'),
  w(3, 'parafraseren', 'een uitspraak van een ander in eigen woorden navertellen', 'Je hoeft het niet woord voor woord over te nemen, je mag het ook ___.'),
  w(3, 'de parafrase', 'een uitspraak van een ander in eigen woorden naverteld', 'Schrijf een korte ___ van wat de schrijver bedoelt.'),
  w(3, 'verzwijgen', 'met opzet niet zeggen, geheimhouden', 'Bram probeerde te ___ dat hij de vaas had gebroken.', { tegen: 'onthullen' }),
  w(3, 'onthullen', 'vertellen, bekendmaken', 'Aan het eind van de film gaat de detective ___ wie de dief is.', { tegen: 'verzwijgen' }),
  w(3, 'de filosoof', 'iemand die voor zijn beroep nadenkt over de vragen van het leven', 'De ___ dacht lang na over de vraag: wat is geluk?'),
  w(3, 'de wetenschap', 'kennis die door geleerde mensen is ontdekt en verzameld, zoals wiskunde en biologie', 'Dankzij de ___ weten we hoe ver de maan van de aarde staat.'),
  w(3, 'aanspreken', 'in de smaak vallen', 'Dat boek kan mij wel ___: het gaat over draken.'),
  w(3, 'de oorsprong', 'het punt waar iets begint, waar iets vandaan komt', 'De ___ van de rivier ligt hoog in de bergen.'),
  w(3, 'eigentijds', 'passend bij deze tijd, modern', 'Het oude huis is vanbinnen heel ___ ingericht.'),
  w(3, 'denkbeeldig', 'als iets alleen in je gedachten bestaat en niet in het echt', 'Mijn kleine zusje heeft een ___ vriendje.'),
  w(3, 'de politicus', 'iemand die in het bestuur zit van een land, provincie of stad', 'De ___ hield een toespraak in de Tweede Kamer.'),
  w(3, 'zich als een olievlek verspreiden', 'heel snel meer of groter worden', 'Het nieuws verspreidde zich ___ door de school.', { ...U, kern: 'als een olievlek' }),
  w(3, 'iets haarfijn aanvoelen', 'meteen begrijpen wat er precies aan de hand is', 'Mijn moeder voelt ___ aan wanneer ik verdrietig ben.', { kern: 'haarfijn' }),
  w(3, 'in grote lijnen', 'ongeveer, wat de hoofdzaken betreft', 'Vertel ___ waar het boek over gaat, niet alle details.', U),
]

const BLOK7 = [
  w(1, 'de werktekening', 'een tekening waarop staat hoe iets in elkaar zit of gemaakt moet worden', 'Op de ___ staat precies hoe je de vogelkast in elkaar zet.'),
  w(1, 'het bovenaanzicht', 'zoals het er van bovenaf uitziet', 'Op het ___ van het huis zie je alleen het dak.'),
  w(1, 'het formaat', 'de maat van iets', 'Deze doos heeft het ___ van een schoenendoos.'),
  w(1, 'de dwarsdoorsnede', 'het vlak waarlangs iets doormidden is gesneden', 'Op de ___ van de boomstam zie je alle jaarringen.'),
  w(1, 'de consument', 'iemand die artikelen koopt of gebruikt', 'De ___ koopt het brood in de winkel.', { tegen: 'de producent' }),
  w(1, 'de producent', 'iemand die een product maakt om het te verkopen', 'De ___ van deze chocolade heeft een fabriek in België.', { tegen: 'de consument' }),
  w(1, 'overwinteren', 'ergens de winter doorbrengen', 'Veel ooievaars gaan in Afrika ___.'),
  w(1, 'gammel', 'niet stevig in elkaar zittend', 'De oude stoel was zo ___ dat hij bijna in elkaar zakte.'),
  w(1, 'achtereenvolgens', 'na elkaar komend, in volgorde', 'De lopers kwamen ___ binnen: eerst Tim, toen Sara, toen Bo.'),
  w(1, 'secuur', 'precies en zorgvuldig', 'Bij het knippen van de rand moet je heel ___ werken.'),
  w(1, 'construeren', 'in elkaar zetten', 'Met lego kun je een hele brug ___.'),
  w(1, 'het scharnier', 'een verbindingsstuk tussen twee delen, zodat één deel open en dicht kan', 'Het ___ van de deur piepte, dus papa deed er olie op.'),
  w(1, 'het geklungel', 'niet handig bezig zijn', 'Na een kwartier ___ zat de band eindelijk om het wiel.'),
  w(1, 'iets achter de hand hebben', 'iets bewaren voor als je het nodig hebt', 'Neem een extra pen mee, dan heb je er een ___.', { ...U, kern: 'achter de hand' }),
  w(1, 'zo op het oog', 'vluchtig bekeken', 'De appel lijkt ___ gaaf, maar binnenin zit een worm.', U),

  w(2, 'de omtrek', 'de buitenste lijn die je meet', 'Voor het hek meet je de ___ van de tuin.'),
  w(2, 'de oppervlakte', 'de maat die je krijgt als je binnenin meet, de lengte keer de breedte', 'Om te weten hoeveel tegels je nodig hebt, reken je de ___ van de vloer uit.'),
  w(2, 'het vlak', 'een vorm met rechte lijnen, bijvoorbeeld een vierkant', 'Elk ___ van een dobbelsteen is een vierkant.'),
  w(2, 'de figuur', 'een vrije vorm of een afbeelding van een mens, dier of ding', 'Op de muur stond een ___ van een man met een hoed.'),
  w(2, 'het patroon', 'een versiering van vormen die zich herhalen', 'Op het behang zit een ___ van steeds dezelfde bloemetjes.'),
  w(2, 'luguber', 'zo eng dat je ervan griezelt', 'Het verlaten huis zag er in het donker heel ___ uit.'),
  w(2, 'transpireren', 'zweten', 'Na het hardlopen begon ik flink te ___.'),
  w(2, 'primaire kleuren', 'de kleuren rood, geel en blauw', 'Rood, geel en blauw noem je de ___.'),
  w(2, 'variëren', 'afwisselen', 'Op de menukaart ___ de gerechten elke week.'),
  w(2, 'continu', 'zonder onderbreking, de hele tijd', 'De baby huilde ___ en sliep de hele nacht niet.'),
  w(2, 'mits', 'alleen op voorwaarde dat', 'Je mag buiten spelen, ___ je om zes uur thuis bent.'),
  w(2, 'de decoratie', 'de versiering', 'Voor het feest hingen we slingers en ballonnen als ___.'),
  w(2, 'beseffen', 'in de gaten hebben', 'Pas later ging ik ___ hoe gevaarlijk dat was.'),
  w(2, 'stalen zenuwen hebben', 'niet snel nerveus worden', 'Bij de strafschoppen had de keeper ___.', { ...U, kern: 'stalen zenuwen' }),
  w(2, 'iets onder handen nemen', 'iets aanpakken', 'Zaterdag gaan we de rommelige schuur ___ nemen.', { ...U, kern: 'onder handen' }),

  w(3, 'het concept', 'een plan van iets wat je wilt maken', 'Het ___ voor de nieuwe app is klaar, nu moet hij nog gebouwd worden.'),
  w(3, 'de toepasbaarheid', 'de manier waarop je iets kunt gebruiken', 'De ___ van dit gereedschap is groot: je kunt er bijna alles mee.'),
  w(3, 'het patent', 'het bewijs dat jij het recht hebt om als enige een product te maken of te verkopen', 'De uitvinder kreeg een ___ op zijn opvouwbare fiets.'),
  w(3, 'de schaarste', 'het tekort aan iets', 'Door de droogte was er ___ aan water.', { tegen: 'de overvloed' }),
  w(3, 'de overvloed', 'een zeer grote hoeveelheid van iets', 'Na de oogst was er een ___ aan appels.', { tegen: 'de schaarste' }),
  w(3, 'het gemis', 'het ontbreken van iets of iemand die je nodig hebt', 'Na de verhuizing voelde ik het ___ van mijn vrienden.'),
  w(3, 'het overschot', 'wat nog over is', 'Het ___ van de soep gaat in de vriezer.'),
  w(3, 'frequent', 'vaak, op veel momenten, veel keren', 'De bus rijdt hier ___: elke vijf minuten.'),
  w(3, 'het ommetje', 'een korte wandeling', 'Na het eten maakten we een ___ door het park.'),
  w(3, 'de eenzaamheid', 'het gevoel dat je alleen bent', 'Sinds oma er niet meer is, voelt opa veel ___.'),
  w(3, 'luidruchtig', 'met veel lawaai', 'De klas was zo ___ dat niemand de juf nog hoorde.'),
  w(3, 'omstreeks', 'rond die tijd', 'We komen ___ zes uur thuis.'),
  w(3, 'multifunctioneel', 'als je er veel verschillende dingen mee kunt doen', 'Een zakmes is ___: je kunt er snijden, schroeven en blikjes mee openen.'),
  w(3, 'om de haverklap', 'iedere keer weer', 'Mijn broertje vraagt ___ of we er al zijn.', U),
  w(3, 'ergens voor opdraaien', 'iets moeten doen, ergens de schuld van krijgen', 'Zij maakten de rommel, maar wij moesten ervoor ___.', { kern: 'opdraaien' }),
]

const BLOK8 = [
  w(1, 'het perspectief', 'vanuit welke plaats of persoon je een gebeurtenis bekijkt', 'Het verhaal is geschreven vanuit het ___ van de hond.'),
  w(1, 'zich inleven', 'zich voorstellen hoe het is om iemand anders, of in een andere situatie, te zijn', 'Een goede acteur kan zich helemaal ___ in de rol.', { kern: 'inleven' }),
  w(1, 'de reflectie', 'het nadenken, de overweging', 'Na het project schreven we een korte ___ over wat we geleerd hadden.'),
  w(1, 'ontkennen', 'zeggen dat iets niet waar is', 'De verdachte bleef ___ dat hij het gestolen had.', { tegen: 'bevestigen' }),
  w(1, 'bevestigen', 'zeggen dat iets klopt', 'De juf kon ___ dat de toets echt morgen is.', { tegen: 'ontkennen' }),
  w(1, 'afdwalen', 'ongemerkt ergens anders over gaan praten of aan iets anders gaan denken', 'Tijdens het lange verhaal ging ik met mijn gedachten ___.'),
  w(1, 'opwindend', 'spannend, boeiend', 'De finale was zo ___ dat niemand stil kon zitten.'),
  w(1, 'de indringer', 'iemand die met geweld of met een list ergens binnenkomt waar hij of zij niet mag zijn', 'De hond blafte naar de ___ in de tuin.'),
  w(1, 'neuzen', 'zoeken zonder dat je precies weet wat je zoekt', 'In de boekwinkel kun je urenlang ___ tussen de boeken.'),
  w(1, 'ondervragen', 'vragen stellen over een misdaad of ongeluk', 'De agent ging de getuigen ___ over het ongeluk.'),
  w(1, 'de taakstraf', 'een straf die bestaat uit een aantal uren werken, in plaats van een boete betalen of naar de gevangenis gaan', 'Als ___ moest de dader twintig uur afval prikken in het park.'),
  w(1, 'herhaaldelijk', 'meerdere keren', 'De juf heeft ___ gezegd dat je je naam op je werk moet zetten.'),
  w(1, 'de wijkagent', 'een politieagent die het contact onderhoudt met de bewoners in een bepaalde wijk of buurt', 'De ___ kent bijna alle mensen in onze buurt.'),
  w(1, 'aan de aandacht ontsnappen', 'onopgemerkt zijn', 'Die kleine fout was ___ ontsnapt.', { ...U, kern: 'aan de aandacht' }),
  w(1, 'bij de les blijven', 'op blijven letten', 'Het is een lang verhaal, dus probeer ___ te blijven.', { ...U, kern: 'bij de les' }),

  w(2, 'zich bevinden', 'ergens zijn', 'De sleutels moeten zich ergens in deze la ___.', { kern: 'bevinden' }),
  w(2, 'zich begeven naar', 'ergens naartoe gaan', 'Alle reizigers moeten zich nu naar de uitgang ___.', { kern: 'begeven' }),
  w(2, 'arriveren', 'ergens aankomen', 'De trein zal om tien uur in Utrecht ___.'),
  w(2, 'koesteren', 'iets of iemand met liefde behandelen en beschermen', 'Oma blijft de oude foto’s van opa ___.', { tegen: 'verafschuwen' }),
  w(2, 'verafschuwen', 'afkeer voor iets of iemand voelen', 'Veel mensen ___ spinnen en kunnen er niet naar kijken.', { tegen: 'koesteren' }),
  w(2, 'verdacht', 'iets dat of iemand die niet helemaal te vertrouwen is', 'Die man met een zonnebril in het donker vond ik erg ___.'),
  w(2, 'aanhoudend', 'de hele tijd, zonder ophouden', 'Het regende ___, drie dagen lang.'),
  w(2, 'het mankement', 'iets waardoor iets het niet goed doet, waardoor het niet in orde is', 'Door een ___ aan de motor stopte de bus.'),
  w(2, 'tijdig', 'op tijd', 'Lever je werkstuk ___ in, dus vóór vrijdag.'),
  w(2, 'uitslaan', 'op een bepaalde manier praten', 'Na de val bleef hij allemaal rare taal ___.'),
  w(2, 'hygiënisch', 'schoon, waar je niet ziek van wordt', 'Je handen wassen voor het koken is ___.'),
  w(2, 'wemelen van', 'vol zijn met, krioelen van', 'In het voorjaar kan het in de vijver ___ van de kikkervisjes.', { kern: 'wemelen' }),
  w(2, 'beïnvloeden', 'invloed op iets of iemand uitoefenen', 'Reclame probeert te ___ wat je koopt.'),
  w(2, 'ergens aan grenzen', 'naast iets of tegen iets aan liggen', 'Onze tuinen ___ aan het bos.', { kern: 'grenzen' }),
  w(2, 'bij nader inzien', 'na ergens nog eens over gedacht te hebben', 'Eerst wilde ik de rode jas, maar ___ koos ik de blauwe.', U),

  w(3, 'zich verzetten tegen', 'proberen iets tegen te houden of niet door te laten gaan', 'De bewoners gaan zich ___ tegen de nieuwe snelweg.', { kern: 'verzetten', tegen: 'berusten in' }),
  w(3, 'berusten in', 'accepteren dat iets niet veranderd kan worden', 'Het regent op je verjaardag, je moet er maar in ___.', { kern: 'berusten', tegen: 'zich verzetten tegen' }),
  w(3, 'ten gunste van', 'gunstig voor, in het voordeel van', 'De scheidsrechter floot ___ ons team: wij kregen een vrije trap.', { ...U, tegen: 'ten nadele van' }),
  w(3, 'ten nadele van', 'ongunstig voor, in het nadeel van', 'De nieuwe regel is ___ de kleine winkels: zij verliezen klanten.', { ...U, tegen: 'ten gunste van' }),
  w(3, 'de realiteit', 'de werkelijkheid, hoe iets echt is', 'In dromen kun je vliegen, maar in de ___ niet.'),
  w(3, 'de lariekoek', 'de onzin', 'Dat verhaal over een pratende vis is pure ___.'),
  w(3, 'de basis', 'het uitgangspunt, datgene waar je van uit moet gaan', 'Goed kunnen lezen is de ___ voor alle vakken.'),
  w(3, 'de inspiratie', 'de toestand waarin je creatief nadenkt en goede ideeën krijgt', 'De schrijver kreeg ___ voor het boek tijdens een wandeling.'),
  w(3, 'het voorval', 'een vaak onverwachte of ongewone gebeurtenis', 'Na het ___ op het schoolplein moesten de jongens bij de directeur komen.'),
  w(3, 'het element', 'elk van de delen waaruit iets is opgebouwd, onderdeel', 'Water is een belangrijk ___ in dit schilderij.'),
  w(3, 'de omstandigheden', 'de feiten en gebeurtenissen die met een bepaalde situatie te maken hebben', 'Door de ___ ging de wedstrijd niet door: er lag te veel sneeuw.'),
  w(3, 'heldhaftig', 'erg dapper en moedig', 'De brandweervrouw haalde ___ het katje uit het brandende huis.'),
  w(3, 'achterdochtig', 'als je iets of iemand niet vertrouwt', 'De winkelier keek ___ naar de jongen met de grote tas.'),
  w(3, 'dat kun je wel op je buik schrijven', 'dat gaat niet door, daar hoef je niet op te rekenen', 'Een nieuwe fiets voor je verjaardag? Dat kun je wel ___.', { ...U, kern: 'op je buik schrijven' }),
  w(3, 'door de zure appel heen bijten', 'iets doen wat heel vervelend is, maar wel moet gebeuren', 'De tandarts is niet leuk, maar je moet ___ bijten.', { ...U, kern: 'door de zure appel heen' }),
]

export const BLOKKEN_2_8 = { 2: BLOK2, 3: BLOK3, 4: BLOK4, 5: BLOK5, 6: BLOK6, 7: BLOK7, 8: BLOK8 }
