const fs = require('fs');

// NIVEAU 1 — Eenvoudige verhaaltjessommen
const n1 = [
  { id:1, contextText:'Emma spaart elke week 4 euro. Ze spaart al 9 weken.', contextImage:null, questionText:'Hoeveel euro heeft Emma nu gespaard?', type:'open', options:null },
  { id:2, contextText:'In een fruitschaal liggen 24 sinaasappels. Ze worden gelijk verdeeld over 6 bakjes.', contextImage:null, questionText:'Hoeveel sinaasappels liggen er in elk bakje?', type:'open', options:null },
  { id:3, contextText:'Een bibliotheek heeft 5 rekken. Op elk rek staan 30 boeken.', contextImage:null, questionText:'Hoeveel boeken staan er in de bibliotheek?', type:'open', options:null },
  { id:4, contextText:'Thijs koopt 3 pakken melk. Elk pak kost 1 euro 20 cent.', contextImage:null, questionText:'Hoeveel betaalt Thijs in totaal?', type:'open', options:null },
  { id:5, contextText:'Op een parkeerplaats staan 56 auto\'s. Er rijden 19 auto\'s weg.', contextImage:null, questionText:'Hoeveel auto\'s staan er nog op de parkeerplaats?', type:'open', options:null },
  { id:6, contextText:'Nadia deelt 36 stickers gelijk uit aan 4 vriendinnen.', contextImage:null, questionText:'Hoeveel stickers krijgt elke vriendin?', type:'open', options:null },
  { id:7, contextText:'Een trein rijdt 120 km per uur. De rit duurt 2 uur.', contextImage:null, questionText:'Hoeveel kilometer rijdt de trein in totaal?', type:'open', options:null },
  { id:8, contextText:'Roos heeft 10 euro. Ze geeft 3 euro en 50 cent uit aan een broodje.', contextImage:null, questionText:'Hoeveel euro heeft Roos nog over?', type:'open', options:null },
  { id:9, contextText:'In een klas zitten 28 leerlingen. De helft van de klas is een meisje.', contextImage:null, questionText:'Hoeveel meisjes zitten er in de klas?', type:'open', options:null },
  { id:10, contextText:'Een boer heeft 7 velden. Op elk veld staan 25 appelbomen.', contextImage:null, questionText:'Hoeveel appelbomen heeft de boer in totaal?', type:'open', options:null },
  { id:11, contextText:'Lukas heeft 40 euro gespaard. Hij geeft een kwart uit aan een boek.', contextImage:null, questionText:'Hoeveel euro geeft Lukas uit aan het boek?', type:'open', options:null },
  { id:12, contextText:'Een vliegtuig vertrekt om 09:30 en landt om 13:00.', contextImage:null, questionText:'Hoe lang duurt de vlucht?', type:'open', options:null },
  { id:13, contextText:'In een doos zitten 48 potloden. Ze worden verdeeld over 8 groepjes.', contextImage:null, questionText:'Hoeveel potloden krijgt elk groepje?', type:'open', options:null },
  { id:14, contextText:'Sofie loopt elke dag 3 km. In een week loopt ze 5 dagen.', contextImage:null, questionText:'Hoeveel kilometer loopt Sofie in een week?', type:'open', options:null },
  { id:15, contextText:'Een winkel verkoopt 9 fietsen per dag. De winkel is 5 dagen per week open.', contextImage:null, questionText:'Hoeveel fietsen verkoopt de winkel per week?', type:'open', options:null },
  { id:16, contextText:'Max heeft 20 kaartjes. Hij geeft er 7 weg aan zijn broer.', contextImage:null, questionText:'Hoeveel kaartjes heeft Max nog over?', type:'open', options:null },
  { id:17, contextText:'In een zwembad zijn 6 banen. Elke baan is 25 meter lang.', contextImage:null, questionText:'Hoe lang is het zwembad?', type:'open', options:null },
  { id:18, contextText:'Anna koopt 2 pakken sinaasappelsap. Elk pak kost 2 euro 40 cent.', contextImage:null, questionText:'Hoeveel betaalt Anna in totaal?', type:'open', options:null },
  { id:19, contextText:'Op een speelplein spelen 63 kinderen. Een derde gaat naar huis.', contextImage:null, questionText:'Hoeveel kinderen blijven er over op het speelplein?', type:'open', options:null },
  { id:20, contextText:'Een kok heeft 5 kg aardappelen nodig. Hij heeft al 2 kg 500 gram.', contextImage:null, questionText:'Hoeveel kilogram aardappelen moet hij nog kopen?', type:'open', options:null },
  { id:21, contextText:'5.400 + 3.200 =', contextImage:null, questionText:'Bereken de uitkomst.', type:'open', options:null },
  { id:22, contextText:'8.000 − 2.750 =', contextImage:null, questionText:'Bereken de uitkomst.', type:'open', options:null },
  { id:23, contextText:'In een speelgoedwinkel kost een doos blokken 8 euro. Een klant koopt 6 dozen.', contextImage:null, questionText:'Hoeveel betaalt de klant?', type:'open', options:null },
  { id:24, contextText:'Een school heeft 240 leerlingen. Ze worden verdeeld over 8 klassen.', contextImage:null, questionText:'Hoeveel leerlingen zitten er in elke klas?', type:'open', options:null },
  { id:25, contextText:'Tom fietst om 08:15 weg. Hij komt om 09:00 aan.', contextImage:null, questionText:'Hoe lang heeft Tom gefietst?', type:'open', options:null },
  { id:26, contextText:'Vier boeken wegen elk 300 gram.', contextImage:null, questionText:'Hoeveel gram wegen de 4 boeken samen?', type:'open', options:null },
  { id:27, contextText:'Lisa heeft 25 euro. Ze koopt een tijdschrift voor 3 euro en 95 cent.', contextImage:null, questionText:'Hoeveel wisselgeld krijgt Lisa terug?', type:'open', options:null },
  { id:28, contextText:'In een dierentuin wonen 12 leeuwen, 8 zebras en 5 neushoorns.', contextImage:null, questionText:'Hoeveel dieren zijn dat in totaal?', type:'open', options:null },
  { id:29, contextText:'Een klas maakt een muurkrant. Elke leerling schrijft 2 stukjes. Er zijn 18 leerlingen.', contextImage:null, questionText:'Hoeveel stukjes zijn er in totaal?', type:'open', options:null },
  { id:30, contextText:'Een wateremmer bevat 8 liter. Hij is voor de helft gevuld.', contextImage:null, questionText:'Hoeveel liter water zit er in de emmer?', type:'open', options:null },
  { id:31, contextText:'Een schaatser rijdt 6 rondjes van elk 400 meter.', contextImage:null, questionText:'Hoeveel meter heeft hij in totaal gereden?', type:'open', options:null },
  { id:32, contextText:'Mariam koopt 4 broodjes voor 1 euro 25 cent per stuk.', contextImage:null, questionText:'Hoeveel betaalt ze in totaal?', type:'open', options:null },
  { id:33, contextText:'In een doos zitten 5 lagen chocolaatjes. Elke laag heeft 12 chocolaatjes.', contextImage:null, questionText:'Hoeveel chocolaatjes zitten er in de doos?', type:'open', options:null },
  { id:34, contextText:'Een voetbalcompetitie duurt 20 weken. Een team speelt elke week 1 wedstrijd.', contextImage:null, questionText:'Hoeveel wedstrijden speelt het team in totaal?', type:'open', options:null },
  { id:35, contextText:'Joep heeft 100 euro. Hij besteedt 35 euro aan kleren en 28 euro aan schoenen.', contextImage:null, questionText:'Hoeveel euro heeft Joep nog over?', type:'open', options:null },
  { id:36, contextText:'Een school bestelt 9 dozen met 24 pennen per doos.', contextImage:null, questionText:'Hoeveel pennen bestelt de school in totaal?', type:'open', options:null },
  { id:37, contextText:'Een wandelroute is 16 km lang. Pieter heeft al 7 km gelopen.', contextImage:null, questionText:'Hoeveel kilometer moet Pieter nog lopen?', type:'open', options:null },
  { id:38, contextText:'In een klas doen 32 leerlingen mee aan een spel. Ze spelen in groepjes van 4.', contextImage:null, questionText:'Hoeveel groepjes zijn er?', type:'open', options:null },
  { id:39, contextText:'Een trui kost 45 euro. In de uitverkoop is hij 10 euro goedkoper.', contextImage:null, questionText:'Hoeveel kost de trui in de uitverkoop?', type:'open', options:null },
  { id:40, contextText:'Een schaatsclub heeft 56 leden. Een kwart van de leden is jeugdlid.', contextImage:null, questionText:'Hoeveel jeugdleden heeft de schaatsclub?', type:'open', options:null },
  { id:41, contextText:'Een auto verbruikt 6 liter benzine per 100 km. De tank bevat 42 liter.', contextImage:null, questionText:'Hoeveel kilometer kan de auto rijden met een volle tank?', type:'open', options:null },
  { id:42, contextText:'Op een verjaardag komen 14 gasten. Elke gast eet gemiddeld 3 kaasblokjes.', contextImage:null, questionText:'Hoeveel kaasblokjes worden er in totaal opgegeten?', type:'open', options:null },
  { id:43, contextText:'Een recept voor 4 personen vraagt 200 gram bloem. Kiri kookt voor 8 personen.', contextImage:null, questionText:'Hoeveel gram bloem heeft Kiri nodig?', type:'open', options:null },
  { id:44, contextText:'9 × 7 =', contextImage:null, questionText:'Bereken de uitkomst.', type:'open', options:null },
  { id:45, contextText:'72 ÷ 8 =', contextImage:null, questionText:'Bereken de uitkomst.', type:'open', options:null },
  { id:46, contextText:'Een hond weegt 12 kg. Een kat weegt een derde van het gewicht van de hond.', contextImage:null, questionText:'Hoeveel kilogram weegt de kat?', type:'open', options:null },
  { id:47, contextText:'In een dorp wonen 1.200 mensen. 300 mensen zijn kind.', contextImage:null, questionText:'Hoeveel procent van de mensen is kind?', type:'open', options:null },
  { id:48, contextText:'Een fles bevat 1,5 liter sap. Je schenkt 4 glazen van elk 250 ml in.', contextImage:null, questionText:'Hoeveel milliliter sap blijft er over?', type:'open', options:null },
  { id:49, contextText:'Een groep van 35 kinderen gaat naar een pretpark. Entree kost 8 euro per kind.', contextImage:null, questionText:'Hoeveel betaalt de groep in totaal?', type:'open', options:null },
  { id:50, contextText:'Een tuin is 8 meter lang en 5 meter breed.', contextImage:null, questionText:'Hoe groot is de oppervlakte van de tuin in vierkante meter?', type:'open', options:null },
];

// NIVEAU 2 — Middelniveau
const n2 = [
  { id:1, contextText:'Een sportclub heeft 9 teams. In elk team spelen 11 spelers.', contextImage:null, questionText:'Hoeveel spelers zijn er in totaal?', type:'open', options:null },
  { id:2, contextText:'Een supermarkt ontvangt 432 blikjes. Ze worden gelijk verdeeld over 8 vakken.', contextImage:null, questionText:'Hoeveel blikjes staan er in elk vak?', type:'open', options:null },
  { id:3, contextText:'Een bakker verkoopt brood voor 2 euro 75 cent. Hij verkoopt er 60 per dag.', contextImage:null, questionText:'Hoeveel euro verdient hij op een dag met brood?', type:'open', options:null },
  { id:4, contextText:'Een busreis kost 18 euro per persoon. Er gaan 24 mensen mee.', contextImage:null, questionText:'Hoeveel betalen ze in totaal?', type:'open', options:null },
  { id:5, contextText:'Een zwembad is 840 meter lang. Sanne zwemt 7 banen.', contextImage:null, questionText:'Hoeveel meter zwemt Sanne in totaal?', type:'open', options:null },
  { id:6, contextText:'Een televisie kost normaal 360 euro. Nu heeft hij 25% korting.', contextImage:null, questionText:'Hoeveel euro korting krijg je?', type:'open', options:null },
  { id:7, contextText:'Een bakker bakt elke dag 15 soorten brood. Van elk soort bakt hij 24 stuks.', contextImage:null, questionText:'Hoeveel broden bakt de bakker elke dag in totaal?', type:'open', options:null },
  { id:8, contextText:'Een marathon is 42 kilometer en 195 meter. Daan heeft al 18 km gelopen.', contextImage:null, questionText:'Hoeveel kilometer moet hij nog lopen? Rond af op hele kilometers.', type:'open', options:null },
  { id:9, contextText:'In een zak zitten 500 gram rijst. Een recept vraagt 125 gram per portie.', contextImage:null, questionText:'Voor hoeveel porties is de zak genoeg?', type:'open', options:null },
  { id:10, contextText:'Een trui is afgeprijsd van 60 euro naar 45 euro.', contextImage:null, questionText:'Hoeveel procent korting is dat?', type:'open', options:null },
  { id:11, contextText:'Een waterfles bevat 0,75 liter. Lena drinkt elke dag 3 volle flessen leeg.', contextImage:null, questionText:'Hoeveel liter drinkt Lena per dag?', type:'open', options:null },
  { id:12, contextText:'Een school heeft 360 leerlingen. 45 leerlingen gaan naar de bibliotheek.', contextImage:null, questionText:'Welk deel van de school gaat naar de bibliotheek? Schrijf als breuk.', type:'open', options:null },
  { id:13, contextText:'Een trein rijdt 72 km per uur. De afstand tussen twee steden is 216 km.', contextImage:null, questionText:'Hoe lang duurt de treinreis?', type:'open', options:null },
  { id:14, contextText:'Een voetbalveld is 105 meter lang en 68 meter breed.', contextImage:null, questionText:'Hoe groot is de oppervlakte van het veld in vierkante meter?', type:'open', options:null },
  { id:15, contextText:'Bij een evenement zijn 1.200 bezoekers. Hiervan is 60% volwassene.', contextImage:null, questionText:'Hoeveel bezoekers zijn volwassene?', type:'open', options:null },
  { id:16, contextText:'Een fiets kost 480 euro. Je betaalt 20% aanbetaling.', contextImage:null, questionText:'Hoeveel euro betaal je als aanbetaling?', type:'open', options:null },
  { id:17, contextText:'Een recept voor 6 personen vraagt 900 ml melk. Bram kookt voor 4 personen.', contextImage:null, questionText:'Hoeveel milliliter melk heeft Bram nodig?', type:'open', options:null },
  { id:18, contextText:'Een emmer weegt leeg 1,2 kg. Gevuld met water weegt hij 9,7 kg.', contextImage:null, questionText:'Hoeveel kilogram weegt het water?', type:'open', options:null },
  { id:19, contextText:'In een klas zijn 24 leerlingen. 3/8 van de klas heeft een fiets.', contextImage:null, questionText:'Hoeveel leerlingen hebben een fiets?', type:'open', options:null },
  { id:20, contextText:'Een bedrijf maakt 2.400 producten per dag. In een werkweek van 5 dagen worden ze geleverd.', contextImage:null, questionText:'Hoeveel producten worden er per week gemaakt?', type:'open', options:null },
  { id:21, contextText:'3,6 km = ? meter', contextImage:null, questionText:'Hoeveel meter is dat?', type:'open', options:null },
  { id:22, contextText:'2.500 gram = ? kilogram', contextImage:null, questionText:'Hoeveel kilogram is dat?', type:'open', options:null },
  { id:23, contextText:'Een klimmer beklimt een berg van 3.400 meter. Hij klom al 2.175 meter.', contextImage:null, questionText:'Hoeveel meter moet hij nog klimmen?', type:'open', options:null },
  { id:24, contextText:'Een zak met appels weegt 3 kg. Elke appel weegt gemiddeld 150 gram.', contextImage:null, questionText:'Hoeveel appels zitten er in de zak?', type:'open', options:null },
  { id:25, contextText:'Een café verkoopt 180 koppen koffie per dag. De prijs is 2 euro 50 cent per kop.', contextImage:null, questionText:'Hoeveel euro verdient het café per dag aan koffie?', type:'open', options:null },
  { id:26, contextText:'Een tegel is 30 cm lang en 30 cm breed. Een vloer is 3 meter bij 3 meter.', contextImage:null, questionText:'Hoeveel tegels zijn er nodig voor de vloer?', type:'open', options:null },
  { id:27, contextText:'Een auto rijdt 520 km op 40 liter benzine.', contextImage:null, questionText:'Hoeveel kilometer rijdt de auto op 1 liter?', type:'open', options:null },
  { id:28, contextText:'Een speelgoedwinkel verkoopt 5/8 van haar voorraad bouwsets. De voorraad was 240 stuks.', contextImage:null, questionText:'Hoeveel bouwsets worden er verkocht?', type:'open', options:null },
  { id:29, contextText:'Een school heeft 12 lokalen. Elk lokaal heeft 6 ramen van elk 90 cm breed.', contextImage:null, questionText:'Hoeveel centimeter raamoppervlakte is er per lokaal?', type:'open', options:null },
  { id:30, contextText:'Julia verdient 12 euro per uur. Ze werkt 6,5 uur.', contextImage:null, questionText:'Hoeveel euro verdient ze?', type:'open', options:null },
  { id:31, contextText:'Een tank bevat 1.200 liter water. Elke dag stroomt er 75 liter weg.', contextImage:null, questionText:'Na hoeveel dagen is de tank leeg?', type:'open', options:null },
  { id:32, contextText:'Een T-shirt kost 18 euro. Er is 15% btw.', contextImage:null, questionText:'Hoeveel bedraagt de btw op het T-shirt?', type:'open', options:null },
  { id:33, contextText:'Een trein vertrekt om 14:45 en komt aan om 17:20.', contextImage:null, questionText:'Hoe lang duurt de treinreis?', type:'open', options:null },
  { id:34, contextText:'Een winkel koopt dozen in voor 6 euro en verkoopt ze voor 9 euro.', contextImage:null, questionText:'Hoeveel procent winst maakt de winkel per doos?', type:'open', options:null },
  { id:35, contextText:'In een klas van 28 leerlingen heeft 3/4 een huisdier.', contextImage:null, questionText:'Hoeveel leerlingen hebben een huisdier?', type:'open', options:null },
  { id:36, contextText:'Een marathon loper loopt 42 km in 3,5 uur.', contextImage:null, questionText:'Hoeveel kilometer loopt hij gemiddeld per uur?', type:'open', options:null },
  { id:37, contextText:'Een machine maakt 150 schroeven per minuut. De machine draait 8 uur per dag.', contextImage:null, questionText:'Hoeveel schroeven maakt de machine per dag?', type:'open', options:null },
  { id:38, contextText:'4.200 ml = ? liter', contextImage:null, questionText:'Hoeveel liter is dat?', type:'open', options:null },
  { id:39, contextText:'Een werkster verdient 14,50 euro per uur. Ze werkt 32 uur per week.', contextImage:null, questionText:'Hoeveel euro verdient ze per week?', type:'open', options:null },
  { id:40, contextText:'Een supermarkt heeft 560 klanten per dag. In het weekend komen er 30% meer klanten.', contextImage:null, questionText:'Hoeveel klanten komen er op een dag in het weekend?', type:'open', options:null },
  { id:41, contextText:'Een schilderij heeft een lijst. De lijst is 120 cm breed en 80 cm hoog.', contextImage:null, questionText:'Hoe lang is de omtrek van de lijst in centimeter?', type:'open', options:null },
  { id:42, contextText:'Een bus vertrekt om 08:12 en rijdt 45 minuten.', contextImage:null, questionText:'Hoe laat komt de bus aan?', type:'open', options:null },
  { id:43, contextText:'Een brood weegt 800 gram. Je snijdt het in gelijke plakken van 50 gram.', contextImage:null, questionText:'Hoeveel plakken krijg je?', type:'open', options:null },
  { id:44, contextText:'Een boom groeit elk jaar 35 cm. Nu is hij 2 meter 10 centimeter.', contextImage:null, questionText:'Hoe hoog was de boom 3 jaar geleden?', type:'open', options:null },
  { id:45, contextText:'In een sporthal kunnen 8 teams tegelijk trainen. Elk team heeft 12 spelers.', contextImage:null, questionText:'Hoeveel spelers kunnen er tegelijk trainen?', type:'open', options:null },
  { id:46, contextText:'Van een vat olijfolie van 18 liter wordt 1/3 verkocht.', contextImage:null, questionText:'Hoeveel liter is er nog in het vat?', type:'open', options:null },
  { id:47, contextText:'Een kledingzaak geeft 30% korting op alle jassen. Een jas kost normaal 90 euro.', contextImage:null, questionText:'Wat is de prijs met korting?', type:'open', options:null },
  { id:48, contextText:'Een klas van 30 leerlingen gaat stemmen op een liedje. 18 leerlingen stemmen op nummer 1.', contextImage:null, questionText:'Hoeveel procent stemt op nummer 1?', type:'open', options:null },
  { id:49, contextText:'Een taart wordt in 8 gelijke stukken gesneden. Kai eet 3 stukken.', contextImage:null, questionText:'Welk deel van de taart heeft Kai gegeten? Schrijf als breuk.', type:'open', options:null },
  { id:50, contextText:'Een concert begint om 20:00 en duurt 2 uur en 45 minuten.', contextImage:null, questionText:'Hoe laat is het concert afgelopen?', type:'open', options:null },
];

// NIVEAU 3 — Gevorderde verhaaltjessommen
const n3 = [
  { id:1, contextText:'Mia fietst een route van 18 km. Ze heeft al 7,4 km gefietst.', contextImage:null, questionText:'Hoeveel kilometer moet ze nog fietsen?', type:'open', options:null },
  { id:2, contextText:'Een gezin van 4 personen gaat naar de bioscoop. Een kaartje kost 13 euro 50. De kinderen (2 personen) betalen de helft.', contextImage:null, questionText:'Hoeveel betalen ze in totaal?', type:'open', options:null },
  { id:3, contextText:'Een schoenenwinkel geeft 20% korting op alle schoenen. Een paar kost normaal 85 euro.', contextImage:null, questionText:'Hoeveel betaalt de klant na de korting?', type:'open', options:null },
  { id:4, contextText:'Hoeveel centiliter is 3,5 liter?', contextImage:null, questionText:'Schrijf je antwoord in centiliter.', type:'open', options:null },
  { id:5, contextText:'Een zwemmer zwemt 100 meter in 1 minuut en 8 seconden. Zijn teamgenoot doet er 1 minuut en 22 seconden over.', contextImage:null, questionText:'Hoeveel seconden sneller is de eerste zwemmer?', type:'open', options:null },
  { id:6, contextText:'Een trein rijdt van stad A naar stad B. De afstand is 280 km. De trein rijdt 140 km per uur.', contextImage:null, questionText:'Hoe lang duurt de rit? Geef je antwoord in uren.', type:'open', options:null },
  { id:7, contextText:'Een supermarkt koopt appels in voor 0,80 euro per kilo en verkoopt ze voor 1,20 euro per kilo.', contextImage:null, questionText:'Hoeveel procent winst maakt de supermarkt?', type:'open', options:null },
  { id:8, contextText:'Een fabriek maakt 4.500 flessen per dag. Op een dag staan er 12 machines. Elke machine maakt evenveel.', contextImage:null, questionText:'Hoeveel flessen maakt elke machine per dag?', type:'open', options:null },
  { id:9, contextText:'Bij een verkiezing op school stemmen 240 leerlingen. Partij A krijgt 35% van de stemmen, partij B krijgt 25%, de rest stemt op partij C.', contextImage:null, questionText:'Hoeveel leerlingen stemmen op partij C?', type:'open', options:null },
  { id:10, contextText:'Een veld is 120 meter lang en 85 meter breed. Er wordt langs de rand een hek geplaatst.', contextImage:null, questionText:'Hoe lang is het hek in totaal?', type:'open', options:null },
  { id:11, contextText:'Een fietser legt in 4,5 uur een afstand van 126 km af.', contextImage:null, questionText:'Hoe snel rijdt de fietser gemiddeld in km per uur?', type:'open', options:null },
  { id:12, contextText:'Een winkel verkoopt 3/5 van een lading van 350 dozen.', contextImage:null, questionText:'Hoeveel dozen worden er verkocht?', type:'open', options:null },
  { id:13, contextText:'Een restaurant rekent 21% btw op dranken. Een fles water kost 2 euro exclusief btw.', contextImage:null, questionText:'Hoeveel betaal je inclusief btw?', type:'open', options:null },
  { id:14, contextText:'Een huis heeft een energielabel A. Het verbruikt 1.800 kWh per jaar. Een huis met label D verbruikt 45% meer.', contextImage:null, questionText:'Hoeveel kWh verbruikt het huis met label D per jaar?', type:'open', options:null },
  { id:15, contextText:'Een school ontvangt 12.000 euro subsidie. Hiervan gaat 1/4 naar sport, 1/3 naar kunst, de rest naar lessen.', contextImage:null, questionText:'Hoeveel euro gaat er naar lessen?', type:'open', options:null },
  { id:16, contextText:'Een auto rijdt gemiddeld 1 op 14. De tank bevat 56 liter.', contextImage:null, questionText:'Hoeveel kilometer kan de auto rijden met een volle tank?', type:'open', options:null },
  { id:17, contextText:'Een waterpomp pompt 240 liter per uur. Een zwembad bevat 48.000 liter.', contextImage:null, questionText:'Hoeveel uur duurt het om het zwembad te vullen?', type:'open', options:null },
  { id:18, contextText:'Een handelaar koopt 200 kg noten voor 180 euro. Hij verkoopt ze voor 1,20 euro per kg.', contextImage:null, questionText:'Hoeveel euro winst maakt hij?', type:'open', options:null },
  { id:19, contextText:'Een rechthoekige kamer is 5,6 meter lang en 4,2 meter breed.', contextImage:null, questionText:'Hoe groot is de oppervlakte van de kamer in vierkante meter?', type:'open', options:null },
  { id:20, contextText:'Van een groep van 80 mensen heeft 15% een rijbewijs maar geen auto, 60% heeft een auto en rijbewijs, de rest heeft geen rijbewijs.', contextImage:null, questionText:'Hoeveel mensen hebben geen rijbewijs?', type:'open', options:null },
  { id:21, contextText:'Een project duurt 3 weken en 4 dagen. Hoeveel dagen is dat?', contextImage:null, questionText:'Bereken het totaal aantal dagen.', type:'open', options:null },
  { id:22, contextText:'Een loods is 40 meter lang, 25 meter breed en 8 meter hoog.', contextImage:null, questionText:'Hoe groot is het volume van de loods in kubieke meter?', type:'open', options:null },
  { id:23, contextText:'Een klimmer stijgt 350 meter in 2,5 uur.', contextImage:null, questionText:'Hoeveel meter stijgt hij gemiddeld per uur?', type:'open', options:null },
  { id:24, contextText:'Op een markt worden tomaten verkocht voor 1 euro 80 cent per kilo. Eline koopt 2,5 kilo.', contextImage:null, questionText:'Hoeveel betaalt Eline?', type:'open', options:null },
  { id:25, contextText:'Een school bestelt schoolmateriaal. 12 dozen met 36 pennen per doos, 8 dozen met 24 schriften per doos.', contextImage:null, questionText:'Hoeveel stuks materiaal bestelt de school in totaal?', type:'open', options:null },
  { id:26, contextText:'Een werknemer verdient 2.400 euro per maand. Hij krijgt een loonsverhoging van 7,5%.', contextImage:null, questionText:'Hoeveel euro verdient hij na de verhoging per maand?', type:'open', options:null },
  { id:27, contextText:'Een machine maakt elke 4 minuten 1 product. De machine draait 10 uur per dag.', contextImage:null, questionText:'Hoeveel producten maakt de machine per dag?', type:'open', options:null },
  { id:28, contextText:'In een dorp wonen 3.200 mensen. In 10 jaar groeit de bevolking met 12,5%.', contextImage:null, questionText:'Hoeveel mensen wonen er dan in het dorp?', type:'open', options:null },
  { id:29, contextText:'Een supermarkt verkoopt per dag gemiddeld 840 liter melk. In de weekenden verkoopt hij 25% meer.', contextImage:null, questionText:'Hoeveel liter melk verkoopt de supermarkt op een zaterdag?', type:'open', options:null },
  { id:30, contextText:'Een tank bevat 1.500 liter. Na gebruik is er nog 540 liter over.', contextImage:null, questionText:'Hoeveel procent van de tank is gebruikt?', type:'open', options:null },
  { id:31, contextText:'Een boom is 12 meter hoog en werpt een schaduw van 8 meter. Een lantaarnpaal werpt een schaduw van 6 meter.', contextImage:null, questionText:'Hoe hoog is de lantaarnpaal? Gebruik verhoudingen.', type:'open', options:null },
  { id:32, contextText:'Een hotel heeft 48 kamers. Elke nacht zijn 3/4 van de kamers bezet. Een kamer kost 95 euro per nacht.', contextImage:null, questionText:'Hoeveel euro verdient het hotel per nacht?', type:'open', options:null },
  { id:33, contextText:'Een lening van 2.000 euro heeft 5% rente per jaar.', contextImage:null, questionText:'Hoeveel rente betaal je na 1 jaar?', type:'open', options:null },
  { id:34, contextText:'Een sporttournee bestaat uit 4 wedstrijden. Het team scoorde: 3, 5, 2 en 6 doelpunten.', contextImage:null, questionText:'Hoeveel doelpunten scoorden ze gemiddeld per wedstrijd?', type:'open', options:null },
  { id:35, contextText:'Een straat is 0,8 km lang. Er staan aan beide kanten bomen. Om de 10 meter staat een boom.', contextImage:null, questionText:'Hoeveel bomen staan er aan een kant van de straat?', type:'open', options:null },
  { id:36, contextText:'Een bakkerij verkoopt op maandag 240 broden, op dinsdag 180, op woensdag 210 en op donderdag 270.', contextImage:null, questionText:'Hoeveel broden werden er gemiddeld per dag verkocht?', type:'open', options:null },
  { id:37, contextText:'Een vlucht vertrekt om 22:40 en landt 8 uur en 15 minuten later.', contextImage:null, questionText:'Hoe laat landt het vliegtuig (lokale tijd)?', type:'open', options:null },
  { id:38, contextText:'Een kledingbedrijf produceert shirts. De kosten per shirt zijn 12 euro. De verkoopprijs is 30 euro.', contextImage:null, questionText:'Hoeveel procent is de winstmarge?', type:'open', options:null },
  { id:39, contextText:'In een klas van 32 leerlingen heeft 5/8 een smartphone. Daarvan heeft de helft ook een tablet.', contextImage:null, questionText:'Hoeveel leerlingen hebben zowel een smartphone als een tablet?', type:'open', options:null },
  { id:40, contextText:'Een waterleiding lekt 3 liter per uur. Na 24 uur is er 72 liter gelekt. Klopt dit?', contextImage:null, questionText:'Klopt de berekening? Leg uit en geef het juiste antwoord.', type:'open', options:null },
  { id:41, contextText:'Een koffer weegt 23,6 kg. Het maximale gewicht is 20 kg. Je haalt er spullen uit.', contextImage:null, questionText:'Hoeveel kilogram moet er minimaal uit de koffer?', type:'open', options:null },
  { id:42, contextText:'Een restaurant bestelt 15 kg rijst per week. In een maand van 4 weken stijgt de prijs van 2,40 euro naar 2,70 euro per kg.', contextImage:null, questionText:'Hoeveel meer betaalt het restaurant per maand na de prijsstijging?', type:'open', options:null },
  { id:43, contextText:'5/8 van een getal is 40.', contextImage:null, questionText:'Wat is het getal?', type:'open', options:null },
  { id:44, contextText:'Een rente van 4% per jaar over 3.500 euro.', contextImage:null, questionText:'Hoeveel euro rente krijg je na 2 jaar?', type:'open', options:null },
  { id:45, contextText:'Een schip vaart 18 km per uur. Het moet 270 km afleggen.', contextImage:null, questionText:'Hoe lang duurt de vaart?', type:'open', options:null },
  { id:46, contextText:'Een gemeentebudget is 8.000.000 euro. Hiervan gaat 35% naar onderwijs, 20% naar sport, de rest naar overige zaken.', contextImage:null, questionText:'Hoeveel euro gaat er naar overige zaken?', type:'open', options:null },
  { id:47, contextText:'Een fruitkraam verkoopt in een week 120 kg appels, 85 kg peren en 60 kg druiven.', contextImage:null, questionText:'Hoeveel kilogram fruit wordt er in totaal verkocht?', type:'open', options:null },
  { id:48, contextText:'Een groentesoep bevat per 100 ml: 25 kcal. Een portie is 350 ml.', contextImage:null, questionText:'Hoeveel kcal bevat een portie soep?', type:'open', options:null },
  { id:49, contextText:'Een ijsbaan is 60 meter lang en 30 meter breed. Er staat een omheining rondom.', contextImage:null, questionText:'Hoe lang is de omheining?', type:'open', options:null },
  { id:50, contextText:'Een bedrijf heeft 250 werknemers. Na een reorganisatie werken er 15% minder mensen.', contextImage:null, questionText:'Hoeveel werknemers zijn er na de reorganisatie?', type:'open', options:null },
];

fs.writeFileSync('public/iep_niveau1.json', JSON.stringify(n1, null, 2));
fs.writeFileSync('public/iep_niveau2.json', JSON.stringify(n2, null, 2));
fs.writeFileSync('public/iep_niveau3.json', JSON.stringify(n3, null, 2));
console.log('Done! n1:', n1.length, 'n2:', n2.length, 'n3:', n3.length);
